$axure.loadCurrentPage({
  "url":"cms___sns__-cms__-__.html",
  "generationDate":new Date(1441157430442.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a5b209ffe2484523babbe2d3fc5b7099",
    "type":"Axure:Page",
    "name":"cms管理和sns管理-cms管理-完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7733f2fd9fe14621b3f1015ea41fc849",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":1180,
              "height":740}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"838bbf671ff24ad1947d48a1aedb143f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":1180,
                  "height":740}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cms___sns__-cms__-__/u0.png"}},
{
          "id":"54a81e2856134588959029bdecd6d6ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":140},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5844e10443c42298fc6f8a0e9762c4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":140},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"07e50916acbc4fc49b37b3f992eb2878",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":190},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"323365b6147249eb86a73e4664e9b04c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":190},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"6c1a4c3fe02a4489b4e99442dc55641e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":240},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ae8698edbbe42809d35dd209592798d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":240},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"bc88b0480bca43e486a2d3e10ed491ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":290},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d3ffe243f064965b8979f5b1cc7ad72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":290},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"5d973a5e50104669b67dd2f294838d49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":340},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afebb0a4a038448c86f2a251eb0ecc9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":340},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"0d5e24abfef74c348b12190cb0e89345",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":390},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d860279740d4cb58c2f6bf65d1f965b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":390},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"137cb167d3e04255a63b2ca7dd584810",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":55,
              "y":440},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52581d9293b24145bd04103660d4eb9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":55,
                  "y":440},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u2.png"}},
{
          "id":"2e2416aafee54644b9019b1994931e82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":570},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"797ddbbc9cae490b89f3d3b0b1f86a68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":570},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"4118283fab014fe382a240da8681ae24",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":76},
            "size":{
              "width":1180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/预约管理-未下载-完成/u18_line.png"}},
{
          "id":"039a173110a9433da5968591ec431773",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":26},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0b24939e7a7454f870284cfef5e6fc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":26},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8612e1a512fd4ac8ba8a67e6b3d86496",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1137,
              "y":26},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34ffbcc554934d598fdce81a4ea0c5a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1137,
                  "y":26},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6432a911900840d2a684f1b086ca7b6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":18},
            "size":{
              "width":135,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e35173cb4634047b6a3721ccdaebeec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":18},
                "size":{
                  "width":135,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u23.png"}},
{
          "id":"f10a545c1945431a973b4c15a202cc23",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":33},
            "size":{
              "width":270,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be1458fccb9c49368e12e6a78dd2496f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":33},
                "size":{
                  "width":270,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"136323daa280414d94feb727cceb0013",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":52},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcec479e5f2641f4b6df5d75106c8ebf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":52},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21adb20a18864dcfb63c6566b9c9ae3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1147,
              "y":52},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4323253353164b76b2062c7f76b8121c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1147,
                  "y":52},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9c044232e5f467781872d461cded418",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":140},
            "size":{
              "width":950,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83fa953ff02449feacb3f330ab25e237",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":140},
                "size":{
                  "width":950,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cms___sns__-cms__-__/u31.png"}},
{
          "id":"c673b6d02f874030869cc4c28441669b",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":187},
            "size":{
              "width":978,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ee41195c4474428a5b11cd7cfbf6ad5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"34c02a4e615b49a3a7d8b7f93967c9fc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u44.png"}},
{
              "id":"f8fd082367c24545ad501481fc1e7775",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":150,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9e2bd4c609cb499998b3defa8c72efc8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":150,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u54.png"}},
{
              "id":"e2c3e8788c2e45a1b37cf17dda36212c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":77},
                "size":{
                  "width":150,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f1271bb6cd2949f28da46cfdf451afee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":77},
                    "size":{
                      "width":150,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u64.png"}},
{
              "id":"3828bf5a72a3452ea29f0cd747a03a13",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":150,
                  "y":0},
                "size":{
                  "width":166,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8238071532ce4b4493374b3fefd3e9cd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":150,
                      "y":0},
                    "size":{
                      "width":166,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u46.png"}},
{
              "id":"a4805fd180bf4a7ebf5f690c3f9df480",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":40},
                "size":{
                  "width":166,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6dd333cd54374a99bc90c2121d11480b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":40},
                    "size":{
                      "width":166,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u56.png"}},
{
              "id":"c587fcac771e460abcc4642b6aaa5020",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":77},
                "size":{
                  "width":166,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fc0e2ebfd65c451283b06c8328a2042c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":77},
                    "size":{
                      "width":166,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u66.png"}},
{
              "id":"6b67532a3e514d48b8fa2054e4997cab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":479,
                  "y":0},
                "size":{
                  "width":153,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6283d151dec84e64b2f170545927c7b0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":479,
                      "y":0},
                    "size":{
                      "width":153,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u41.png"}},
{
              "id":"958aeca02d8a414cbb1b3e10e5356705",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":479,
                  "y":40},
                "size":{
                  "width":153,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"32b85317b91641858bea3f6961e0835b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":479,
                      "y":40},
                    "size":{
                      "width":153,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u49.png"}},
{
              "id":"32d43b4fe3534900bab7988b72042ee0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":479,
                  "y":77},
                "size":{
                  "width":153,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7b0224d28f044e2d84f3fab5f25ad382",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":479,
                      "y":77},
                    "size":{
                      "width":153,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u57.png"}},
{
              "id":"5c252479219c4b4f8c0807211bb2cfac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":632,
                  "y":0},
                "size":{
                  "width":183,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"134cda8ced274d4aafbe74b028b8a2cf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":632,
                      "y":0},
                    "size":{
                      "width":183,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cms___sns__-cms__-__/u42.png"}},
{
              "id":"db643a6d98364af38ff798b22c6dec53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":632,
                  "y":40},
                "size":{
                  "width":183,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f17b61fc389f43b8b511fb727c4d83a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":632,
                      "y":40},
                    "size":{
                      "width":183,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cms___sns__-cms__-__/u54.png"}},
{
              "id":"f0f525f6891f4b3581af0fdb97a9fd8c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":632,
                  "y":77},
                "size":{
                  "width":183,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a2cf747d3c02470a89727ec1b4b50d8f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":632,
                      "y":77},
                    "size":{
                      "width":183,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cms___sns__-cms__-__/u66.png"}},
{
              "id":"4eb10eac4f9e4d4ca718ff54de3de656",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":815,
                  "y":0},
                "size":{
                  "width":163,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56bc59dfd72e4a42b42a6f60c91c82f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":815,
                      "y":0},
                    "size":{
                      "width":163,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cms___sns__-cms__-__/u44.png"}},
{
              "id":"eacba825354b4705bde4082c0febed93",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":815,
                  "y":40},
                "size":{
                  "width":163,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4c1708d1adc544a6b2d70169204d85de",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000CC,
                      "opacity":1},
                    "location":{
                      "x":815,
                      "y":40},
                    "size":{
                      "width":163,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cms___sns__-cms__-__/u56.png"}},
{
              "id":"bb77377cd8234b3191e09055b07c6c1b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":815,
                  "y":77},
                "size":{
                  "width":163,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b44fb29dde6947b688b4a00463a0cca6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000CC,
                      "opacity":1},
                    "location":{
                      "x":815,
                      "y":77},
                    "size":{
                      "width":163,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/cms___sns__-cms__-__/u68.png"}},
{
              "id":"104e065fd0984bb79927469aaac1cbe8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":316,
                  "y":0},
                "size":{
                  "width":163,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5cffe0f34390409fb397563e1db28eef",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":316,
                      "y":0},
                    "size":{
                      "width":163,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/账号管理-账号列表-完成/u39.png"}},
{
              "id":"0644d84089b2417bbb14f66243861aed",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":316,
                  "y":40},
                "size":{
                  "width":163,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e9e3f3a755947ca97384da66c424df7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":316,
                      "y":40},
                    "size":{
                      "width":163,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/账号管理-账号列表-完成/u49.png"}},
{
              "id":"f0295b9644814eba80881187e46590dd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":316,
                  "y":77},
                "size":{
                  "width":163,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cbc60d0a3cd74df7be734ece8bf4decd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":316,
                      "y":77},
                    "size":{
                      "width":163,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/账号管理-账号列表-完成/u59.png"}}]},
{
          "id":"aa0fc6dc71504899baa8291f5b3513d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":550},
            "size":{
              "width":560,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48d373a4eef54c4e98553373f734adaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":550},
                "size":{
                  "width":560,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u101.png"}},
{
          "id":"cccfed87306945b38a1c124484034bcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":104},
            "size":{
              "width":225,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47470ef641aa44d9900b65c912c95ead",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":104},
                "size":{
                  "width":225,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"995451665ffd4bc39bfdc2bb5e613478",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":55,
              "y":490},
            "size":{
              "width":165,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ab408279c90483ab9bb5bf425bfd384",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":55,
                  "y":490},
                "size":{
                  "width":165,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cms___sns__-cms__-__/u74.png"}},
{
          "id":"7a2f8aa998bb48a1a91f7b9d42579390",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":530},
            "size":{
              "width":165,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10b2caacae05407a9d1833d5b3e57941",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":530},
                "size":{
                  "width":165,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cms___sns__-cms__-__/u76.png"}},
{
          "id":"42f36b0b222b4994b22293bc850b344e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":548,
              "y":154},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7254c005c1e148a0ac43c74af8ce8141",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":623,
              "y":162},
            "size":{
              "width":15,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/预约管理-未下载-完成/u35_line.png"}},
{
          "id":"8d8b01816a5f49c9808a9b7c4de05783",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":648,
              "y":154},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9fb22c0b857143c588a38cdd0bb8485f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":154},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e97966167a094075927f5f97bfc65c1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":158},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39da718be9354cce9b48834902bec392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":158},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4456a6255da44b3fb2660a77ba3eb004",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":157},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b4fc845b79a48efa4b2f97f7b665c41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":157},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6ae9b4a2d1343f6b9046578b9d2b355",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":760,
              "y":154},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7eb431ee2e3457988ec01ed63db713d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":760,
                  "y":154},
                "size":{
                  "width":100,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cms___sns__-cms__-__/u86.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7733f2fd9fe14621b3f1015ea41fc849":{
      "scriptId":"u0"},
    "838bbf671ff24ad1947d48a1aedb143f":{
      "scriptId":"u1"},
    "54a81e2856134588959029bdecd6d6ce":{
      "scriptId":"u2"},
    "c5844e10443c42298fc6f8a0e9762c4c":{
      "scriptId":"u3"},
    "07e50916acbc4fc49b37b3f992eb2878":{
      "scriptId":"u4"},
    "323365b6147249eb86a73e4664e9b04c":{
      "scriptId":"u5"},
    "6c1a4c3fe02a4489b4e99442dc55641e":{
      "scriptId":"u6"},
    "9ae8698edbbe42809d35dd209592798d":{
      "scriptId":"u7"},
    "bc88b0480bca43e486a2d3e10ed491ff":{
      "scriptId":"u8"},
    "1d3ffe243f064965b8979f5b1cc7ad72":{
      "scriptId":"u9"},
    "5d973a5e50104669b67dd2f294838d49":{
      "scriptId":"u10"},
    "afebb0a4a038448c86f2a251eb0ecc9a":{
      "scriptId":"u11"},
    "0d5e24abfef74c348b12190cb0e89345":{
      "scriptId":"u12"},
    "6d860279740d4cb58c2f6bf65d1f965b":{
      "scriptId":"u13"},
    "137cb167d3e04255a63b2ca7dd584810":{
      "scriptId":"u14"},
    "52581d9293b24145bd04103660d4eb9e":{
      "scriptId":"u15"},
    "2e2416aafee54644b9019b1994931e82":{
      "scriptId":"u16"},
    "797ddbbc9cae490b89f3d3b0b1f86a68":{
      "scriptId":"u17"},
    "4118283fab014fe382a240da8681ae24":{
      "scriptId":"u18"},
    "039a173110a9433da5968591ec431773":{
      "scriptId":"u19"},
    "d0b24939e7a7454f870284cfef5e6fc5":{
      "scriptId":"u20"},
    "8612e1a512fd4ac8ba8a67e6b3d86496":{
      "scriptId":"u21"},
    "34ffbcc554934d598fdce81a4ea0c5a7":{
      "scriptId":"u22"},
    "6432a911900840d2a684f1b086ca7b6f":{
      "scriptId":"u23"},
    "1e35173cb4634047b6a3721ccdaebeec":{
      "scriptId":"u24"},
    "f10a545c1945431a973b4c15a202cc23":{
      "scriptId":"u25"},
    "be1458fccb9c49368e12e6a78dd2496f":{
      "scriptId":"u26"},
    "136323daa280414d94feb727cceb0013":{
      "scriptId":"u27"},
    "dcec479e5f2641f4b6df5d75106c8ebf":{
      "scriptId":"u28"},
    "21adb20a18864dcfb63c6566b9c9ae3f":{
      "scriptId":"u29"},
    "4323253353164b76b2062c7f76b8121c":{
      "scriptId":"u30"},
    "b9c044232e5f467781872d461cded418":{
      "scriptId":"u31"},
    "83fa953ff02449feacb3f330ab25e237":{
      "scriptId":"u32"},
    "c673b6d02f874030869cc4c28441669b":{
      "scriptId":"u33"},
    "9ee41195c4474428a5b11cd7cfbf6ad5":{
      "scriptId":"u34"},
    "34c02a4e615b49a3a7d8b7f93967c9fc":{
      "scriptId":"u35"},
    "3828bf5a72a3452ea29f0cd747a03a13":{
      "scriptId":"u36"},
    "8238071532ce4b4493374b3fefd3e9cd":{
      "scriptId":"u37"},
    "104e065fd0984bb79927469aaac1cbe8":{
      "scriptId":"u38"},
    "5cffe0f34390409fb397563e1db28eef":{
      "scriptId":"u39"},
    "6b67532a3e514d48b8fa2054e4997cab":{
      "scriptId":"u40"},
    "6283d151dec84e64b2f170545927c7b0":{
      "scriptId":"u41"},
    "5c252479219c4b4f8c0807211bb2cfac":{
      "scriptId":"u42"},
    "134cda8ced274d4aafbe74b028b8a2cf":{
      "scriptId":"u43"},
    "4eb10eac4f9e4d4ca718ff54de3de656":{
      "scriptId":"u44"},
    "56bc59dfd72e4a42b42a6f60c91c82f6":{
      "scriptId":"u45"},
    "f8fd082367c24545ad501481fc1e7775":{
      "scriptId":"u46"},
    "9e2bd4c609cb499998b3defa8c72efc8":{
      "scriptId":"u47"},
    "a4805fd180bf4a7ebf5f690c3f9df480":{
      "scriptId":"u48"},
    "6dd333cd54374a99bc90c2121d11480b":{
      "scriptId":"u49"},
    "0644d84089b2417bbb14f66243861aed":{
      "scriptId":"u50"},
    "4e9e3f3a755947ca97384da66c424df7":{
      "scriptId":"u51"},
    "958aeca02d8a414cbb1b3e10e5356705":{
      "scriptId":"u52"},
    "32b85317b91641858bea3f6961e0835b":{
      "scriptId":"u53"},
    "db643a6d98364af38ff798b22c6dec53":{
      "scriptId":"u54"},
    "f17b61fc389f43b8b511fb727c4d83a8":{
      "scriptId":"u55"},
    "eacba825354b4705bde4082c0febed93":{
      "scriptId":"u56"},
    "4c1708d1adc544a6b2d70169204d85de":{
      "scriptId":"u57"},
    "e2c3e8788c2e45a1b37cf17dda36212c":{
      "scriptId":"u58"},
    "f1271bb6cd2949f28da46cfdf451afee":{
      "scriptId":"u59"},
    "c587fcac771e460abcc4642b6aaa5020":{
      "scriptId":"u60"},
    "fc0e2ebfd65c451283b06c8328a2042c":{
      "scriptId":"u61"},
    "f0295b9644814eba80881187e46590dd":{
      "scriptId":"u62"},
    "cbc60d0a3cd74df7be734ece8bf4decd":{
      "scriptId":"u63"},
    "32d43b4fe3534900bab7988b72042ee0":{
      "scriptId":"u64"},
    "7b0224d28f044e2d84f3fab5f25ad382":{
      "scriptId":"u65"},
    "f0f525f6891f4b3581af0fdb97a9fd8c":{
      "scriptId":"u66"},
    "a2cf747d3c02470a89727ec1b4b50d8f":{
      "scriptId":"u67"},
    "bb77377cd8234b3191e09055b07c6c1b":{
      "scriptId":"u68"},
    "b44fb29dde6947b688b4a00463a0cca6":{
      "scriptId":"u69"},
    "aa0fc6dc71504899baa8291f5b3513d4":{
      "scriptId":"u70"},
    "48d373a4eef54c4e98553373f734adaf":{
      "scriptId":"u71"},
    "cccfed87306945b38a1c124484034bcc":{
      "scriptId":"u72"},
    "47470ef641aa44d9900b65c912c95ead":{
      "scriptId":"u73"},
    "995451665ffd4bc39bfdc2bb5e613478":{
      "scriptId":"u74"},
    "8ab408279c90483ab9bb5bf425bfd384":{
      "scriptId":"u75"},
    "7a2f8aa998bb48a1a91f7b9d42579390":{
      "scriptId":"u76"},
    "10b2caacae05407a9d1833d5b3e57941":{
      "scriptId":"u77"},
    "42f36b0b222b4994b22293bc850b344e":{
      "scriptId":"u78"},
    "7254c005c1e148a0ac43c74af8ce8141":{
      "scriptId":"u79"},
    "8d8b01816a5f49c9808a9b7c4de05783":{
      "scriptId":"u80"},
    "9fb22c0b857143c588a38cdd0bb8485f":{
      "scriptId":"u81"},
    "e97966167a094075927f5f97bfc65c1a":{
      "scriptId":"u82"},
    "39da718be9354cce9b48834902bec392":{
      "scriptId":"u83"},
    "4456a6255da44b3fb2660a77ba3eb004":{
      "scriptId":"u84"},
    "5b4fc845b79a48efa4b2f97f7b665c41":{
      "scriptId":"u85"},
    "a6ae9b4a2d1343f6b9046578b9d2b355":{
      "scriptId":"u86"},
    "f7eb431ee2e3457988ec01ed63db713d":{
      "scriptId":"u87"}}});