$axure.loadCurrentPage({
  "url":"分期流程介绍页面.html",
  "generationDate":new Date(1439287134175.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"449616ab5d0947bb951fda08f20e7380",
    "type":"Axure:Page",
    "name":"分期流程介绍页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"42def18c994d4be3a75a8cadc7a40246",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":30},
            "size":{
              "width":1220,
              "height":4130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0de1e30aef546a98a10c3332f5a6937",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":30},
                "size":{
                  "width":1220,
                  "height":4130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/悦享家分期/u0.png"}},
{
          "id":"4b7110b688ab4d21836f96139f268f6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":110},
            "size":{
              "width":220,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7534e8166b194cc1a3dfb95c3d2f188a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":110},
                "size":{
                  "width":220,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u2.png"}},
{
          "id":"3617bd249e084652a4e8569912807044",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":1220,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页-已登录/u4_line.png"}},
{
          "id":"58ae8727bc45405794c96b4e82d512af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":380,
              "y":113},
            "size":{
              "width":60,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"207f5a88a1a344189daf7d16763fb131",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":380,
                  "y":113},
                "size":{
                  "width":60,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u5.png"}},
{
          "id":"694cb6b9a38f4c52887919a126c4e3b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1045,
              "y":110},
            "size":{
              "width":176,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acff8414662a4ce88303fbffe4034223",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1045,
                  "y":110},
                "size":{
                  "width":176,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u7.png"}},
{
          "id":"8af777c5f46d4e31b24e80d032904698",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":41},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0d22c546a5df4b95bd8257a8771b9117",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c94a34668cac42b98489d04e7541f423",
                  "label":"",
                  "parentDynamicPanel":"8af777c5f46d4e31b24e80d032904698",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF009900,
                          "opacity":1}}},
                    "size":{
                      "width":132,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4a1e76adb3246dc8d817e22bdabb6a6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8af777c5f46d4e31b24e80d032904698",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF009900,
                              "opacity":1}}},
                        "size":{
                          "width":132,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"90e3b0550e6442c88329eea1decc776d",
                  "label":"",
                  "parentDynamicPanel":"8af777c5f46d4e31b24e80d032904698",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF009900,
                          "opacity":1}}},
                    "location":{
                      "x":128,
                      "y":0},
                    "size":{
                      "width":62,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d00773c8ec0f47d483bffe890ff7ba49",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8af777c5f46d4e31b24e80d032904698",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF009900,
                              "opacity":1}}},
                        "location":{
                          "x":128,
                          "y":0},
                        "size":{
                          "width":62,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"a66a2c477b0a4373984b6a1dc0d7ad15",
                  "label":"",
                  "parentDynamicPanel":"8af777c5f46d4e31b24e80d032904698",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF009900,
                          "opacity":1}}},
                    "location":{
                      "x":197,
                      "y":0},
                    "size":{
                      "width":62,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a1f32e16e3f44e480afc9de59a016f7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8af777c5f46d4e31b24e80d032904698",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF009900,
                              "opacity":1}}},
                        "location":{
                          "x":197,
                          "y":0},
                        "size":{
                          "width":62,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"eabbcc4f3d1c4acbaab2ee78a830dc25",
                  "label":"",
                  "parentDynamicPanel":"8af777c5f46d4e31b24e80d032904698",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF009900,
                          "opacity":1}}},
                    "location":{
                      "x":270,
                      "y":0},
                    "size":{
                      "width":67,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c2e3297269864d8c81f4eb18770e8868",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8af777c5f46d4e31b24e80d032904698",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF009900,
                              "opacity":1}}},
                        "location":{
                          "x":270,
                          "y":0},
                        "size":{
                          "width":67,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"06e1588d02df42589efb997ef2d15ef7",
                  "label":"",
                  "parentDynamicPanel":"8af777c5f46d4e31b24e80d032904698",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":183,
                      "y":0},
                    "size":{
                      "width":11,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ae740bd798f64f7ab57a21096bd3337f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8af777c5f46d4e31b24e80d032904698",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":183,
                          "y":0},
                        "size":{
                          "width":11,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页-已登录/u18.png"}},
{
                  "id":"036b6a7d4d1247c3a26c6765bff3dfef",
                  "label":"",
                  "parentDynamicPanel":"8af777c5f46d4e31b24e80d032904698",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":259,
                      "y":0},
                    "size":{
                      "width":11,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"073252bd3e71488499489cba0adf6311",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8af777c5f46d4e31b24e80d032904698",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":259,
                          "y":0},
                        "size":{
                          "width":11,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页-已登录/u18.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"d42ec715ca8d4d7b973e4bc9566e8959",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":526,
              "y":131},
            "size":{
              "width":52,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF84C225}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"214021b5d02b47879e695607dc29afbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":526,
                  "y":131},
                "size":{
                  "width":52,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF84C225}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"872cd8acb447451ab1970cceab5887e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF84C225,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1}}},
            "location":{
              "x":606,
              "y":131},
            "size":{
              "width":110,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b1fa8c3a95a4b86ad78670f2962584d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF84C225,
                      "opacity":1}}},
                "location":{
                  "x":606,
                  "y":131},
                "size":{
                  "width":110,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"a713667aac8e4b7eb0a5e2c8f65d0afa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1}}},
            "location":{
              "x":742,
              "y":131},
            "size":{
              "width":110,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14870c646e114398a684899c8112e1dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF84C225,
                      "opacity":1}}},
                "location":{
                  "x":742,
                  "y":131},
                "size":{
                  "width":110,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"bb5320b160d54f4ca56750398f517230",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1}}},
            "location":{
              "x":870,
              "y":131},
            "size":{
              "width":110,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d690693e6ee0496897cc94a38582aec7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF84C225,
                      "opacity":1}}},
                "location":{
                  "x":870,
                  "y":131},
                "size":{
                  "width":110,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"7e145a172e4c4927b33586d248a9f383",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":390,
              "y":153},
            "size":{
              "width":70,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbf6bedb7f1b4d37a9d855c61b89e1e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":390,
                  "y":153},
                "size":{
                  "width":70,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 城市",
                      "objectsToFades":[{
                          "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-已登录/u81.png"}},
{
          "id":"3f9c12444f154d8c9c83dbd77ca64275",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":608,
              "y":165},
            "size":{
              "width":108,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF84C225}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/悦享家分期/u32_line.png"}},
{
          "id":"3e5cd5c5beef44188829a65847bb3ee2",
          "label":"城市",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":390,
              "y":173},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"df1c89c7f64c43da8d4733fa029669e0",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e46b60fa1c0f45fd916eea94ba76da46",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":500,
                      "height":130},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fafab9e13923498793570c3dc5a73b7b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":500,
                          "height":130},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页-已登录/u45.png"}},
{
                  "id":"b925274bf689412fb322a0a6c2e99bce",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":19,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ff97e7590d224d2f970e1c78ec3390c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":19,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f026eef2664a42f59294c73092726c57",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":78,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fb004348071940c0899c14308d3db04c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":78,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5f8e819c2f7641b4aa0952cd7846d764",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":142,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45fcc2fef22940fb8da1729d408c3dd9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":142,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6be0be9159e0483d8d17168942d77af0",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":203,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f16c8822b66c40e792f2fc3b783c237c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":203,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cbf33194418f471d8b855eba3bba7465",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":262,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"00c6a9bb9c9841209d994c0369940ab8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":262,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"259b02d807d44d9d903569b1eece5969",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":323,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"860c06b81cc94e19b3009e6c3ec592d2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":323,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cddc4c7d545e4b1d9631e4292f5dd557",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":384,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f645386edc2e4657a0451710e83117c2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":384,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fc10e231f66547968904c8f9f7cb16fb",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":445,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f5111dd3ab0d4daa8dd3c70504603e2f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":445,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"70268d10a4c343a7a24d11c07197d5c4",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":19,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b1b90bad2854d85aa5f41ba0dc76009",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":19,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"83b7039a7ec74ae9bf932aa5929622c2",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":78,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8730325fb4b74d75955d68131055a87a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":78,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a955088289f146478d0c32fcaf47ac01",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":142,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fdfbd7b27568416dba17af3ef0f986f3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":142,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"55e10be1213944ad8809a37c5f32386e",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":203,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8900e49d660b454289326f18ec1d19a6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":203,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"475d4f7188f044d6b9545ae7729121aa",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":262,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5af70c2716974bf5b64c9a83a13a33f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":262,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"817907bb0fa74378b51852e4b03bd611",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":323,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0544a60a4e714688bd262aed00ed0feb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":323,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f3f0a43ce005461494f1e519503d806f",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":384,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cee123e0026f48c0a19cc7d32dcf32dc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":384,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"abea45cfa1b04ecfb71a1101af0ee627",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":445,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"10f8ccc8ec0a4f21919aace9f883fd4d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":445,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"65b7aba640ee472d84bc82fbff63faf6",
                  "label":"",
                  "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":19,
                      "y":94},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f834fc4f64c44aadbdf32d8e28cd127b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e5cd5c5beef44188829a65847bb3ee2",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":19,
                          "y":94},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["3e5cd5c5beef44188829a65847bb3ee2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "42def18c994d4be3a75a8cadc7a40246":{
      "scriptId":"u0"},
    "e0de1e30aef546a98a10c3332f5a6937":{
      "scriptId":"u1"},
    "4b7110b688ab4d21836f96139f268f6d":{
      "scriptId":"u2"},
    "7534e8166b194cc1a3dfb95c3d2f188a":{
      "scriptId":"u3"},
    "3617bd249e084652a4e8569912807044":{
      "scriptId":"u4"},
    "58ae8727bc45405794c96b4e82d512af":{
      "scriptId":"u5"},
    "207f5a88a1a344189daf7d16763fb131":{
      "scriptId":"u6"},
    "694cb6b9a38f4c52887919a126c4e3b2":{
      "scriptId":"u7"},
    "acff8414662a4ce88303fbffe4034223":{
      "scriptId":"u8"},
    "8af777c5f46d4e31b24e80d032904698":{
      "scriptId":"u9"},
    "c94a34668cac42b98489d04e7541f423":{
      "scriptId":"u10"},
    "e4a1e76adb3246dc8d817e22bdabb6a6":{
      "scriptId":"u11"},
    "90e3b0550e6442c88329eea1decc776d":{
      "scriptId":"u12"},
    "d00773c8ec0f47d483bffe890ff7ba49":{
      "scriptId":"u13"},
    "a66a2c477b0a4373984b6a1dc0d7ad15":{
      "scriptId":"u14"},
    "7a1f32e16e3f44e480afc9de59a016f7":{
      "scriptId":"u15"},
    "eabbcc4f3d1c4acbaab2ee78a830dc25":{
      "scriptId":"u16"},
    "c2e3297269864d8c81f4eb18770e8868":{
      "scriptId":"u17"},
    "06e1588d02df42589efb997ef2d15ef7":{
      "scriptId":"u18"},
    "ae740bd798f64f7ab57a21096bd3337f":{
      "scriptId":"u19"},
    "036b6a7d4d1247c3a26c6765bff3dfef":{
      "scriptId":"u20"},
    "073252bd3e71488499489cba0adf6311":{
      "scriptId":"u21"},
    "d42ec715ca8d4d7b973e4bc9566e8959":{
      "scriptId":"u22"},
    "214021b5d02b47879e695607dc29afbd":{
      "scriptId":"u23"},
    "872cd8acb447451ab1970cceab5887e8":{
      "scriptId":"u24"},
    "6b1fa8c3a95a4b86ad78670f2962584d":{
      "scriptId":"u25"},
    "a713667aac8e4b7eb0a5e2c8f65d0afa":{
      "scriptId":"u26"},
    "14870c646e114398a684899c8112e1dc":{
      "scriptId":"u27"},
    "bb5320b160d54f4ca56750398f517230":{
      "scriptId":"u28"},
    "d690693e6ee0496897cc94a38582aec7":{
      "scriptId":"u29"},
    "7e145a172e4c4927b33586d248a9f383":{
      "scriptId":"u30"},
    "cbf6bedb7f1b4d37a9d855c61b89e1e1":{
      "scriptId":"u31"},
    "3f9c12444f154d8c9c83dbd77ca64275":{
      "scriptId":"u32"},
    "3e5cd5c5beef44188829a65847bb3ee2":{
      "scriptId":"u33"},
    "e46b60fa1c0f45fd916eea94ba76da46":{
      "scriptId":"u34"},
    "fafab9e13923498793570c3dc5a73b7b":{
      "scriptId":"u35"},
    "b925274bf689412fb322a0a6c2e99bce":{
      "scriptId":"u36"},
    "ff97e7590d224d2f970e1c78ec3390c0":{
      "scriptId":"u37"},
    "f026eef2664a42f59294c73092726c57":{
      "scriptId":"u38"},
    "fb004348071940c0899c14308d3db04c":{
      "scriptId":"u39"},
    "5f8e819c2f7641b4aa0952cd7846d764":{
      "scriptId":"u40"},
    "45fcc2fef22940fb8da1729d408c3dd9":{
      "scriptId":"u41"},
    "6be0be9159e0483d8d17168942d77af0":{
      "scriptId":"u42"},
    "f16c8822b66c40e792f2fc3b783c237c":{
      "scriptId":"u43"},
    "cbf33194418f471d8b855eba3bba7465":{
      "scriptId":"u44"},
    "00c6a9bb9c9841209d994c0369940ab8":{
      "scriptId":"u45"},
    "259b02d807d44d9d903569b1eece5969":{
      "scriptId":"u46"},
    "860c06b81cc94e19b3009e6c3ec592d2":{
      "scriptId":"u47"},
    "cddc4c7d545e4b1d9631e4292f5dd557":{
      "scriptId":"u48"},
    "f645386edc2e4657a0451710e83117c2":{
      "scriptId":"u49"},
    "fc10e231f66547968904c8f9f7cb16fb":{
      "scriptId":"u50"},
    "f5111dd3ab0d4daa8dd3c70504603e2f":{
      "scriptId":"u51"},
    "70268d10a4c343a7a24d11c07197d5c4":{
      "scriptId":"u52"},
    "1b1b90bad2854d85aa5f41ba0dc76009":{
      "scriptId":"u53"},
    "83b7039a7ec74ae9bf932aa5929622c2":{
      "scriptId":"u54"},
    "8730325fb4b74d75955d68131055a87a":{
      "scriptId":"u55"},
    "a955088289f146478d0c32fcaf47ac01":{
      "scriptId":"u56"},
    "fdfbd7b27568416dba17af3ef0f986f3":{
      "scriptId":"u57"},
    "55e10be1213944ad8809a37c5f32386e":{
      "scriptId":"u58"},
    "8900e49d660b454289326f18ec1d19a6":{
      "scriptId":"u59"},
    "475d4f7188f044d6b9545ae7729121aa":{
      "scriptId":"u60"},
    "5af70c2716974bf5b64c9a83a13a33f8":{
      "scriptId":"u61"},
    "817907bb0fa74378b51852e4b03bd611":{
      "scriptId":"u62"},
    "0544a60a4e714688bd262aed00ed0feb":{
      "scriptId":"u63"},
    "f3f0a43ce005461494f1e519503d806f":{
      "scriptId":"u64"},
    "cee123e0026f48c0a19cc7d32dcf32dc":{
      "scriptId":"u65"},
    "abea45cfa1b04ecfb71a1101af0ee627":{
      "scriptId":"u66"},
    "10f8ccc8ec0a4f21919aace9f883fd4d":{
      "scriptId":"u67"},
    "65b7aba640ee472d84bc82fbff63faf6":{
      "scriptId":"u68"},
    "f834fc4f64c44aadbdf32d8e28cd127b":{
      "scriptId":"u69"}}});