$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1440075580221.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b44f17ae65fd4cc5adacb31f04b945dd",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e812b7cf76af4b308736a66497750af3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":110},
            "size":{
              "width":1000,
              "height":494},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95cf6720a99c41638b2e0d3e6bf79912",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":110},
                "size":{
                  "width":1000,
                  "height":494},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"e47d17dc2f0f40c3a16a2871f4e527c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":140},
            "size":{
              "width":900,
              "height":400},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfafd7c82c7547b19d8df9e6c3a6e0a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":140},
                "size":{
                  "width":900,
                  "height":400},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u2.png"}},
{
          "id":"eaad084220fb4eaa85a9c46ff36bebe5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":534,
              "y":174},
            "size":{
              "width":386,
              "height":346},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"244e8b57496f4de6a6b0a7c566cf826f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":534,
                  "y":174},
                "size":{
                  "width":386,
                  "height":346},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"bdb1ddf2efe94649a63c5412372f9e43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":650,
              "y":406},
            "size":{
              "width":230,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab46d3edb91b4f1dad2d30001cb214c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":650,
                  "y":406},
                "size":{
                  "width":230,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u6.png"}},
{
          "id":"4487933997704dfb903023339a64e05b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":810,
              "y":373},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec4ed1e8258944c1b37aab38f21958bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":810,
                  "y":373},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2396a12ae0b4f54bf236cd857a7ecb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":217},
            "size":{
              "width":363,
              "height":246}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11f2ab6ddb0d4384b7ddbf515b72bcf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":97,
                  "y":217},
                "size":{
                  "width":363,
                  "height":246}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u10.png"}},
{
          "id":"f660f4d4d59d4a22b9c3ff50aa8caa8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"28px",
            "location":{
              "x":178,
              "y":290},
            "size":{
              "width":200,
              "height":100},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"047853513a444e51a9ebdbefd352f86b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"28px",
                "location":{
                  "x":178,
                  "y":290},
                "size":{
                  "width":200,
                  "height":100},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u16.png"}},
{
          "id":"919377ada7cc4073ade1a2004b65bff4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":600,
              "y":200},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b50fab57901d45e3881f323525e80dae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":200},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa0dee694b2f4351a4de79ae0585d1b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":580,
              "y":274},
            "size":{
              "width":59,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ba8794c66074554bf5ca2f47043e790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":580,
                  "y":274},
                "size":{
                  "width":59,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf009329835b421799b2395727ed27e9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":650,
              "y":263},
            "size":{
              "width":230,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae95cef9ecf9497c98fb101e65b99b08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":650,
                  "y":263},
                "size":{
                  "width":230,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u18.png"}},
{
          "id":"4e2ef9f3fbe74481b0bbff28000a3ee4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":650,
              "y":319},
            "size":{
              "width":230,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c19a45eef1514c19badf5ba2935b6f4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":650,
                  "y":319},
                "size":{
                  "width":230,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u18.png"}},
{
          "id":"b792869e7c1c401bb14ae40c480a232f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":207},
            "size":{
              "width":240,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u22_line.png"}},
{
          "id":"e930faa26b5b4f6f9ed48cdc11e4093e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":207},
            "size":{
              "width":54,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u23_line.png"}},
{
          "id":"fafdb1c7137345ae9ba5cced05c9df34",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "verticalAlignment":"bottom",
            "location":{
              "x":650,
              "y":373},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c42c68063fc4eca94eeb75c7850e64f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "verticalAlignment":"bottom",
                "location":{
                  "x":650,
                  "y":373},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}]},
{
          "id":"d3970b8e9d9e4fb6b520f78a6fc3295a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":40},
            "size":{
              "width":110,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"925d472d3f7c4b33a0ec1c01f76dc97d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":40},
                "size":{
                  "width":110,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u24.png"}},
{
          "id":"cf426c01f89c48e381e5d4db98c68d05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":62,
              "y":48},
            "size":{
              "width":88,
              "height":43},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"653988efe5c84cf0aa6383f8c28321fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":62,
                  "y":48},
                "size":{
                  "width":88,
                  "height":43},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u26.png"}},
{
          "id":"bbdde616f5364680a351077816f2f920",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":698,
              "y":456},
            "size":{
              "width":134,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbf6b117b51e4621a4dcbc1880e30268",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":698,
                  "y":456},
                "size":{
                  "width":134,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cebf9407c2ed4ab7b3088e4dd17933f5",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1080,
              "y":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1D82DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d23b8e9b2a0b4ecdbac52cf0d536d8c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1080,
                  "y":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1D82DE}},
              "adaptiveStyles":{
}}]},
{
          "id":"3f406b7954d847b8a0f7db89cfbe770c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1088,
              "y":18},
            "size":{
              "width":82,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"720967d83daa4466bfcb18c0eb682175",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1088,
                  "y":18},
                "size":{
                  "width":82,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf305f9f180b4066bcf021f4a5612b57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":580,
              "y":234},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e9c369edfb54e55bae364e80e10fab2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":580,
                  "y":234},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u50.png"}},
{
          "id":"4fee1f7301da4394a23b959d60076a1e",
          "label":"提交错误提示",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":602,
              "y":234},
            "size":{
              "width":298,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f7ce7c9a75547c7a22b2b7912f19b8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":602,
                  "y":234},
                "size":{
                  "width":298,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"707bdeac68104728935dae9872c4f67f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecfb9c8e1f8b4401ad415661f0a5f563",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":240}},
              "adaptiveStyles":{
}}]},
{
          "id":"76c65444f3ff4f419fb1f1cb4a258de6",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":287}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a17c7b7d8c33483fbd2d998b1b20d96c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":287}},
              "adaptiveStyles":{
}}]},
{
          "id":"cd1a4da937f6499cbd6496e9c30b3b6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1155,
              "y":282},
            "size":{
              "width":220,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c73b479f0d9042c89397354877f2c3dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1155,
                  "y":282},
                "size":{
                  "width":220,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4dc65365f1c7479bb72d0969e9688289",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":883,
              "y":385}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2945cf0995c439192c8b225bf6b5017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":883,
                  "y":385}},
              "adaptiveStyles":{
}}]},
{
          "id":"1f3f5f7e45f84dc59041a7c06ab2d8c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1055,
              "y":375},
            "size":{
              "width":190,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2275504ead0e4ed5a2b7102cbcfabf2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1055,
                  "y":375},
                "size":{
                  "width":190,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10865eedf7314d0c977c175a1d37bcf1",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":833,
              "y":469}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a0f5fa017654170a1b7d6be26667e55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":833,
                  "y":469}},
              "adaptiveStyles":{
}}]},
{
          "id":"58d8a9e30a4a4b97b85380e944a726bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1050,
              "y":456},
            "size":{
              "width":190,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eea0360f0c1146eca14ff6331f3a67b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1050,
                  "y":456},
                "size":{
                  "width":190,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6daec3eb3c5e4f17b1a605af597bf676",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":1516,
              "y":234},
            "size":{
              "width":213,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc6628cae7e54b14a31ebe7f9706d31f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":1516,
                  "y":234},
                "size":{
                  "width":213,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cc1fa40382540dcbff27e7c29a2073a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":1491,
              "y":234},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c3b38f29eea4625970f19f747c1f554",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":1491,
                  "y":234},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u50.png"}},
{
          "id":"ba15a7a658cd49a8b635ce36bb800a48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":1516,
              "y":270},
            "size":{
              "width":213,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4f03587258c495e8622a4c1f5ec9969",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":1516,
                  "y":270},
                "size":{
                  "width":213,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e17efd184774dd3ba05389c9eaff253",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":1491,
              "y":270},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f876d1f8f8a4c35ac659273ce3f0f70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":1491,
                  "y":270},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u50.png"}},
{
          "id":"d15345d1b6b34c1792cc1fd3259a4320",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":1516,
              "y":302},
            "size":{
              "width":213,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2294ab159a024a7685a82106fac9f84d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":1516,
                  "y":302},
                "size":{
                  "width":213,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4da83282bc054b049f3333ffc2517c94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":1491,
              "y":302},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bffd7f6c3f0245ccb63c16cf6e1ae8f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":1491,
                  "y":302},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u50.png"}},
{
          "id":"a88a713087834beab26ea6b8a36243af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":1516,
              "y":340},
            "size":{
              "width":284,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d7ec58700764e9a893808cf91b4e890",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":1516,
                  "y":340},
                "size":{
                  "width":284,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffcb774cebf74ee7ae8786a82bf5c5bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":1491,
              "y":340},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e6e74d297674edd81c7982824969372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":1491,
                  "y":340},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u50.png"}},
{
          "id":"8e84f25f624442ab81c58028a603dd23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":1516,
              "y":376},
            "size":{
              "width":284,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26549513f1474c54948bbeac74bac792",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":1516,
                  "y":376},
                "size":{
                  "width":284,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b03a18e74ce44cd49ad3d6d49a2ca1f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":1491,
              "y":376},
            "size":{
              "width":15,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e12aaf3cccef415c846370deeaf20e99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":1491,
                  "y":376},
                "size":{
                  "width":15,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u50.png"}},
{
          "id":"9950b5913f034d168991a6463061c6dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":604},
            "size":{
              "width":665,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51f6b20bd85845eb956a43bf1395f67c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":604},
                "size":{
                  "width":665,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u82.png"}},
{
          "id":"ec0c2e1e408b4eb8b8ab288f89ceba29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":429,
              "y":614},
            "size":{
              "width":60,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b6f3d9fda034527a14e61cf9476f316",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":429,
                  "y":614},
                "size":{
                  "width":60,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册成功/u28.png"}},
{
          "id":"12aaf61a9cce40a0bf4556961bc0ed04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":215,
              "y":644},
            "size":{
              "width":580,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fb42f0f039f423ab76a5ec007be1e80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":215,
                  "y":644},
                "size":{
                  "width":580,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u96.png"}},
{
          "id":"7ebd377353c94b8faa13098bf68354a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":0,
              "y":604},
            "size":{
              "width":190,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34a15802a1dd4632aba65bf7136d625a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":0,
                  "y":604},
                "size":{
                  "width":190,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u84.png"}},
{
          "id":"0698c65d7c6a4897a9d1a141c536cf2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":810,
              "y":604},
            "size":{
              "width":190,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94012ff350a7411fbda60cf770a0f014",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":810,
                  "y":604},
                "size":{
                  "width":190,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u84.png"}},
{
          "id":"bb4f039a443147ecbc9aefedda9de977",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":0,
              "y":674},
            "size":{
              "width":1000,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d92b529d83ec47e190ec492b76e776ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":0,
                  "y":674},
                "size":{
                  "width":1000,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u88.png"}},
{
          "id":"bf4eaabc77914f13b6b44c0e3c7ba050",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":190,
              "y":613},
            "size":{
              "width":630,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43a46b35e0284ea0af3d46caa32ce54e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":190,
                  "y":613},
                "size":{
                  "width":630,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u98.png"}},
{
          "id":"af29c43cb6eb4e60ab7a27f7a62d7aee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":270,
              "y":618},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b06e3f3d0ab4a679b0c5e1faf7bdc71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":270,
                  "y":618},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecb3add011464192aaa83ecb1b79bbe2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":618},
            "size":{
              "width":10,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册/u102_line.png"}},
{
          "id":"042e5cc945f34cd4b8f32dd9dce1c915",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":362,
              "y":618},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"874645c11f614a2583ae46d945c67cd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":362,
                  "y":618},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0ea7b0c5e734eaeae988836ecfaa1a8",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":443,
              "y":618},
            "size":{
              "width":10,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册/u102_line.png"}},
{
          "id":"668b846cb7544f1faffac6388fb7d1eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":453,
              "y":618},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feb31c62a25c4cde9120454d1d1a2601",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":453,
                  "y":618},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c13050f52d6d470ea5e1069af1025c23",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":618},
            "size":{
              "width":10,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册/u102_line.png"}},
{
          "id":"5004ef4ada6546e69c50476107fc9d9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":543,
              "y":618},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4948dd2e242c45a2a6afc87d4ab4017b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":543,
                  "y":618},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57030fdf2bd24dd498e2796b89a310c5",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":622,
              "y":618},
            "size":{
              "width":10,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册/u102_line.png"}},
{
          "id":"eb71b4e14b044856be0df2ee0e886f8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":632,
              "y":618},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"302c73c4ed89410eaf62e8a7d177cf00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":632,
                  "y":618},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62475ba3173c489ba2b1623cee810d34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":838,
              "y":60},
            "size":{
              "width":72,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c83c99c65469489fa2416e2c92b7ce74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":838,
                  "y":60},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"c065d43ac0d4447a881ae0a871080a73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":747,
              "y":60},
            "size":{
              "width":73,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40ac037cc0a0484d8a8aa9085cec4770",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":747,
                  "y":60},
                "size":{
                  "width":73,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"93b548805ecc411280301481bb25fff7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":693,
              "y":60},
            "size":{
              "width":54,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad5c0b37d825482c97426ae4554f2917",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":693,
                  "y":60},
                "size":{
                  "width":54,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"f883f5ca28db40ce9f9eb9d8134f0ed9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":928,
              "y":60},
            "size":{
              "width":72,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eb599df0cfc41f0b8d2d35cbd5bc2a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":928,
                  "y":60},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e812b7cf76af4b308736a66497750af3":{
      "scriptId":"u0"},
    "95cf6720a99c41638b2e0d3e6bf79912":{
      "scriptId":"u1"},
    "e47d17dc2f0f40c3a16a2871f4e527c8":{
      "scriptId":"u2"},
    "dfafd7c82c7547b19d8df9e6c3a6e0a7":{
      "scriptId":"u3"},
    "eaad084220fb4eaa85a9c46ff36bebe5":{
      "scriptId":"u4"},
    "244e8b57496f4de6a6b0a7c566cf826f":{
      "scriptId":"u5"},
    "bdb1ddf2efe94649a63c5412372f9e43":{
      "scriptId":"u6"},
    "ab46d3edb91b4f1dad2d30001cb214c4":{
      "scriptId":"u7"},
    "4487933997704dfb903023339a64e05b":{
      "scriptId":"u8"},
    "ec4ed1e8258944c1b37aab38f21958bb":{
      "scriptId":"u9"},
    "e2396a12ae0b4f54bf236cd857a7ecb5":{
      "scriptId":"u10"},
    "11f2ab6ddb0d4384b7ddbf515b72bcf2":{
      "scriptId":"u11"},
    "f660f4d4d59d4a22b9c3ff50aa8caa8e":{
      "scriptId":"u12"},
    "047853513a444e51a9ebdbefd352f86b":{
      "scriptId":"u13"},
    "919377ada7cc4073ade1a2004b65bff4":{
      "scriptId":"u14"},
    "b50fab57901d45e3881f323525e80dae":{
      "scriptId":"u15"},
    "fa0dee694b2f4351a4de79ae0585d1b1":{
      "scriptId":"u16"},
    "3ba8794c66074554bf5ca2f47043e790":{
      "scriptId":"u17"},
    "bf009329835b421799b2395727ed27e9":{
      "scriptId":"u18"},
    "ae95cef9ecf9497c98fb101e65b99b08":{
      "scriptId":"u19"},
    "4e2ef9f3fbe74481b0bbff28000a3ee4":{
      "scriptId":"u20"},
    "c19a45eef1514c19badf5ba2935b6f4e":{
      "scriptId":"u21"},
    "b792869e7c1c401bb14ae40c480a232f":{
      "scriptId":"u22"},
    "e930faa26b5b4f6f9ed48cdc11e4093e":{
      "scriptId":"u23"},
    "fafdb1c7137345ae9ba5cced05c9df34":{
      "scriptId":"u24"},
    "2c42c68063fc4eca94eeb75c7850e64f":{
      "scriptId":"u25"},
    "d3970b8e9d9e4fb6b520f78a6fc3295a":{
      "scriptId":"u26"},
    "925d472d3f7c4b33a0ec1c01f76dc97d":{
      "scriptId":"u27"},
    "cf426c01f89c48e381e5d4db98c68d05":{
      "scriptId":"u28"},
    "653988efe5c84cf0aa6383f8c28321fb":{
      "scriptId":"u29"},
    "bbdde616f5364680a351077816f2f920":{
      "scriptId":"u30"},
    "fbf6b117b51e4621a4dcbc1880e30268":{
      "scriptId":"u31"},
    "cebf9407c2ed4ab7b3088e4dd17933f5":{
      "scriptId":"u32"},
    "d23b8e9b2a0b4ecdbac52cf0d536d8c5":{
      "scriptId":"u33"},
    "3f406b7954d847b8a0f7db89cfbe770c":{
      "scriptId":"u34"},
    "720967d83daa4466bfcb18c0eb682175":{
      "scriptId":"u35"},
    "bf305f9f180b4066bcf021f4a5612b57":{
      "scriptId":"u36"},
    "8e9c369edfb54e55bae364e80e10fab2":{
      "scriptId":"u37"},
    "4fee1f7301da4394a23b959d60076a1e":{
      "scriptId":"u38"},
    "9f7ce7c9a75547c7a22b2b7912f19b8e":{
      "scriptId":"u39"},
    "707bdeac68104728935dae9872c4f67f":{
      "scriptId":"u40"},
    "ecfb9c8e1f8b4401ad415661f0a5f563":{
      "scriptId":"u41"},
    "76c65444f3ff4f419fb1f1cb4a258de6":{
      "scriptId":"u42"},
    "a17c7b7d8c33483fbd2d998b1b20d96c":{
      "scriptId":"u43"},
    "cd1a4da937f6499cbd6496e9c30b3b6a":{
      "scriptId":"u44"},
    "c73b479f0d9042c89397354877f2c3dd":{
      "scriptId":"u45"},
    "4dc65365f1c7479bb72d0969e9688289":{
      "scriptId":"u46"},
    "f2945cf0995c439192c8b225bf6b5017":{
      "scriptId":"u47"},
    "1f3f5f7e45f84dc59041a7c06ab2d8c9":{
      "scriptId":"u48"},
    "2275504ead0e4ed5a2b7102cbcfabf2c":{
      "scriptId":"u49"},
    "10865eedf7314d0c977c175a1d37bcf1":{
      "scriptId":"u50"},
    "9a0f5fa017654170a1b7d6be26667e55":{
      "scriptId":"u51"},
    "58d8a9e30a4a4b97b85380e944a726bd":{
      "scriptId":"u52"},
    "eea0360f0c1146eca14ff6331f3a67b4":{
      "scriptId":"u53"},
    "6daec3eb3c5e4f17b1a605af597bf676":{
      "scriptId":"u54"},
    "fc6628cae7e54b14a31ebe7f9706d31f":{
      "scriptId":"u55"},
    "2cc1fa40382540dcbff27e7c29a2073a":{
      "scriptId":"u56"},
    "1c3b38f29eea4625970f19f747c1f554":{
      "scriptId":"u57"},
    "ba15a7a658cd49a8b635ce36bb800a48":{
      "scriptId":"u58"},
    "f4f03587258c495e8622a4c1f5ec9969":{
      "scriptId":"u59"},
    "1e17efd184774dd3ba05389c9eaff253":{
      "scriptId":"u60"},
    "3f876d1f8f8a4c35ac659273ce3f0f70":{
      "scriptId":"u61"},
    "d15345d1b6b34c1792cc1fd3259a4320":{
      "scriptId":"u62"},
    "2294ab159a024a7685a82106fac9f84d":{
      "scriptId":"u63"},
    "4da83282bc054b049f3333ffc2517c94":{
      "scriptId":"u64"},
    "bffd7f6c3f0245ccb63c16cf6e1ae8f9":{
      "scriptId":"u65"},
    "a88a713087834beab26ea6b8a36243af":{
      "scriptId":"u66"},
    "4d7ec58700764e9a893808cf91b4e890":{
      "scriptId":"u67"},
    "ffcb774cebf74ee7ae8786a82bf5c5bf":{
      "scriptId":"u68"},
    "4e6e74d297674edd81c7982824969372":{
      "scriptId":"u69"},
    "8e84f25f624442ab81c58028a603dd23":{
      "scriptId":"u70"},
    "26549513f1474c54948bbeac74bac792":{
      "scriptId":"u71"},
    "b03a18e74ce44cd49ad3d6d49a2ca1f8":{
      "scriptId":"u72"},
    "e12aaf3cccef415c846370deeaf20e99":{
      "scriptId":"u73"},
    "9950b5913f034d168991a6463061c6dd":{
      "scriptId":"u74"},
    "51f6b20bd85845eb956a43bf1395f67c":{
      "scriptId":"u75"},
    "ec0c2e1e408b4eb8b8ab288f89ceba29":{
      "scriptId":"u76"},
    "9b6f3d9fda034527a14e61cf9476f316":{
      "scriptId":"u77"},
    "12aaf61a9cce40a0bf4556961bc0ed04":{
      "scriptId":"u78"},
    "3fb42f0f039f423ab76a5ec007be1e80":{
      "scriptId":"u79"},
    "7ebd377353c94b8faa13098bf68354a3":{
      "scriptId":"u80"},
    "34a15802a1dd4632aba65bf7136d625a":{
      "scriptId":"u81"},
    "0698c65d7c6a4897a9d1a141c536cf2a":{
      "scriptId":"u82"},
    "94012ff350a7411fbda60cf770a0f014":{
      "scriptId":"u83"},
    "bb4f039a443147ecbc9aefedda9de977":{
      "scriptId":"u84"},
    "d92b529d83ec47e190ec492b76e776ce":{
      "scriptId":"u85"},
    "bf4eaabc77914f13b6b44c0e3c7ba050":{
      "scriptId":"u86"},
    "43a46b35e0284ea0af3d46caa32ce54e":{
      "scriptId":"u87"},
    "af29c43cb6eb4e60ab7a27f7a62d7aee":{
      "scriptId":"u88"},
    "5b06e3f3d0ab4a679b0c5e1faf7bdc71":{
      "scriptId":"u89"},
    "ecb3add011464192aaa83ecb1b79bbe2":{
      "scriptId":"u90"},
    "042e5cc945f34cd4b8f32dd9dce1c915":{
      "scriptId":"u91"},
    "874645c11f614a2583ae46d945c67cd9":{
      "scriptId":"u92"},
    "b0ea7b0c5e734eaeae988836ecfaa1a8":{
      "scriptId":"u93"},
    "668b846cb7544f1faffac6388fb7d1eb":{
      "scriptId":"u94"},
    "feb31c62a25c4cde9120454d1d1a2601":{
      "scriptId":"u95"},
    "c13050f52d6d470ea5e1069af1025c23":{
      "scriptId":"u96"},
    "5004ef4ada6546e69c50476107fc9d9a":{
      "scriptId":"u97"},
    "4948dd2e242c45a2a6afc87d4ab4017b":{
      "scriptId":"u98"},
    "57030fdf2bd24dd498e2796b89a310c5":{
      "scriptId":"u99"},
    "eb71b4e14b044856be0df2ee0e886f8f":{
      "scriptId":"u100"},
    "302c73c4ed89410eaf62e8a7d177cf00":{
      "scriptId":"u101"},
    "62475ba3173c489ba2b1623cee810d34":{
      "scriptId":"u102"},
    "c83c99c65469489fa2416e2c92b7ce74":{
      "scriptId":"u103"},
    "c065d43ac0d4447a881ae0a871080a73":{
      "scriptId":"u104"},
    "40ac037cc0a0484d8a8aa9085cec4770":{
      "scriptId":"u105"},
    "93b548805ecc411280301481bb25fff7":{
      "scriptId":"u106"},
    "ad5c0b37d825482c97426ae4554f2917":{
      "scriptId":"u107"},
    "f883f5ca28db40ce9f9eb9d8134f0ed9":{
      "scriptId":"u108"},
    "2eb599df0cfc41f0b8d2d35cbd5bc2a1":{
      "scriptId":"u109"}}});