$axure.loadCurrentPage({
  "url":"编辑和添加-制作中.html",
  "generationDate":new Date(1441157430554.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"036fb8d26071489ca1e79288d390b0f6",
    "type":"Axure:Page",
    "name":"编辑和添加-制作中",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4e649d596dd0419892243a426f49dfff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":1180,
              "height":740}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b782564cb634ff6a9f5fec16a23e622",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":1180,
                  "height":740}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cms___sns__-cms__-__/u0.png"}},
{
          "id":"f21fb12f8a0642e482ce6633ab26f86c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":140},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d90e69ecd94404eb661270a6882b485",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":140},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"4cf32bd5f3884ea08ce1200d3ed0cc04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":190},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f95a42347da941aeb0ea043dbed01d94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":190},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"3e3c55a41b4647eeb6670fc68a7349db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":240},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18630a5156d44ef797d2e24c1ba21751",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":240},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"cf3f07da9e034c76984b93df019bb974",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":290},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b8e73fab8fb4da2917264d840493f87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":290},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"7abb0e334af34d979585adcdaf5bd3fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":340},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"758f34d6d7214c159276bb444ebfd91a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":340},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"60cd7304a024406db1eaddc785a4eb1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":390},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ed5a37f551f423085a4faeded26ffea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":390},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"53d170fb3d9d420c9f1d615d334c3b17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":55,
              "y":440},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9988127cbe1c4285a1134b70d36be4a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":55,
                  "y":440},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u2.png"}},
{
          "id":"a36b7ad5bf234d4ab331e52f5d99c5cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":570},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7f771722a6b42ba89bae2aeb1dcad81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":570},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"85cc4b0ced4448faac981065d59d6be4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":76},
            "size":{
              "width":1180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/预约管理-未下载-完成/u18_line.png"}},
{
          "id":"3b43817a9a724d70805bd3028562ded6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":26},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffdc01ae4e0e4c0baf3ee8d4f9a5ec02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":26},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5b925bd392649a984cafbdf76a2a2b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1137,
              "y":26},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8678072d3a942f0b081ff9d0b3f1502",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1137,
                  "y":26},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7f882fa134a4dd9b9896b2142366009",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":18},
            "size":{
              "width":135,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04cf2613f2bf4f748d6d52c727d24f84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":18},
                "size":{
                  "width":135,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u23.png"}},
{
          "id":"97b345e2b9a14b1b893fc32dfcb820bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":33},
            "size":{
              "width":270,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd83165f591b4260bd33b64336c48e91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":33},
                "size":{
                  "width":270,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2733a376f1704e38bd6b40f65edaf288",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":52},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"548070b675524cbeb51ae184e830ca54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":52},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69294ec0007844a4ab6c77863f4415b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1147,
              "y":52},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ced36b17c8748bf97bac7866191679a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1147,
                  "y":52},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"469102733a5d424b90598587bbacc7d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":140},
            "size":{
              "width":950,
              "height":590}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c899a86480e04476aa0c1bf210318707",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":140},
                "size":{
                  "width":950,
                  "height":590}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑和添加-制作中/u31.png"}},
{
          "id":"045a07982fa74121af3ab406164119d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":104},
            "size":{
              "width":375,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3de5e996310b42638fd304a433846e06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":104},
                "size":{
                  "width":375,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aac04f4134eb4f3583befbdd9bd3ed48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":55,
              "y":490},
            "size":{
              "width":165,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8243bc298bda4f0490c8a5da19dd87c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":55,
                  "y":490},
                "size":{
                  "width":165,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cms___sns__-cms__-__/u74.png"}},
{
          "id":"5fc67fe34cbe4836b78d4377732ab692",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":530},
            "size":{
              "width":165,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1594f62d73994855bd1ed45a4bf44f4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":530},
                "size":{
                  "width":165,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cms___sns__-cms__-__/u76.png"}},
{
          "id":"0389ed5bc39945b08e269a37c5d21d9b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":152},
            "size":{
              "width":202,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3ffbfac892e44e24839b54fedc40aeba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":158},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60da571592e1499786e13f5774917345",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":158},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"019c3c6fa07e4511aa47f8aa371acb48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":196},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f6c623c6519455ba7fc153b3b65098c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":196},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd8cf88ca0024c74b47932af7741bf0b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":225},
            "size":{
              "width":202,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c074a55ce84c48cd847958eae011be36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":231},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc9139fcc0f8482a9751521b443ac56e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":231},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f412829d0f51415bbf0cf6a8fd307c5e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":190},
            "size":{
              "width":202,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "4e649d596dd0419892243a426f49dfff":{
      "scriptId":"u0"},
    "9b782564cb634ff6a9f5fec16a23e622":{
      "scriptId":"u1"},
    "f21fb12f8a0642e482ce6633ab26f86c":{
      "scriptId":"u2"},
    "9d90e69ecd94404eb661270a6882b485":{
      "scriptId":"u3"},
    "4cf32bd5f3884ea08ce1200d3ed0cc04":{
      "scriptId":"u4"},
    "f95a42347da941aeb0ea043dbed01d94":{
      "scriptId":"u5"},
    "3e3c55a41b4647eeb6670fc68a7349db":{
      "scriptId":"u6"},
    "18630a5156d44ef797d2e24c1ba21751":{
      "scriptId":"u7"},
    "cf3f07da9e034c76984b93df019bb974":{
      "scriptId":"u8"},
    "0b8e73fab8fb4da2917264d840493f87":{
      "scriptId":"u9"},
    "7abb0e334af34d979585adcdaf5bd3fd":{
      "scriptId":"u10"},
    "758f34d6d7214c159276bb444ebfd91a":{
      "scriptId":"u11"},
    "60cd7304a024406db1eaddc785a4eb1d":{
      "scriptId":"u12"},
    "2ed5a37f551f423085a4faeded26ffea":{
      "scriptId":"u13"},
    "53d170fb3d9d420c9f1d615d334c3b17":{
      "scriptId":"u14"},
    "9988127cbe1c4285a1134b70d36be4a9":{
      "scriptId":"u15"},
    "a36b7ad5bf234d4ab331e52f5d99c5cc":{
      "scriptId":"u16"},
    "f7f771722a6b42ba89bae2aeb1dcad81":{
      "scriptId":"u17"},
    "85cc4b0ced4448faac981065d59d6be4":{
      "scriptId":"u18"},
    "3b43817a9a724d70805bd3028562ded6":{
      "scriptId":"u19"},
    "ffdc01ae4e0e4c0baf3ee8d4f9a5ec02":{
      "scriptId":"u20"},
    "b5b925bd392649a984cafbdf76a2a2b3":{
      "scriptId":"u21"},
    "a8678072d3a942f0b081ff9d0b3f1502":{
      "scriptId":"u22"},
    "e7f882fa134a4dd9b9896b2142366009":{
      "scriptId":"u23"},
    "04cf2613f2bf4f748d6d52c727d24f84":{
      "scriptId":"u24"},
    "97b345e2b9a14b1b893fc32dfcb820bb":{
      "scriptId":"u25"},
    "fd83165f591b4260bd33b64336c48e91":{
      "scriptId":"u26"},
    "2733a376f1704e38bd6b40f65edaf288":{
      "scriptId":"u27"},
    "548070b675524cbeb51ae184e830ca54":{
      "scriptId":"u28"},
    "69294ec0007844a4ab6c77863f4415b6":{
      "scriptId":"u29"},
    "2ced36b17c8748bf97bac7866191679a":{
      "scriptId":"u30"},
    "469102733a5d424b90598587bbacc7d4":{
      "scriptId":"u31"},
    "c899a86480e04476aa0c1bf210318707":{
      "scriptId":"u32"},
    "045a07982fa74121af3ab406164119d0":{
      "scriptId":"u33"},
    "3de5e996310b42638fd304a433846e06":{
      "scriptId":"u34"},
    "aac04f4134eb4f3583befbdd9bd3ed48":{
      "scriptId":"u35"},
    "8243bc298bda4f0490c8a5da19dd87c4":{
      "scriptId":"u36"},
    "5fc67fe34cbe4836b78d4377732ab692":{
      "scriptId":"u37"},
    "1594f62d73994855bd1ed45a4bf44f4a":{
      "scriptId":"u38"},
    "0389ed5bc39945b08e269a37c5d21d9b":{
      "scriptId":"u39"},
    "3ffbfac892e44e24839b54fedc40aeba":{
      "scriptId":"u40"},
    "60da571592e1499786e13f5774917345":{
      "scriptId":"u41"},
    "019c3c6fa07e4511aa47f8aa371acb48":{
      "scriptId":"u42"},
    "0f6c623c6519455ba7fc153b3b65098c":{
      "scriptId":"u43"},
    "dd8cf88ca0024c74b47932af7741bf0b":{
      "scriptId":"u44"},
    "c074a55ce84c48cd847958eae011be36":{
      "scriptId":"u45"},
    "dc9139fcc0f8482a9751521b443ac56e":{
      "scriptId":"u46"},
    "f412829d0f51415bbf0cf6a8fd307c5e":{
      "scriptId":"u47"}}});