$axure.loadCurrentPage({
  "url":"第三步-修改成功.html",
  "generationDate":new Date(1440075581104.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b120ddfe045d450880132b6020b04963",
    "type":"Axure:Page",
    "name":"第三步-修改成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"97acefef029d4b2fb9366ca1f5eb50ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":43},
            "size":{
              "width":110,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8b389c8ed524ceaa9a81b87df562e9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":43},
                "size":{
                  "width":110,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u24.png"}},
{
          "id":"6d8bc4d5f0cc4012acef0aec4b8547d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":315,
              "y":51},
            "size":{
              "width":88,
              "height":43},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03dd4fbe3534489e9f66bb0eab633f9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":315,
                  "y":51},
                "size":{
                  "width":88,
                  "height":43},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u26.png"}},
{
          "id":"1a4d53a3f315469d9919fe5914605c0a",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1373,
              "y":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1D82DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aef4bf4d287640229270a282172e88de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1373,
                  "y":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1D82DE}},
              "adaptiveStyles":{
}}]},
{
          "id":"1f5872d142ce48c3ac04a58e55c005f6",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1373,
              "y":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1D82DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"376ea750f7f54ec78748b01140a11136",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1373,
                  "y":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1D82DE}},
              "adaptiveStyles":{
}}]},
{
          "id":"66c331e111c24065b68787209ae7d0ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":155},
            "size":{
              "width":971,
              "height":286}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8e559cace4d46318e58827c2a97ec5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":155},
                "size":{
                  "width":971,
                  "height":286}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一步-验证手机/u8.png"}},
{
          "id":"f2d3dbcfea2e4e6cad2e4bcd4c2aac14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":266},
            "size":{
              "width":944,
              "height":175},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0b21fcd84c14caeb9c9527587024f1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":266},
                "size":{
                  "width":944,
                  "height":175},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一步-验证手机/u14.png"}},
{
          "id":"3c54d79ede0c43ecaffdd52a4eacee21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":320,
              "y":264},
            "size":{
              "width":332,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eecf2e2873734298a9732538872a0597",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":320,
                  "y":264},
                "size":{
                  "width":332,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6df5178dde3140099e01f15a396cf740",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":290},
            "size":{
              "width":932,
              "height":426},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70779c1b9e07471998790084b955777a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":290},
                "size":{
                  "width":932,
                  "height":426},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第二步-修改密码/u16.png"}},
{
          "id":"b7dfd1112aac4fb4a347e5e72e67185c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":572,
              "y":330},
            "size":{
              "width":547,
              "height":293}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30029c19ce9145ea932cf13044a54bec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":572,
                  "y":330},
                "size":{
                  "width":547,
                  "height":293}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一步-验证手机/u20.png"}},
{
          "id":"04013f0ae8c644d7959a12f36cfa47fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":808,
              "y":451},
            "size":{
              "width":124,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76e96308ef6346f599ba2bd6a3224423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":808,
                  "y":451},
                "size":{
                  "width":124,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一步-验证手机/u22.png"}},
{
          "id":"6769691b54a74a7eb996f80e0344f298",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":208},
            "size":{
              "width":949,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58ea16fe58d84ceeb5c98287430bbd6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":312,
                  "y":208},
                "size":{
                  "width":949,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第二步-修改密码/u22.png"}},
{
          "id":"b66461180e284f6090f71f515a4a2d91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF8900},
            "location":{
              "x":688,
              "y":218},
            "size":{
              "width":174,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF8900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"672e4aa654554e0dab98f86fd9556b70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF8900},
                "location":{
                  "x":688,
                  "y":218},
                "size":{
                  "width":174,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF8900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三步-修改成功/u22.png"}},
{
          "id":"dce7b4dea5d645149a3eb8eed730a405",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFDEDEDE},
            "location":{
              "x":364,
              "y":217},
            "size":{
              "width":174,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDEDEDE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"456ff8b2426948b0811f66527d0e8dec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDEDEDE},
                "location":{
                  "x":364,
                  "y":217},
                "size":{
                  "width":174,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDEDEDE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一步-验证手机/u12.png"}},
{
          "id":"b7acfc42f72743b2924831d40a69f9c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":313},
            "size":{
              "width":659,
              "height":336}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ac8c604586e4e92b5d5b7f17ad26b8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":313},
                "size":{
                  "width":659,
                  "height":336}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第二步-修改密码/u28.png"}},
{
          "id":"8f310d96592d48ac959a6080afad578e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":636,
              "y":339},
            "size":{
              "width":420,
              "height":57},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53d2c4fbe97c4cb7852d6c99cdb90099",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":636,
                  "y":339},
                "size":{
                  "width":420,
                  "height":57},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第二步-修改密码/u30.png"}},
{
          "id":"464df9f87d0543c0aecc4a56ca7ea5c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":732,
              "y":475},
            "size":{
              "width":120,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42510f03daef454797a40cba9561ce7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":732,
                  "y":475},
                "size":{
                  "width":120,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第二步-修改密码/u32.png"}},
{
          "id":"d548b391375748e2b5ad4d52b88e6dc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":932,
              "y":216},
            "size":{
              "width":322,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf8dca13048c4ed7821833b1302907f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":932,
                  "y":216},
                "size":{
                  "width":322,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三步-修改成功/u32.png"}},
{
          "id":"3ab35e6465c9433c93b1cad0b64880de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDEDEDE},
            "location":{
              "x":632,
              "y":216},
            "size":{
              "width":322,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78b30f36e6dd4d0da58229bc1010cac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDEDEDE},
                "location":{
                  "x":632,
                  "y":216},
                "size":{
                  "width":322,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三步-修改成功/u34.png"}},
{
          "id":"dca683225efd4c6c9cb3d52d7aea7584",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDEDEDE},
            "location":{
              "x":320,
              "y":216},
            "size":{
              "width":322,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6f6ae819bd848aa846f8ca192c93f70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDEDEDE},
                "location":{
                  "x":320,
                  "y":216},
                "size":{
                  "width":322,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三步-修改成功/u34.png"}},
{
          "id":"81317879bde3490c8a126b69225c1021",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":548,
              "y":426},
            "size":{
              "width":484,
              "height":230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"033d459226034b97abf0a812be34fae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":548,
                  "y":426},
                "size":{
                  "width":484,
                  "height":230},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三步-修改成功/u38.png"}},
{
          "id":"1035c4eb6128497287233bd227c35128",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文楷体 Bold', '华文楷体'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":310,
              "y":150},
            "size":{
              "width":159,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42f7ad6611bb48538f7f444c99b86f63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文楷体 Bold', '华文楷体'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":310,
                  "y":150},
                "size":{
                  "width":159,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一步-验证手机/u26.png"}},
{
          "id":"4b8360748b4f4aa0a5983078fa0b3c4a",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":317.5,
              "y":156},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"1145f7ffb1f64c7d8eb2c172603760c3",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8af5553677b1494d924c43159f0dac5d",
                  "label":"",
                  "parentDynamicPanel":"4b8360748b4f4aa0a5983078fa0b3c4a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'楷体 Bold', '楷体'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "horizontalAlignment":"left",
                    "location":{
                      "x":0,
                      "y":2},
                    "size":{
                      "width":170,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b0977ccf1cf541ecb0c5c2cbc7206dc8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4b8360748b4f4aa0a5983078fa0b3c4a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'楷体 Bold', '楷体'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "horizontalAlignment":"left",
                        "location":{
                          "x":0,
                          "y":2},
                        "size":{
                          "width":170,
                          "height":36},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/第三步-修改成功/u43.png"}},
{
                  "id":"4c00b1f86d42498d9b5ab0bf48b58a83",
                  "label":"",
                  "parentDynamicPanel":"4b8360748b4f4aa0a5983078fa0b3c4a",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":2,
                      "y":37},
                    "size":{
                      "width":158,
                      "height":10},
                    "borderWidth":"3",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF333333}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/第一步-验证手机/u32_line.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"f10573097fdc4691983b8c4d7efe2a6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":556,
              "y":335},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8f25e0266194096bf3ab6b4c6b58403",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":556,
                  "y":335},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册成功/u20.png"}},
{
          "id":"998a072444fa48a88e67344067bd9b93",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":468,
              "y":740},
            "size":{
              "width":665,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"106e459c9d584d808601ac07403a3753",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":468,
                  "y":740},
                "size":{
                  "width":665,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u82.png"}},
{
          "id":"b7b2f7bea7e1433caa6f805d051f5181",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":722,
              "y":750},
            "size":{
              "width":60,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e83e7969f414dbbb3cc10da2ec1c1e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":722,
                  "y":750},
                "size":{
                  "width":60,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册成功/u28.png"}},
{
          "id":"677471319c084f7a9c59106bd7545499",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":508,
              "y":780},
            "size":{
              "width":580,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"693aeec681ee45d3abb91c13b45956d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":508,
                  "y":780},
                "size":{
                  "width":580,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u96.png"}},
{
          "id":"3bb8f562acdd4ea5a89f6a3f1febe7ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":292,
              "y":740},
            "size":{
              "width":190,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f5db0df6f7b485e80a2dbe8c91f396b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":292,
                  "y":740},
                "size":{
                  "width":190,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u84.png"}},
{
          "id":"9ccb2ada95174b498d608325b310087e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":1102,
              "y":740},
            "size":{
              "width":190,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2bcc6a4c1964c02b74fc9482cf58355",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":1102,
                  "y":740},
                "size":{
                  "width":190,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u84.png"}},
{
          "id":"bf06c59a240f472f9a4bb2b7b95f4453",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":292,
              "y":810},
            "size":{
              "width":1000,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"337478b8fe2645809737dccec56f50eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":292,
                  "y":810},
                "size":{
                  "width":1000,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u88.png"}},
{
          "id":"f3d4e5dd002f4769954f9dd14d71e67a",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":471,
              "y":747},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"edd1680c36db46b9bbf47fbffb72318b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"adc3d629200c4c57a5fb8b18b676cfd1",
                  "label":"",
                  "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF0EEEF},
                    "location":{
                      "x":25,
                      "y":31},
                    "size":{
                      "width":580,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF0EEEF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45f1bcb61b50441fb980fd4b817ff680",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF0EEEF},
                        "location":{
                          "x":25,
                          "y":31},
                        "size":{
                          "width":580,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF0EEEF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/注册/u96.png"}},
{
                  "id":"987f174d3aae449993e61b4f607075b3",
                  "label":"",
                  "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF0EEEF},
                    "size":{
                      "width":630,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF0EEEF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"441c47a7bd2344fba9c3d74b15833ccc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF0EEEF},
                        "size":{
                          "width":630,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF0EEEF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/注册/u98.png"}},
{
                  "id":"6e2a9064d5fe41f0b997325b686a9904",
                  "label":"",
                  "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":80,
                      "y":5},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dc7fcd5d82694fbbbdbdaefb7294122f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":80,
                          "y":5},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3bce7f25a1544f178fcde032b25e8a5e",
                  "label":"",
                  "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                  "panelIndex":0,
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":5},
                    "size":{
                      "width":10,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/注册/u102_line.png"}},
{
                  "id":"355821a33339435a8dc4addb741fb733",
                  "label":"",
                  "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":172,
                      "y":5},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"996776b15a324c9b9d93e4fada76b17c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":172,
                          "y":5},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0c60a8612bd14523ad064545b830c48e",
                  "label":"",
                  "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                  "panelIndex":0,
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":253,
                      "y":5},
                    "size":{
                      "width":10,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/注册/u102_line.png"}},
{
                  "id":"bfdc662f3b0545729bfb6fd182af514b",
                  "label":"",
                  "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":263,
                      "y":5},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0e61e23f03204b60b38b09d4a736b0b7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":263,
                          "y":5},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d1bf2ebf4ecd450da9c021b4d6ff1b04",
                  "label":"",
                  "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                  "panelIndex":0,
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":342,
                      "y":5},
                    "size":{
                      "width":10,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/注册/u102_line.png"}},
{
                  "id":"a0dbde0e55cc44679d46003e6ee91253",
                  "label":"",
                  "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":353,
                      "y":5},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"353bf9364956499f8c2c1331364526c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":353,
                          "y":5},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"78c69d3dda634098bd4cd3e8c85d7f51",
                  "label":"",
                  "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                  "panelIndex":0,
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":432,
                      "y":5},
                    "size":{
                      "width":10,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/注册/u102_line.png"}},
{
                  "id":"8b649765ef28446ebf34f74488ba30f6",
                  "label":"",
                  "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":442,
                      "y":5},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"946a1f759ee74304add5955044203b42",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f3d4e5dd002f4769954f9dd14d71e67a",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":442,
                          "y":5},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"6f7789e2f2da4a4bb2a358e25eac5a96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":1068,
              "y":62},
            "size":{
              "width":72,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9accb3d893654dfba85cae88c9a76e4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":1068,
                  "y":62},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"0e31f972d41a4247a84f47c674713d7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":977,
              "y":62},
            "size":{
              "width":73,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b318ee6c8a84a1db06b1540b5eb3e87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":977,
                  "y":62},
                "size":{
                  "width":73,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"fa95d6c57aac41788b4431e272d7273a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":923,
              "y":62},
            "size":{
              "width":54,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc27a68a85174ea2bcbb160010624232",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":923,
                  "y":62},
                "size":{
                  "width":54,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"a9724fcad23c44f38765943d97557998",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":1158,
              "y":62},
            "size":{
              "width":72,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4813f72ac2a45308c40259e3f5419e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":1158,
                  "y":62},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "97acefef029d4b2fb9366ca1f5eb50ca":{
      "scriptId":"u0"},
    "e8b389c8ed524ceaa9a81b87df562e9d":{
      "scriptId":"u1"},
    "6d8bc4d5f0cc4012acef0aec4b8547d3":{
      "scriptId":"u2"},
    "03dd4fbe3534489e9f66bb0eab633f9f":{
      "scriptId":"u3"},
    "1a4d53a3f315469d9919fe5914605c0a":{
      "scriptId":"u4"},
    "aef4bf4d287640229270a282172e88de":{
      "scriptId":"u5"},
    "1f5872d142ce48c3ac04a58e55c005f6":{
      "scriptId":"u6"},
    "376ea750f7f54ec78748b01140a11136":{
      "scriptId":"u7"},
    "66c331e111c24065b68787209ae7d0ec":{
      "scriptId":"u8"},
    "b8e559cace4d46318e58827c2a97ec5a":{
      "scriptId":"u9"},
    "f2d3dbcfea2e4e6cad2e4bcd4c2aac14":{
      "scriptId":"u10"},
    "c0b21fcd84c14caeb9c9527587024f1a":{
      "scriptId":"u11"},
    "3c54d79ede0c43ecaffdd52a4eacee21":{
      "scriptId":"u12"},
    "eecf2e2873734298a9732538872a0597":{
      "scriptId":"u13"},
    "6df5178dde3140099e01f15a396cf740":{
      "scriptId":"u14"},
    "70779c1b9e07471998790084b955777a":{
      "scriptId":"u15"},
    "b7dfd1112aac4fb4a347e5e72e67185c":{
      "scriptId":"u16"},
    "30029c19ce9145ea932cf13044a54bec":{
      "scriptId":"u17"},
    "04013f0ae8c644d7959a12f36cfa47fd":{
      "scriptId":"u18"},
    "76e96308ef6346f599ba2bd6a3224423":{
      "scriptId":"u19"},
    "6769691b54a74a7eb996f80e0344f298":{
      "scriptId":"u20"},
    "58ea16fe58d84ceeb5c98287430bbd6c":{
      "scriptId":"u21"},
    "b66461180e284f6090f71f515a4a2d91":{
      "scriptId":"u22"},
    "672e4aa654554e0dab98f86fd9556b70":{
      "scriptId":"u23"},
    "dce7b4dea5d645149a3eb8eed730a405":{
      "scriptId":"u24"},
    "456ff8b2426948b0811f66527d0e8dec":{
      "scriptId":"u25"},
    "b7acfc42f72743b2924831d40a69f9c5":{
      "scriptId":"u26"},
    "2ac8c604586e4e92b5d5b7f17ad26b8a":{
      "scriptId":"u27"},
    "8f310d96592d48ac959a6080afad578e":{
      "scriptId":"u28"},
    "53d2c4fbe97c4cb7852d6c99cdb90099":{
      "scriptId":"u29"},
    "464df9f87d0543c0aecc4a56ca7ea5c0":{
      "scriptId":"u30"},
    "42510f03daef454797a40cba9561ce7a":{
      "scriptId":"u31"},
    "d548b391375748e2b5ad4d52b88e6dc4":{
      "scriptId":"u32"},
    "bf8dca13048c4ed7821833b1302907f0":{
      "scriptId":"u33"},
    "3ab35e6465c9433c93b1cad0b64880de":{
      "scriptId":"u34"},
    "78b30f36e6dd4d0da58229bc1010cac3":{
      "scriptId":"u35"},
    "dca683225efd4c6c9cb3d52d7aea7584":{
      "scriptId":"u36"},
    "a6f6ae819bd848aa846f8ca192c93f70":{
      "scriptId":"u37"},
    "81317879bde3490c8a126b69225c1021":{
      "scriptId":"u38"},
    "033d459226034b97abf0a812be34fae1":{
      "scriptId":"u39"},
    "1035c4eb6128497287233bd227c35128":{
      "scriptId":"u40"},
    "42f7ad6611bb48538f7f444c99b86f63":{
      "scriptId":"u41"},
    "4b8360748b4f4aa0a5983078fa0b3c4a":{
      "scriptId":"u42"},
    "8af5553677b1494d924c43159f0dac5d":{
      "scriptId":"u43"},
    "b0977ccf1cf541ecb0c5c2cbc7206dc8":{
      "scriptId":"u44"},
    "4c00b1f86d42498d9b5ab0bf48b58a83":{
      "scriptId":"u45"},
    "f10573097fdc4691983b8c4d7efe2a6b":{
      "scriptId":"u46"},
    "d8f25e0266194096bf3ab6b4c6b58403":{
      "scriptId":"u47"},
    "998a072444fa48a88e67344067bd9b93":{
      "scriptId":"u48"},
    "106e459c9d584d808601ac07403a3753":{
      "scriptId":"u49"},
    "b7b2f7bea7e1433caa6f805d051f5181":{
      "scriptId":"u50"},
    "4e83e7969f414dbbb3cc10da2ec1c1e3":{
      "scriptId":"u51"},
    "677471319c084f7a9c59106bd7545499":{
      "scriptId":"u52"},
    "693aeec681ee45d3abb91c13b45956d2":{
      "scriptId":"u53"},
    "3bb8f562acdd4ea5a89f6a3f1febe7ea":{
      "scriptId":"u54"},
    "8f5db0df6f7b485e80a2dbe8c91f396b":{
      "scriptId":"u55"},
    "9ccb2ada95174b498d608325b310087e":{
      "scriptId":"u56"},
    "a2bcc6a4c1964c02b74fc9482cf58355":{
      "scriptId":"u57"},
    "bf06c59a240f472f9a4bb2b7b95f4453":{
      "scriptId":"u58"},
    "337478b8fe2645809737dccec56f50eb":{
      "scriptId":"u59"},
    "f3d4e5dd002f4769954f9dd14d71e67a":{
      "scriptId":"u60"},
    "adc3d629200c4c57a5fb8b18b676cfd1":{
      "scriptId":"u61"},
    "45f1bcb61b50441fb980fd4b817ff680":{
      "scriptId":"u62"},
    "987f174d3aae449993e61b4f607075b3":{
      "scriptId":"u63"},
    "441c47a7bd2344fba9c3d74b15833ccc":{
      "scriptId":"u64"},
    "6e2a9064d5fe41f0b997325b686a9904":{
      "scriptId":"u65"},
    "dc7fcd5d82694fbbbdbdaefb7294122f":{
      "scriptId":"u66"},
    "3bce7f25a1544f178fcde032b25e8a5e":{
      "scriptId":"u67"},
    "355821a33339435a8dc4addb741fb733":{
      "scriptId":"u68"},
    "996776b15a324c9b9d93e4fada76b17c":{
      "scriptId":"u69"},
    "0c60a8612bd14523ad064545b830c48e":{
      "scriptId":"u70"},
    "bfdc662f3b0545729bfb6fd182af514b":{
      "scriptId":"u71"},
    "0e61e23f03204b60b38b09d4a736b0b7":{
      "scriptId":"u72"},
    "d1bf2ebf4ecd450da9c021b4d6ff1b04":{
      "scriptId":"u73"},
    "a0dbde0e55cc44679d46003e6ee91253":{
      "scriptId":"u74"},
    "353bf9364956499f8c2c1331364526c6":{
      "scriptId":"u75"},
    "78c69d3dda634098bd4cd3e8c85d7f51":{
      "scriptId":"u76"},
    "8b649765ef28446ebf34f74488ba30f6":{
      "scriptId":"u77"},
    "946a1f759ee74304add5955044203b42":{
      "scriptId":"u78"},
    "6f7789e2f2da4a4bb2a358e25eac5a96":{
      "scriptId":"u79"},
    "9accb3d893654dfba85cae88c9a76e4c":{
      "scriptId":"u80"},
    "0e31f972d41a4247a84f47c674713d7a":{
      "scriptId":"u81"},
    "1b318ee6c8a84a1db06b1540b5eb3e87":{
      "scriptId":"u82"},
    "fa95d6c57aac41788b4431e272d7273a":{
      "scriptId":"u83"},
    "cc27a68a85174ea2bcbb160010624232":{
      "scriptId":"u84"},
    "a9724fcad23c44f38765943d97557998":{
      "scriptId":"u85"},
    "f4813f72ac2a45308c40259e3f5419e6":{
      "scriptId":"u86"}}});