$axure.loadCurrentPage({
  "url":"注册成功.html",
  "generationDate":new Date(1440075580045.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"892239b780684411a861969fb27707dc",
    "type":"Axure:Page",
    "name":"注册成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2821b552a34a4c539c4db71fc29c9a1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"28px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":0,
              "y":110},
            "size":{
              "width":1000,
              "height":540},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48ab0eb5edfc4eaca3e0f96a924d360f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"28px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":110},
                "size":{
                  "width":1000,
                  "height":540},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u0.png"}},
{
          "id":"2b1b1e241e234e9b8f400197b6b2fd76",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":140},
            "size":{
              "width":900,
              "height":500},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdf3ee722ed04c0cb9ee2199aabcb8d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":140},
                "size":{
                  "width":900,
                  "height":500},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u2.png"}},
{
          "id":"055ea90b25064988b76d2ccdec772c43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":140},
            "size":{
              "width":300,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aefc1c31529c469da65307ee5dfa2f75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":140},
                "size":{
                  "width":300,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u4.png"}},
{
          "id":"4cc5150ed70a44eb9d8cfbf658cb4d18",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":40},
            "size":{
              "width":110,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50a52f0c5c584e98b88e029bce551b37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":40},
                "size":{
                  "width":110,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u24.png"}},
{
          "id":"594c9cc08a9a47028a8535fa0275013a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":62,
              "y":48},
            "size":{
              "width":88,
              "height":43},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d477f45050e44ecae1a5d4d284d45ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":62,
                  "y":48},
                "size":{
                  "width":88,
                  "height":43},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u26.png"}},
{
          "id":"fcdfc112068649398f157f72e1c59e5a",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1080,
              "y":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1D82DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9c6f08c6520498f8c6454c333262bc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1080,
                  "y":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1D82DE}},
              "adaptiveStyles":{
}}]},
{
          "id":"47b24262c07141098690e6038bfe4b09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1088,
              "y":18},
            "size":{
              "width":82,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df237845dbae4bfbaa3fc8b4640fe595",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1088,
                  "y":18},
                "size":{
                  "width":82,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d039e848a54248df868dbf13aebc43a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":174,
              "y":243},
            "size":{
              "width":723,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0e877a17b07416a8ca26e9cd2e73c17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":174,
                  "y":243},
                "size":{
                  "width":723,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"457a24a7484a48d6bcfaa03f20c138de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":200},
            "size":{
              "width":470,
              "height":380}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a168a793aa3420eb8675d98a00d2b14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":200},
                "size":{
                  "width":470,
                  "height":380}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册成功/u16.png"}},
{
          "id":"035c97963a5e4a3691b480c7e622b668",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":130,
              "y":330},
            "size":{
              "width":220,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c39559e5c5840a687d11bc1c827ca3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":130,
                  "y":330},
                "size":{
                  "width":220,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册成功/u18.png"}},
{
          "id":"19870fdfdf8a475a8bc7e20c96f7d324",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":220},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68427f72831a4546af07890a50d375c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":220},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册成功/u20.png"}},
{
          "id":"b8c45eec699844eabe8e5e0fcc428d8e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1090,
              "y":360},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1D82DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0767f7ed20b457c9a9a70edca841786",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1090,
                  "y":360},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1D82DE}},
              "adaptiveStyles":{
}}]},
{
          "id":"5ac31d2915da410b8d2102d774ff1fb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1104,
              "y":351},
            "size":{
              "width":296,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc475509dc584dfba708e4cd785dabaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1104,
                  "y":351},
                "size":{
                  "width":296,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35ef8bec71604576a99ddf68b9277a36",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":650},
            "size":{
              "width":665,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a87c4e761fc45008fbbd4e67f9f0819",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":650},
                "size":{
                  "width":665,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u82.png"}},
{
          "id":"bfed89cd85ad4927aaa40fabd1171fa6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":429,
              "y":660},
            "size":{
              "width":60,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be1761ca9cf74590b375deae83005c0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":429,
                  "y":660},
                "size":{
                  "width":60,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册成功/u28.png"}},
{
          "id":"01473f026034430596b8e98624edbf12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":215,
              "y":690},
            "size":{
              "width":580,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77659539347c48a69ecd941a26d6f87d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":215,
                  "y":690},
                "size":{
                  "width":580,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u96.png"}},
{
          "id":"90325ef945394354898954910b23b2c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":0,
              "y":650},
            "size":{
              "width":190,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a621bf8a467545eea984dcd55372e715",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":0,
                  "y":650},
                "size":{
                  "width":190,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u84.png"}},
{
          "id":"ad2aa02ffc3d4f749080c986772c473f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":810,
              "y":650},
            "size":{
              "width":190,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f97e8440179f4d5c85aa814fd190f9cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":810,
                  "y":650},
                "size":{
                  "width":190,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u84.png"}},
{
          "id":"2272aedba9f842719e681cb094cf0f49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":0,
              "y":720},
            "size":{
              "width":1000,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"197735dfd1a446f0a36a674e90928ef3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":0,
                  "y":720},
                "size":{
                  "width":1000,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u88.png"}},
{
          "id":"6e9e3cec32fa4a1dba49758840784287",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":210,
              "y":691},
            "size":{
              "width":580,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b1abc940d934786ae4dda48f249ffd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":210,
                  "y":691},
                "size":{
                  "width":580,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u96.png"}},
{
          "id":"52dff565d50b4d98bd89ec2bf33fb216",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":185,
              "y":660},
            "size":{
              "width":630,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29d7b73a305f4a28933f71f5196a0c63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":185,
                  "y":660},
                "size":{
                  "width":630,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u98.png"}},
{
          "id":"cfd7fa364d4a48aeb172a711d5b6b7d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":265,
              "y":665},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37d1d72f6f284801989272bbc5d03ac1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":265,
                  "y":665},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac761ef31e2041819ae61a9d11baea98",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":345,
              "y":665},
            "size":{
              "width":10,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册/u102_line.png"}},
{
          "id":"556059c7f8c241a2866acb5334a3095b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":357,
              "y":665},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6ab22d8942746d1886ad36b74af81ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":357,
                  "y":665},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83d435447d6d42409f3b13f14c652594",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":438,
              "y":665},
            "size":{
              "width":10,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册/u102_line.png"}},
{
          "id":"cbaa0d1f247e4940b5e3456211b1fe59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":448,
              "y":665},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a1c4c894a564518bbbc2a299965ed82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":448,
                  "y":665},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ec0767ae66a413ba34b22ae07b2f1af",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":527,
              "y":665},
            "size":{
              "width":10,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册/u102_line.png"}},
{
          "id":"79f5c4b71ac449e5a3c08c52ae75bfa3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":538,
              "y":665},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47bd818a52964d4b9aa41ce4b21895f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":538,
                  "y":665},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fadf44cbb094706a548fc8a0a302531",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":665},
            "size":{
              "width":10,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册/u102_line.png"}},
{
          "id":"183edf75423f4469b24a835fc09b9a24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":627,
              "y":665},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"777bb959c5ec4f809780930a4723d9af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":627,
                  "y":665},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36519afcef1e47f68c57192e073df369",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":838,
              "y":60},
            "size":{
              "width":72,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36652ebc376342588422350bb3d5d20e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":838,
                  "y":60},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"a6ea0bba153b40e78eaca4cf22469778",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":747,
              "y":60},
            "size":{
              "width":73,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"089eb2f65e294dedb17fd0e672882f8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":747,
                  "y":60},
                "size":{
                  "width":73,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"13e2057b9eb2415e81122ffa8362e253",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":693,
              "y":60},
            "size":{
              "width":54,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"080e4be032e741c58e8f02b8738ca359",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":693,
                  "y":60},
                "size":{
                  "width":54,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"55bd557abb3b40e49fda86738034a6c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":928,
              "y":60},
            "size":{
              "width":72,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"368b986487f54c12a6afb6d3fc348377",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":928,
                  "y":60},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2821b552a34a4c539c4db71fc29c9a1b":{
      "scriptId":"u0"},
    "48ab0eb5edfc4eaca3e0f96a924d360f":{
      "scriptId":"u1"},
    "2b1b1e241e234e9b8f400197b6b2fd76":{
      "scriptId":"u2"},
    "cdf3ee722ed04c0cb9ee2199aabcb8d6":{
      "scriptId":"u3"},
    "055ea90b25064988b76d2ccdec772c43":{
      "scriptId":"u4"},
    "aefc1c31529c469da65307ee5dfa2f75":{
      "scriptId":"u5"},
    "4cc5150ed70a44eb9d8cfbf658cb4d18":{
      "scriptId":"u6"},
    "50a52f0c5c584e98b88e029bce551b37":{
      "scriptId":"u7"},
    "594c9cc08a9a47028a8535fa0275013a":{
      "scriptId":"u8"},
    "2d477f45050e44ecae1a5d4d284d45ad":{
      "scriptId":"u9"},
    "fcdfc112068649398f157f72e1c59e5a":{
      "scriptId":"u10"},
    "f9c6f08c6520498f8c6454c333262bc7":{
      "scriptId":"u11"},
    "47b24262c07141098690e6038bfe4b09":{
      "scriptId":"u12"},
    "df237845dbae4bfbaa3fc8b4640fe595":{
      "scriptId":"u13"},
    "d039e848a54248df868dbf13aebc43a6":{
      "scriptId":"u14"},
    "a0e877a17b07416a8ca26e9cd2e73c17":{
      "scriptId":"u15"},
    "457a24a7484a48d6bcfaa03f20c138de":{
      "scriptId":"u16"},
    "1a168a793aa3420eb8675d98a00d2b14":{
      "scriptId":"u17"},
    "035c97963a5e4a3691b480c7e622b668":{
      "scriptId":"u18"},
    "1c39559e5c5840a687d11bc1c827ca3c":{
      "scriptId":"u19"},
    "19870fdfdf8a475a8bc7e20c96f7d324":{
      "scriptId":"u20"},
    "68427f72831a4546af07890a50d375c8":{
      "scriptId":"u21"},
    "b8c45eec699844eabe8e5e0fcc428d8e":{
      "scriptId":"u22"},
    "f0767f7ed20b457c9a9a70edca841786":{
      "scriptId":"u23"},
    "5ac31d2915da410b8d2102d774ff1fb4":{
      "scriptId":"u24"},
    "bc475509dc584dfba708e4cd785dabaa":{
      "scriptId":"u25"},
    "35ef8bec71604576a99ddf68b9277a36":{
      "scriptId":"u26"},
    "8a87c4e761fc45008fbbd4e67f9f0819":{
      "scriptId":"u27"},
    "bfed89cd85ad4927aaa40fabd1171fa6":{
      "scriptId":"u28"},
    "be1761ca9cf74590b375deae83005c0a":{
      "scriptId":"u29"},
    "01473f026034430596b8e98624edbf12":{
      "scriptId":"u30"},
    "77659539347c48a69ecd941a26d6f87d":{
      "scriptId":"u31"},
    "90325ef945394354898954910b23b2c9":{
      "scriptId":"u32"},
    "a621bf8a467545eea984dcd55372e715":{
      "scriptId":"u33"},
    "ad2aa02ffc3d4f749080c986772c473f":{
      "scriptId":"u34"},
    "f97e8440179f4d5c85aa814fd190f9cb":{
      "scriptId":"u35"},
    "2272aedba9f842719e681cb094cf0f49":{
      "scriptId":"u36"},
    "197735dfd1a446f0a36a674e90928ef3":{
      "scriptId":"u37"},
    "6e9e3cec32fa4a1dba49758840784287":{
      "scriptId":"u38"},
    "5b1abc940d934786ae4dda48f249ffd5":{
      "scriptId":"u39"},
    "52dff565d50b4d98bd89ec2bf33fb216":{
      "scriptId":"u40"},
    "29d7b73a305f4a28933f71f5196a0c63":{
      "scriptId":"u41"},
    "cfd7fa364d4a48aeb172a711d5b6b7d3":{
      "scriptId":"u42"},
    "37d1d72f6f284801989272bbc5d03ac1":{
      "scriptId":"u43"},
    "ac761ef31e2041819ae61a9d11baea98":{
      "scriptId":"u44"},
    "556059c7f8c241a2866acb5334a3095b":{
      "scriptId":"u45"},
    "e6ab22d8942746d1886ad36b74af81ca":{
      "scriptId":"u46"},
    "83d435447d6d42409f3b13f14c652594":{
      "scriptId":"u47"},
    "cbaa0d1f247e4940b5e3456211b1fe59":{
      "scriptId":"u48"},
    "1a1c4c894a564518bbbc2a299965ed82":{
      "scriptId":"u49"},
    "9ec0767ae66a413ba34b22ae07b2f1af":{
      "scriptId":"u50"},
    "79f5c4b71ac449e5a3c08c52ae75bfa3":{
      "scriptId":"u51"},
    "47bd818a52964d4b9aa41ce4b21895f5":{
      "scriptId":"u52"},
    "5fadf44cbb094706a548fc8a0a302531":{
      "scriptId":"u53"},
    "183edf75423f4469b24a835fc09b9a24":{
      "scriptId":"u54"},
    "777bb959c5ec4f809780930a4723d9af":{
      "scriptId":"u55"},
    "36519afcef1e47f68c57192e073df369":{
      "scriptId":"u56"},
    "36652ebc376342588422350bb3d5d20e":{
      "scriptId":"u57"},
    "a6ea0bba153b40e78eaca4cf22469778":{
      "scriptId":"u58"},
    "089eb2f65e294dedb17fd0e672882f8a":{
      "scriptId":"u59"},
    "13e2057b9eb2415e81122ffa8362e253":{
      "scriptId":"u60"},
    "080e4be032e741c58e8f02b8738ca359":{
      "scriptId":"u61"},
    "55bd557abb3b40e49fda86738034a6c6":{
      "scriptId":"u62"},
    "368b986487f54c12a6afb6d3fc348377":{
      "scriptId":"u63"}}});