$axure.loadCurrentPage({
  "url":"用户管理-个人用户列表-完成.html",
  "generationDate":new Date(1441157429134.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2eae7f5219fd4de28460da8ef9aca81d",
    "type":"Axure:Page",
    "name":"用户管理-个人用户列表-完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6a63ffe04a6d47a2b3fd25bad694d2dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":1180,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5f1fccd3d6e459fb76963bd641508b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":1180,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u0.png"}},
{
          "id":"d6f4144d74c24344b0d3da91b67e440e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":140},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ac03bb647df4ffcaae4e30a883fc1df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":140},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"8adf8d9210d0413ea9a8ed1d5b77439d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":55,
              "y":190},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7617cf6a3c3644dfb87c0d691ed351cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":55,
                  "y":190},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u2.png"}},
{
          "id":"4da47382f0d94b65a01c2457103d8dd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":240},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ce6f0c85db94aaaaae53f55fd76e5c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":240},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"b080733c90b94431a2fe244a1c5e3da5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":290},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd89269e588b421b9b896b776d2e86ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":290},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"8402a04dac8f4b049a1e7a5e179d6ed5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":340},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53dcfa3358684f6980db8f876eb3efe4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":340},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"e4632a9745bb44bc80feffd307a83da5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":390},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6081e2dc53c74a6caa6b7d90f00e359a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":390},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"755093860e0e49b0b336bd2a562232cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":440},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcd809613c45493aa0959a505e917708",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":440},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"44ea9b45b0c04eb9b869a712f2702709",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":490},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d247b549af14446d9cf6517243b4477c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":490},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"a9241b9d72014aeb938e76d34d853a00",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":76},
            "size":{
              "width":1180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/预约管理-未下载-完成/u18_line.png"}},
{
          "id":"5e2dd85c751b41518dad7cdc88c1a8d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":26},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f320d2b2c9654ade9896c2c63eb5fb10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":26},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95816726e9d447aabca85714d9dbf1ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1137,
              "y":26},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33743e79112543b0bf9553f03b99fcca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1137,
                  "y":26},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d59b21d149348259b2cccf72ffe642b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":18},
            "size":{
              "width":135,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3084653cb0924f76a55d8b5f20ce1ce7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":18},
                "size":{
                  "width":135,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u23.png"}},
{
          "id":"d0392c3d23994842a8b6ef99eb51a717",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":33},
            "size":{
              "width":270,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"861c50fa708c45b48ec80d4e9fe2bbd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":33},
                "size":{
                  "width":270,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89881631b6ce4f9ab7d68b6d626c1cea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":52},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a9d0a3eb5c54ee1a61fa90493320702",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":52},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70608e70a48d4401bdec56cf03dcda66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1147,
              "y":52},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fbe7d4488f147268b1217c8aaa22f94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1147,
                  "y":52},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8532a88a0e249d69b0b55fa531b3755",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":190},
            "size":{
              "width":950,
              "height":350}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b55484f254f4dc0a685bb70ebc102c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":190},
                "size":{
                  "width":950,
                  "height":350}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户管理-个人用户列表-完成/u31.png"}},
{
          "id":"bd11dcd95f424435a2ed14f0d4ab73b5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":623,
              "y":200},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4da04239cd154681853299e5c917c533",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":200},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dc4ab367cf67458bbb733a2e434e97b6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":419,
              "y":208},
            "size":{
              "width":15,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/预约管理-未下载-完成/u35_line.png"}},
{
          "id":"65d8bbe580e64ed889dde03433c5b537",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":444,
              "y":200},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"556ffdc436d04a7db540703e0a97af83",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":853,
              "y":200},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d93ee6c1c2934b1282e40b76fcffaa82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":853,
                  "y":200},
                "size":{
                  "width":50,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u37.png"}},
{
          "id":"c8af7f4437d94c789b7b21946464b04c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":250,
              "y":150},
            "size":{
              "width":119,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db7535d885fc408b9d437c05fca4df4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":250,
                  "y":150},
                "size":{
                  "width":119,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户管理-个人用户列表-完成/u39.png"}},
{
          "id":"4776275a024a4a2c8b13eb3754b37798",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":369,
              "y":150},
            "size":{
              "width":119,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"647ad07da213462ab676769af0df1d89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":369,
                  "y":150},
                "size":{
                  "width":119,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u41.png"}},
{
          "id":"6287a3292ff541ecae6fec924db46579",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":244},
            "size":{
              "width":760,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbddc72dfd8649f1bf6b29f0e745a8f2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a529fda4ffab459087a24210ae394f85",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u44.png"}},
{
              "id":"39edd75c726f4496a550e603878f4b7f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":150,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f17e8fd3fa644ae4a0e080366c8d1e28",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":150,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u54.png"}},
{
              "id":"bde6a2d6233a4b2086bf3ab959fba99c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":77},
                "size":{
                  "width":150,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4fd9c0081dd640d99dccb505af182a33",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":77},
                    "size":{
                      "width":150,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u64.png"}},
{
              "id":"641f797442cc430d803e3a5c2a5a28fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":150,
                  "y":0},
                "size":{
                  "width":166,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3312e88b54e4eb294ee914c1befde17",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":150,
                      "y":0},
                    "size":{
                      "width":166,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u46.png"}},
{
              "id":"2bc04c54134d4586b8165c760ac65606",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":40},
                "size":{
                  "width":166,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"07440a0c539d479ab7f2232c1a4cd371",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":40},
                    "size":{
                      "width":166,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u56.png"}},
{
              "id":"bd8a6981250d46fb825c03ba7dc02ee7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":77},
                "size":{
                  "width":166,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c9de2e7d6ed74eea9c64b4127c1cd264",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":77},
                    "size":{
                      "width":166,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u66.png"}},
{
              "id":"a6cbc277644f40c086636dde5017c0c7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":316,
                  "y":0},
                "size":{
                  "width":140,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2fd319517ea54a8d93a1af8e1b1230f4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":316,
                      "y":0},
                    "size":{
                      "width":140,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u48.png"}},
{
              "id":"2485c6d4880b488e89d3cb968ec41041",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":316,
                  "y":40},
                "size":{
                  "width":140,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a59a5fd52d31436ba46afd073e7607a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":316,
                      "y":40},
                    "size":{
                      "width":140,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u58.png"}},
{
              "id":"176f8b78cd274492950e424f1e4e1ad8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":316,
                  "y":77},
                "size":{
                  "width":140,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2cace3efcf38484f836ecd2739563ad7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":316,
                      "y":77},
                    "size":{
                      "width":140,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u68.png"}},
{
              "id":"37cdea7cef364e21908fb045e3be34a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":456,
                  "y":0},
                "size":{
                  "width":152,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6ceb93a0af0f4bde87b6e4afe6bd14a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":456,
                      "y":0},
                    "size":{
                      "width":152,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u50.png"}},
{
              "id":"b407bea8fd804c64b4aa89b32ef0440c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":456,
                  "y":40},
                "size":{
                  "width":152,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5226b195f4f640fc900dabd782972538",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":456,
                      "y":40},
                    "size":{
                      "width":152,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u60.png"}},
{
              "id":"5b98482650384e5f8639cc6998d3b446",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":456,
                  "y":77},
                "size":{
                  "width":152,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c2f303d5afc4f869b634e168a8ba1d7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":456,
                      "y":77},
                    "size":{
                      "width":152,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u70.png"}},
{
              "id":"5c558c779c37482faa0cdecf97a5ae57",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":608,
                  "y":0},
                "size":{
                  "width":152,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"582ebd7f9ceb435a8a78498e82c302d0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":608,
                      "y":0},
                    "size":{
                      "width":152,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u52.png"}},
{
              "id":"43f360a955dc415783fc8c8545e2445d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":608,
                  "y":40},
                "size":{
                  "width":152,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"24e96b8a70be4471afa539a1c0701103",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000CC,
                      "opacity":1},
                    "location":{
                      "x":608,
                      "y":40},
                    "size":{
                      "width":152,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u62.png"}},
{
              "id":"dfef4c6248ed4e33881d941a2410ff98",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":608,
                  "y":77},
                "size":{
                  "width":152,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d65be74abd8c4a67bb6155cc04a04bfd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000CC,
                      "opacity":1},
                    "location":{
                      "x":608,
                      "y":77},
                    "size":{
                      "width":152,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u72.png"}}]},
{
          "id":"152a6e92698b4278929ef79d19961b38",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":533,
              "y":202},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"1d883e59b676437780a241379b3abdcd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":452},
            "size":{
              "width":560,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b14c36e0996246e7947558c2d80dc03d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":452},
                "size":{
                  "width":560,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u101.png"}},
{
          "id":"02dc3db17d3145f0a9032445a177affb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":104},
            "size":{
              "width":225,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"460689345e7540a2bf6178e62bedec06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":104},
                "size":{
                  "width":225,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f30599380b54741837ca2865edbe736",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":204},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c659bec61e15415ca66d5b685040fd86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":266,
                  "y":204},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6a63ffe04a6d47a2b3fd25bad694d2dd":{
      "scriptId":"u0"},
    "d5f1fccd3d6e459fb76963bd641508b6":{
      "scriptId":"u1"},
    "d6f4144d74c24344b0d3da91b67e440e":{
      "scriptId":"u2"},
    "9ac03bb647df4ffcaae4e30a883fc1df":{
      "scriptId":"u3"},
    "8adf8d9210d0413ea9a8ed1d5b77439d":{
      "scriptId":"u4"},
    "7617cf6a3c3644dfb87c0d691ed351cf":{
      "scriptId":"u5"},
    "4da47382f0d94b65a01c2457103d8dd5":{
      "scriptId":"u6"},
    "6ce6f0c85db94aaaaae53f55fd76e5c9":{
      "scriptId":"u7"},
    "b080733c90b94431a2fe244a1c5e3da5":{
      "scriptId":"u8"},
    "fd89269e588b421b9b896b776d2e86ac":{
      "scriptId":"u9"},
    "8402a04dac8f4b049a1e7a5e179d6ed5":{
      "scriptId":"u10"},
    "53dcfa3358684f6980db8f876eb3efe4":{
      "scriptId":"u11"},
    "e4632a9745bb44bc80feffd307a83da5":{
      "scriptId":"u12"},
    "6081e2dc53c74a6caa6b7d90f00e359a":{
      "scriptId":"u13"},
    "755093860e0e49b0b336bd2a562232cb":{
      "scriptId":"u14"},
    "dcd809613c45493aa0959a505e917708":{
      "scriptId":"u15"},
    "44ea9b45b0c04eb9b869a712f2702709":{
      "scriptId":"u16"},
    "d247b549af14446d9cf6517243b4477c":{
      "scriptId":"u17"},
    "a9241b9d72014aeb938e76d34d853a00":{
      "scriptId":"u18"},
    "5e2dd85c751b41518dad7cdc88c1a8d4":{
      "scriptId":"u19"},
    "f320d2b2c9654ade9896c2c63eb5fb10":{
      "scriptId":"u20"},
    "95816726e9d447aabca85714d9dbf1ef":{
      "scriptId":"u21"},
    "33743e79112543b0bf9553f03b99fcca":{
      "scriptId":"u22"},
    "2d59b21d149348259b2cccf72ffe642b":{
      "scriptId":"u23"},
    "3084653cb0924f76a55d8b5f20ce1ce7":{
      "scriptId":"u24"},
    "d0392c3d23994842a8b6ef99eb51a717":{
      "scriptId":"u25"},
    "861c50fa708c45b48ec80d4e9fe2bbd0":{
      "scriptId":"u26"},
    "89881631b6ce4f9ab7d68b6d626c1cea":{
      "scriptId":"u27"},
    "8a9d0a3eb5c54ee1a61fa90493320702":{
      "scriptId":"u28"},
    "70608e70a48d4401bdec56cf03dcda66":{
      "scriptId":"u29"},
    "8fbe7d4488f147268b1217c8aaa22f94":{
      "scriptId":"u30"},
    "b8532a88a0e249d69b0b55fa531b3755":{
      "scriptId":"u31"},
    "6b55484f254f4dc0a685bb70ebc102c1":{
      "scriptId":"u32"},
    "bd11dcd95f424435a2ed14f0d4ab73b5":{
      "scriptId":"u33"},
    "4da04239cd154681853299e5c917c533":{
      "scriptId":"u34"},
    "dc4ab367cf67458bbb733a2e434e97b6":{
      "scriptId":"u35"},
    "65d8bbe580e64ed889dde03433c5b537":{
      "scriptId":"u36"},
    "556ffdc436d04a7db540703e0a97af83":{
      "scriptId":"u37"},
    "d93ee6c1c2934b1282e40b76fcffaa82":{
      "scriptId":"u38"},
    "c8af7f4437d94c789b7b21946464b04c":{
      "scriptId":"u39"},
    "db7535d885fc408b9d437c05fca4df4d":{
      "scriptId":"u40"},
    "4776275a024a4a2c8b13eb3754b37798":{
      "scriptId":"u41"},
    "647ad07da213462ab676769af0df1d89":{
      "scriptId":"u42"},
    "6287a3292ff541ecae6fec924db46579":{
      "scriptId":"u43"},
    "dbddc72dfd8649f1bf6b29f0e745a8f2":{
      "scriptId":"u44"},
    "a529fda4ffab459087a24210ae394f85":{
      "scriptId":"u45"},
    "641f797442cc430d803e3a5c2a5a28fe":{
      "scriptId":"u46"},
    "e3312e88b54e4eb294ee914c1befde17":{
      "scriptId":"u47"},
    "a6cbc277644f40c086636dde5017c0c7":{
      "scriptId":"u48"},
    "2fd319517ea54a8d93a1af8e1b1230f4":{
      "scriptId":"u49"},
    "37cdea7cef364e21908fb045e3be34a2":{
      "scriptId":"u50"},
    "6ceb93a0af0f4bde87b6e4afe6bd14a5":{
      "scriptId":"u51"},
    "5c558c779c37482faa0cdecf97a5ae57":{
      "scriptId":"u52"},
    "582ebd7f9ceb435a8a78498e82c302d0":{
      "scriptId":"u53"},
    "39edd75c726f4496a550e603878f4b7f":{
      "scriptId":"u54"},
    "f17e8fd3fa644ae4a0e080366c8d1e28":{
      "scriptId":"u55"},
    "2bc04c54134d4586b8165c760ac65606":{
      "scriptId":"u56"},
    "07440a0c539d479ab7f2232c1a4cd371":{
      "scriptId":"u57"},
    "2485c6d4880b488e89d3cb968ec41041":{
      "scriptId":"u58"},
    "a59a5fd52d31436ba46afd073e7607a0":{
      "scriptId":"u59"},
    "b407bea8fd804c64b4aa89b32ef0440c":{
      "scriptId":"u60"},
    "5226b195f4f640fc900dabd782972538":{
      "scriptId":"u61"},
    "43f360a955dc415783fc8c8545e2445d":{
      "scriptId":"u62"},
    "24e96b8a70be4471afa539a1c0701103":{
      "scriptId":"u63"},
    "bde6a2d6233a4b2086bf3ab959fba99c":{
      "scriptId":"u64"},
    "4fd9c0081dd640d99dccb505af182a33":{
      "scriptId":"u65"},
    "bd8a6981250d46fb825c03ba7dc02ee7":{
      "scriptId":"u66"},
    "c9de2e7d6ed74eea9c64b4127c1cd264":{
      "scriptId":"u67"},
    "176f8b78cd274492950e424f1e4e1ad8":{
      "scriptId":"u68"},
    "2cace3efcf38484f836ecd2739563ad7":{
      "scriptId":"u69"},
    "5b98482650384e5f8639cc6998d3b446":{
      "scriptId":"u70"},
    "5c2f303d5afc4f869b634e168a8ba1d7":{
      "scriptId":"u71"},
    "dfef4c6248ed4e33881d941a2410ff98":{
      "scriptId":"u72"},
    "d65be74abd8c4a67bb6155cc04a04bfd":{
      "scriptId":"u73"},
    "152a6e92698b4278929ef79d19961b38":{
      "scriptId":"u74"},
    "1d883e59b676437780a241379b3abdcd":{
      "scriptId":"u75"},
    "b14c36e0996246e7947558c2d80dc03d":{
      "scriptId":"u76"},
    "02dc3db17d3145f0a9032445a177affb":{
      "scriptId":"u77"},
    "460689345e7540a2bf6178e62bedec06":{
      "scriptId":"u78"},
    "8f30599380b54741837ca2865edbe736":{
      "scriptId":"u79"},
    "c659bec61e15415ca66d5b685040fd86":{
      "scriptId":"u80"}}});