$axure.loadCurrentPage({
  "url":"添加和编辑页面-制作中.html",
  "generationDate":new Date(1441157430056.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9266e9bb28b54d9c917e88a0c59399b8",
    "type":"Axure:Page",
    "name":"添加和编辑页面-制作中",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"72daeef571694b33909bad53571b8a5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":1180,
              "height":750}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dfd71e9027f443fb8feaca977a9eaa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":1180,
                  "height":750}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加和编辑页面-制作中/u0.png"}},
{
          "id":"afb49f385e76407f855ee12c1f87a283",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":140},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e670dd0e64ca41509de975a418f380b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":140},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"71c022e5b89143ec9451d6ad713c622e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":190},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b926ac0fd074df18916060fd0ca6572",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":190},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"a49ee78bcfb844128758324ede9b5af2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":240},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f357caeee43c4639b2e141bc230c0198",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":240},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"014227e913744deaac2ac125aded7300",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":290},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88ee76e3581a4e798dd63993bf894a3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":290},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"394a927a63c341ebbaae4e34e82ed9ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":55,
              "y":340},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf41ecd463a74dc5b9dd6cbc8b94d43b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":55,
                  "y":340},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u2.png"}},
{
          "id":"b4872c5e1ffb4eb78657da6671b9040a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":390},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83a467bfc9124443a2bc09019cc4908c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":390},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"3f267c2a2b0d42d7993d1a526be93b48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":440},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0aa7b278a8d4cf3ba84c764e5188a01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":440},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"84963d53dfdb40c798780105e4ee5220",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":490},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c46b7043c85444038d41b2db389869f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":490},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"9fbc09314ec247e7af343ed0fb1c3e79",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":76},
            "size":{
              "width":1180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/预约管理-未下载-完成/u18_line.png"}},
{
          "id":"c2a58b991bf54f16a38e8ab8e3c317da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":26},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09373a3a164245a7ab7aac6a6546206a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":26},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14f5011466f54e64a0c86893014e5e0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1137,
              "y":26},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95d95df8cd2043dcb9b509351f2961c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1137,
                  "y":26},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b0b6f351c8d4a3a8107b102dc68d713",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":18},
            "size":{
              "width":135,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"767a5d912ddf47ab8e665f803d550c09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":18},
                "size":{
                  "width":135,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u23.png"}},
{
          "id":"f6d7d2e912954b11b0a241642e5fa95c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":33},
            "size":{
              "width":270,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3fdd2174b744eceb587c5ee953ef60e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":33},
                "size":{
                  "width":270,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"137e3373733c4234b3b6a0a44ad3ad2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":52},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"163e6bd6561444cc8aa5d1955902302f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":52},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44c2f167bd814b2cb982ea487d5041dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1147,
              "y":52},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e44e3b3f26794e04b47d36ff91d5756e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1147,
                  "y":52},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39699ba83a4241e480a6bf907fc407b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":140},
            "size":{
              "width":950,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcfa01d142ba457393efe809a177e82a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":140},
                "size":{
                  "width":950,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加和编辑页面-制作中/u31.png"}},
{
          "id":"52e216144c0b4f178e922391da5e5922",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":104},
            "size":{
              "width":225,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fefb5cd44c840d69b14b561119e50cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":104},
                "size":{
                  "width":225,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7e5d2640e494e96982c346cc102ae37",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":170},
            "size":{
              "width":146,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2d56e9315c5e42d388041b74905d6671",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":174},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cb43308b44f47ec84e62ff62bdf8f17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":174},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7936f90de4d748d9bca2a70a1bd3655b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":214},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21d0615eefd8483a8fa62467e44ddabf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":214},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"157e7a25640a4d309443c5f885e619aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":257},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b7bf5627732491a976de29373899e13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":257},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78e1e3ef0998496daa0c43c92e7c638a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":209},
            "size":{
              "width":146,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4ebdac9f92014e44b116416af14fa418",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":265},
            "size":{
              "width":352,
              "height":405}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65706282ad2d43e6a68ec3a9193119e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":368,
                  "y":265},
                "size":{
                  "width":352,
                  "height":405}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加和编辑页面-制作中/u43.png"}},
{
          "id":"29b373a103c44e2cb178c26887cb0edb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":368,
              "y":690},
            "size":{
              "width":112,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3d7004e44784014ba36e0f5e194bcb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":368,
                  "y":690},
                "size":{
                  "width":112,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加和编辑页面-制作中/u45.png"}},
{
          "id":"fcc3fa864aae4b429cd9177976a86653",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":690},
            "size":{
              "width":112,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14bd6b1dae054c1fac8213b6819d0956",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":690},
                "size":{
                  "width":112,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加和编辑页面-制作中/u47.png"}},
{
          "id":"595f49c047a947c6aabbf64300d20a46",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":280},
            "size":{
              "width":220,
              "height":390}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"faf53825c3e446599101c838f655f9ab",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"82ab0eb6d57e4ecc91065e4b88a0b1f9",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6848a7717da24f928ead4387ce714a8c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/添加和编辑页面-制作中/u50.png"}},
{
                  "id":"d66272c46a314ce697d42b3a7270ded2",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":30,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"21bfa49f917e4657b060b5b179be95fc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":30,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3f23ce765b484208bbac22cb8b3c437c",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":33},
                    "size":{
                      "width":15,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ba0757444af548079e0143731d60d334",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":33},
                        "size":{
                          "width":15,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/添加和编辑页面-制作中/u54.png"}},
{
                  "id":"ca2589c8689b4ad88bb587a9a3d08c91",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":55,
                      "y":33},
                    "size":{
                      "width":115,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f5343779b1c241f5abdb19adb897e6d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":55,
                          "y":33},
                        "size":{
                          "width":115,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5c437203cc7348afaa964d87f5c91632",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":56},
                    "size":{
                      "width":15,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f3414f8549304c038de666d94ef834ed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":56},
                        "size":{
                          "width":15,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/添加和编辑页面-制作中/u54.png"}},
{
                  "id":"4cbcd1cd9a6a43e5a20278b5e23f13e4",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":55,
                      "y":56},
                    "size":{
                      "width":115,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"97786b3c76a74969b05d32f7c07a5a1c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":55,
                          "y":56},
                        "size":{
                          "width":115,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4fb16efab61e43399bc3ab83e4a4d0eb",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":78},
                    "size":{
                      "width":15,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"019f7234020c4d73a0400f2f34057f5a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":78},
                        "size":{
                          "width":15,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/添加和编辑页面-制作中/u54.png"}},
{
                  "id":"1fbd932e81d7430d9b548f27d95ab6cc",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":55,
                      "y":78},
                    "size":{
                      "width":115,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"28540170bb3a4bc1a8067315612d3ff8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":55,
                          "y":78},
                        "size":{
                          "width":115,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c03b09e9ef254047acd561833b5dc20c",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":104},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"faed0c3ea5e14617beb6fa008ed6c3d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":104},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/添加和编辑页面-制作中/u50.png"}},
{
                  "id":"84eba4c69c2c45c9a90715c6fcc871d2",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":30,
                      "y":103},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bf57f94fdd73420bb6b21958d77ecf81",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":30,
                          "y":103},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3272f61ab8444d52a70c9103dfbddf66",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":136},
                    "size":{
                      "width":15,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"791590dd69864dc3bbe309f5bc92db9d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":136},
                        "size":{
                          "width":15,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/添加和编辑页面-制作中/u54.png"}},
{
                  "id":"ab05fb41f7c9489ca8410ab967f0c34f",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":55,
                      "y":136},
                    "size":{
                      "width":115,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7bdad937f46e40f4953b5ad930cc2de7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":55,
                          "y":136},
                        "size":{
                          "width":115,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f1aef683b32140d1b6f5d2ad1375fbd8",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":159},
                    "size":{
                      "width":15,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"94a2b71aa19c48d39c5edce155e52378",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":159},
                        "size":{
                          "width":15,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/添加和编辑页面-制作中/u54.png"}},
{
                  "id":"796bea21ebe34d559712e20b6afba4cb",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":55,
                      "y":159},
                    "size":{
                      "width":115,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0bd9223b62884fddbcfe6e537790cd4d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":55,
                          "y":159},
                        "size":{
                          "width":115,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"84981e8bd3a64d31a056571fbc210090",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":181},
                    "size":{
                      "width":15,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"041dfd8a84634b3db85c0900c8a0df99",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":181},
                        "size":{
                          "width":15,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/添加和编辑页面-制作中/u54.png"}},
{
                  "id":"161fa89eafb0461eaa4080d1344da884",
                  "label":"",
                  "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":55,
                      "y":181},
                    "size":{
                      "width":115,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"05240a13dc884472b06165bb8975c266",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"595f49c047a947c6aabbf64300d20a46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":55,
                          "y":181},
                        "size":{
                          "width":115,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "72daeef571694b33909bad53571b8a5e":{
      "scriptId":"u0"},
    "3dfd71e9027f443fb8feaca977a9eaa1":{
      "scriptId":"u1"},
    "afb49f385e76407f855ee12c1f87a283":{
      "scriptId":"u2"},
    "e670dd0e64ca41509de975a418f380b4":{
      "scriptId":"u3"},
    "71c022e5b89143ec9451d6ad713c622e":{
      "scriptId":"u4"},
    "9b926ac0fd074df18916060fd0ca6572":{
      "scriptId":"u5"},
    "a49ee78bcfb844128758324ede9b5af2":{
      "scriptId":"u6"},
    "f357caeee43c4639b2e141bc230c0198":{
      "scriptId":"u7"},
    "014227e913744deaac2ac125aded7300":{
      "scriptId":"u8"},
    "88ee76e3581a4e798dd63993bf894a3c":{
      "scriptId":"u9"},
    "394a927a63c341ebbaae4e34e82ed9ee":{
      "scriptId":"u10"},
    "bf41ecd463a74dc5b9dd6cbc8b94d43b":{
      "scriptId":"u11"},
    "b4872c5e1ffb4eb78657da6671b9040a":{
      "scriptId":"u12"},
    "83a467bfc9124443a2bc09019cc4908c":{
      "scriptId":"u13"},
    "3f267c2a2b0d42d7993d1a526be93b48":{
      "scriptId":"u14"},
    "f0aa7b278a8d4cf3ba84c764e5188a01":{
      "scriptId":"u15"},
    "84963d53dfdb40c798780105e4ee5220":{
      "scriptId":"u16"},
    "c46b7043c85444038d41b2db389869f7":{
      "scriptId":"u17"},
    "9fbc09314ec247e7af343ed0fb1c3e79":{
      "scriptId":"u18"},
    "c2a58b991bf54f16a38e8ab8e3c317da":{
      "scriptId":"u19"},
    "09373a3a164245a7ab7aac6a6546206a":{
      "scriptId":"u20"},
    "14f5011466f54e64a0c86893014e5e0f":{
      "scriptId":"u21"},
    "95d95df8cd2043dcb9b509351f2961c0":{
      "scriptId":"u22"},
    "3b0b6f351c8d4a3a8107b102dc68d713":{
      "scriptId":"u23"},
    "767a5d912ddf47ab8e665f803d550c09":{
      "scriptId":"u24"},
    "f6d7d2e912954b11b0a241642e5fa95c":{
      "scriptId":"u25"},
    "d3fdd2174b744eceb587c5ee953ef60e":{
      "scriptId":"u26"},
    "137e3373733c4234b3b6a0a44ad3ad2e":{
      "scriptId":"u27"},
    "163e6bd6561444cc8aa5d1955902302f":{
      "scriptId":"u28"},
    "44c2f167bd814b2cb982ea487d5041dd":{
      "scriptId":"u29"},
    "e44e3b3f26794e04b47d36ff91d5756e":{
      "scriptId":"u30"},
    "39699ba83a4241e480a6bf907fc407b7":{
      "scriptId":"u31"},
    "fcfa01d142ba457393efe809a177e82a":{
      "scriptId":"u32"},
    "52e216144c0b4f178e922391da5e5922":{
      "scriptId":"u33"},
    "2fefb5cd44c840d69b14b561119e50cf":{
      "scriptId":"u34"},
    "b7e5d2640e494e96982c346cc102ae37":{
      "scriptId":"u35"},
    "2d56e9315c5e42d388041b74905d6671":{
      "scriptId":"u36"},
    "5cb43308b44f47ec84e62ff62bdf8f17":{
      "scriptId":"u37"},
    "7936f90de4d748d9bca2a70a1bd3655b":{
      "scriptId":"u38"},
    "21d0615eefd8483a8fa62467e44ddabf":{
      "scriptId":"u39"},
    "157e7a25640a4d309443c5f885e619aa":{
      "scriptId":"u40"},
    "2b7bf5627732491a976de29373899e13":{
      "scriptId":"u41"},
    "78e1e3ef0998496daa0c43c92e7c638a":{
      "scriptId":"u42"},
    "4ebdac9f92014e44b116416af14fa418":{
      "scriptId":"u43"},
    "65706282ad2d43e6a68ec3a9193119e3":{
      "scriptId":"u44"},
    "29b373a103c44e2cb178c26887cb0edb":{
      "scriptId":"u45"},
    "e3d7004e44784014ba36e0f5e194bcb5":{
      "scriptId":"u46"},
    "fcc3fa864aae4b429cd9177976a86653":{
      "scriptId":"u47"},
    "14bd6b1dae054c1fac8213b6819d0956":{
      "scriptId":"u48"},
    "595f49c047a947c6aabbf64300d20a46":{
      "scriptId":"u49"},
    "82ab0eb6d57e4ecc91065e4b88a0b1f9":{
      "scriptId":"u50"},
    "6848a7717da24f928ead4387ce714a8c":{
      "scriptId":"u51"},
    "d66272c46a314ce697d42b3a7270ded2":{
      "scriptId":"u52"},
    "21bfa49f917e4657b060b5b179be95fc":{
      "scriptId":"u53"},
    "3f23ce765b484208bbac22cb8b3c437c":{
      "scriptId":"u54"},
    "ba0757444af548079e0143731d60d334":{
      "scriptId":"u55"},
    "ca2589c8689b4ad88bb587a9a3d08c91":{
      "scriptId":"u56"},
    "f5343779b1c241f5abdb19adb897e6d5":{
      "scriptId":"u57"},
    "5c437203cc7348afaa964d87f5c91632":{
      "scriptId":"u58"},
    "f3414f8549304c038de666d94ef834ed":{
      "scriptId":"u59"},
    "4cbcd1cd9a6a43e5a20278b5e23f13e4":{
      "scriptId":"u60"},
    "97786b3c76a74969b05d32f7c07a5a1c":{
      "scriptId":"u61"},
    "4fb16efab61e43399bc3ab83e4a4d0eb":{
      "scriptId":"u62"},
    "019f7234020c4d73a0400f2f34057f5a":{
      "scriptId":"u63"},
    "1fbd932e81d7430d9b548f27d95ab6cc":{
      "scriptId":"u64"},
    "28540170bb3a4bc1a8067315612d3ff8":{
      "scriptId":"u65"},
    "c03b09e9ef254047acd561833b5dc20c":{
      "scriptId":"u66"},
    "faed0c3ea5e14617beb6fa008ed6c3d8":{
      "scriptId":"u67"},
    "84eba4c69c2c45c9a90715c6fcc871d2":{
      "scriptId":"u68"},
    "bf57f94fdd73420bb6b21958d77ecf81":{
      "scriptId":"u69"},
    "3272f61ab8444d52a70c9103dfbddf66":{
      "scriptId":"u70"},
    "791590dd69864dc3bbe309f5bc92db9d":{
      "scriptId":"u71"},
    "ab05fb41f7c9489ca8410ab967f0c34f":{
      "scriptId":"u72"},
    "7bdad937f46e40f4953b5ad930cc2de7":{
      "scriptId":"u73"},
    "f1aef683b32140d1b6f5d2ad1375fbd8":{
      "scriptId":"u74"},
    "94a2b71aa19c48d39c5edce155e52378":{
      "scriptId":"u75"},
    "796bea21ebe34d559712e20b6afba4cb":{
      "scriptId":"u76"},
    "0bd9223b62884fddbcfe6e537790cd4d":{
      "scriptId":"u77"},
    "84981e8bd3a64d31a056571fbc210090":{
      "scriptId":"u78"},
    "041dfd8a84634b3db85c0900c8a0df99":{
      "scriptId":"u79"},
    "161fa89eafb0461eaa4080d1344da884":{
      "scriptId":"u80"},
    "05240a13dc884472b06165bb8975c266":{
      "scriptId":"u81"}}});