$axure.loadCurrentPage({
  "url":"分期流程介绍页面_1.html",
  "generationDate":new Date(1439287134930.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e9b61d0db9f94fbcabf042305ae410b4",
    "type":"Axure:Page",
    "name":"分期流程介绍页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d468c3f3de2b49f8a3d470e0a3a8898b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":30},
            "size":{
              "width":1220,
              "height":3480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a218240d08e4c9d8372d9495cd33310",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":30},
                "size":{
                  "width":1220,
                  "height":3480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/尊享家分期/u0.png"}},
{
          "id":"d81e7fcb511c4ae4b6ef6ba2311b4e01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":110},
            "size":{
              "width":220,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87271c3c47f143508a19f7193f14819f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":110},
                "size":{
                  "width":220,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u2.png"}},
{
          "id":"6b377387e82a45299846372217016f06",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":1220,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页-已登录/u4_line.png"}},
{
          "id":"bf7d6d8a51e346eea1ff2fa44e2f2bf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":380,
              "y":113},
            "size":{
              "width":60,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86ed03b6db6b477b9f6be29698d37cad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":380,
                  "y":113},
                "size":{
                  "width":60,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u5.png"}},
{
          "id":"94e1f2f42fa245c3ad6c3d1a2b38cb54",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1045,
              "y":110},
            "size":{
              "width":176,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cacda086803340de9b5c7a5a858f7433",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1045,
                  "y":110},
                "size":{
                  "width":176,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u7.png"}},
{
          "id":"7a5ea2ae48634366baf18ce034b4e35e",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":41},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5018bf51267d4bddaec2d026337e52e6",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"db64972d20f748e781c9c3c34626069d",
                  "label":"",
                  "parentDynamicPanel":"7a5ea2ae48634366baf18ce034b4e35e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF009900,
                          "opacity":1}}},
                    "size":{
                      "width":132,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ed28d4acbaf84525be742823b2ee601f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5ea2ae48634366baf18ce034b4e35e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF009900,
                              "opacity":1}}},
                        "size":{
                          "width":132,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"9432cdbdad354a6a83b8e385da480103",
                  "label":"",
                  "parentDynamicPanel":"7a5ea2ae48634366baf18ce034b4e35e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF009900,
                          "opacity":1}}},
                    "location":{
                      "x":128,
                      "y":0},
                    "size":{
                      "width":62,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a1f24b063e54c9bb7e6c2fe5c848b98",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5ea2ae48634366baf18ce034b4e35e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF009900,
                              "opacity":1}}},
                        "location":{
                          "x":128,
                          "y":0},
                        "size":{
                          "width":62,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"fda3d72176bd4a39a9877c40a8cd197a",
                  "label":"",
                  "parentDynamicPanel":"7a5ea2ae48634366baf18ce034b4e35e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF009900,
                          "opacity":1}}},
                    "location":{
                      "x":197,
                      "y":0},
                    "size":{
                      "width":62,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"79293508cff64b11b5cd4ef8a7adbcb8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5ea2ae48634366baf18ce034b4e35e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF009900,
                              "opacity":1}}},
                        "location":{
                          "x":197,
                          "y":0},
                        "size":{
                          "width":62,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"b83a42904b794a18b4000daf3756d65a",
                  "label":"",
                  "parentDynamicPanel":"7a5ea2ae48634366baf18ce034b4e35e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF009900,
                          "opacity":1}}},
                    "location":{
                      "x":270,
                      "y":0},
                    "size":{
                      "width":67,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd8bd482003949e2a099c4495121c6f2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5ea2ae48634366baf18ce034b4e35e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF009900,
                              "opacity":1}}},
                        "location":{
                          "x":270,
                          "y":0},
                        "size":{
                          "width":67,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"2eb45a8082b043abb6c9869dcfcff7e3",
                  "label":"",
                  "parentDynamicPanel":"7a5ea2ae48634366baf18ce034b4e35e",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":183,
                      "y":0},
                    "size":{
                      "width":11,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1cd5d2d7c37b41d583539119263d1b51",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5ea2ae48634366baf18ce034b4e35e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":183,
                          "y":0},
                        "size":{
                          "width":11,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页-已登录/u18.png"}},
{
                  "id":"bc8a61c12282452f970b5b3707c17bf9",
                  "label":"",
                  "parentDynamicPanel":"7a5ea2ae48634366baf18ce034b4e35e",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":259,
                      "y":0},
                    "size":{
                      "width":11,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4580673afbd04a5cb4666971d9e606a7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a5ea2ae48634366baf18ce034b4e35e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":259,
                          "y":0},
                        "size":{
                          "width":11,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页-已登录/u18.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"dd80a8d683774540a7ae9a9c03d70e6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":526,
              "y":131},
            "size":{
              "width":52,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF84C225}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d338dcc35945448da3dee8a7dc70c543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":526,
                  "y":131},
                "size":{
                  "width":52,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF84C225}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba8e9644946a4ff3bf4637e60987660f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1}}},
            "location":{
              "x":606,
              "y":131},
            "size":{
              "width":110,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c39ca7f4e4849c5937531fe17446ca3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF84C225,
                      "opacity":1}}},
                "location":{
                  "x":606,
                  "y":131},
                "size":{
                  "width":110,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"98ff04d391f14b849bad1fe3411b3b2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF84C225,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1}}},
            "location":{
              "x":742,
              "y":131},
            "size":{
              "width":110,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"815efbc8ddc04033b8d704232b7bc5a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF84C225,
                      "opacity":1}}},
                "location":{
                  "x":742,
                  "y":131},
                "size":{
                  "width":110,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"a3adbeb6285845099b8f93985279ce6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1}}},
            "location":{
              "x":870,
              "y":131},
            "size":{
              "width":110,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69f6012b398d4b29834d97b1c8a2a941",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF84C225,
                      "opacity":1}}},
                "location":{
                  "x":870,
                  "y":131},
                "size":{
                  "width":110,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"935c692cbfe244baaebf53dac9493d5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":390,
              "y":153},
            "size":{
              "width":70,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f83d107b23424742bcfa4e6e9338860c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":390,
                  "y":153},
                "size":{
                  "width":70,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 城市",
                      "objectsToFades":[{
                          "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-已登录/u81.png"}},
{
          "id":"afd0c01586984e6b8cc51e35ed86f182",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":742,
              "y":165},
            "size":{
              "width":110,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF84C225}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/尊享家分期/u32_line.png"}},
{
          "id":"5483537494524fdbabe43df6d6b2ccee",
          "label":"城市",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":390,
              "y":173},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"a31956f2805d4d99aff98d12f26e0307",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9bba2a11a91641f18241054c7ac39c32",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":500,
                      "height":130},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d349bfae23c947268f1d0d6e7c707a26",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":500,
                          "height":130},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页-已登录/u45.png"}},
{
                  "id":"8cdfd27ee1ff4f4da6f279c97ff96feb",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":19,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0ede61a3860546a1a7bab2e020d96380",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":19,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a75a210e922843f4873c923462cff98c",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":78,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"39d1d4e16a654fb8a153b5f3d4099a2a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":78,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2be135a8e78f4eeb94f426c1fa82b043",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":142,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"905bd9a2e56841a8a61d88a71dc7a4fc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":142,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"18e0417b428d47509ee5abacadd3db96",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":203,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3c64d88aab2544ae8b7d9c59b501024e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":203,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5593bbf78bd6427c989ffd59abd0bf60",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":262,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ba3c226d126b4f9083ebe00178458e9c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":262,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3dc7521fed824dddb2f8e3d57bc8d3a4",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":323,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ceee9d9256e4d3c8df6e78030781114",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":323,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"055953ae23f64f48bdc1533366dd0640",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":384,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"96d63cea5f654fc1a55d9017a129a39b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":384,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7717368c94a94ef0990e8e6db94e421a",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":445,
                      "y":26},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"44401955f1854e08a2d807e0c35b0d33",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":445,
                          "y":26},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4ddb2f818a7641c681cd7f1e99f96483",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":19,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ea5f5a189dbd445e87fdf4ec8d9cd93c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":19,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b943cca0f73641a88587c1e88b79fde9",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":78,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"83aba5266fb34b43972664d4bf297d0d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":78,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9b656d3ba5ff424fb8974b98bcb6adef",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":142,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"edd6086ad42a46079ddf80cbeff12fb3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":142,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2fe6c4850b2d421cb18985317d88b6a8",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":203,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e10fbcdb6b54b82a0c254051736e27e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":203,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7d03df9cbc6f4b65aba34be5ef46eeba",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":262,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ff99e224641496eb214f4537dd8c164",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":262,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3c6cf6a9d089448f976fe4d226c6e86c",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":323,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"154f3b4a8dd742a6a774e5975daf2b9b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":323,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b8c78d194b424ae288c5f637b535be84",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":384,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8e0f22e68724a96bd33c438496f5148",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":384,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dc6ff075828b47358af507905c278516",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":445,
                      "y":60},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"060dc04234ff46d7a55088cfda74423b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":445,
                          "y":60},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2d7541de5b354592964ad48427565d90",
                  "label":"",
                  "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":19,
                      "y":94},
                    "size":{
                      "width":51,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"50755f87e3c44129a496faa42bd0409e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5483537494524fdbabe43df6d6b2ccee",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":19,
                          "y":94},
                        "size":{
                          "width":51,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 城市",
                              "objectsToFades":[{
                                  "objectPath":["5483537494524fdbabe43df6d6b2ccee"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "d468c3f3de2b49f8a3d470e0a3a8898b":{
      "scriptId":"u0"},
    "6a218240d08e4c9d8372d9495cd33310":{
      "scriptId":"u1"},
    "d81e7fcb511c4ae4b6ef6ba2311b4e01":{
      "scriptId":"u2"},
    "87271c3c47f143508a19f7193f14819f":{
      "scriptId":"u3"},
    "6b377387e82a45299846372217016f06":{
      "scriptId":"u4"},
    "bf7d6d8a51e346eea1ff2fa44e2f2bf9":{
      "scriptId":"u5"},
    "86ed03b6db6b477b9f6be29698d37cad":{
      "scriptId":"u6"},
    "94e1f2f42fa245c3ad6c3d1a2b38cb54":{
      "scriptId":"u7"},
    "cacda086803340de9b5c7a5a858f7433":{
      "scriptId":"u8"},
    "7a5ea2ae48634366baf18ce034b4e35e":{
      "scriptId":"u9"},
    "db64972d20f748e781c9c3c34626069d":{
      "scriptId":"u10"},
    "ed28d4acbaf84525be742823b2ee601f":{
      "scriptId":"u11"},
    "9432cdbdad354a6a83b8e385da480103":{
      "scriptId":"u12"},
    "9a1f24b063e54c9bb7e6c2fe5c848b98":{
      "scriptId":"u13"},
    "fda3d72176bd4a39a9877c40a8cd197a":{
      "scriptId":"u14"},
    "79293508cff64b11b5cd4ef8a7adbcb8":{
      "scriptId":"u15"},
    "b83a42904b794a18b4000daf3756d65a":{
      "scriptId":"u16"},
    "cd8bd482003949e2a099c4495121c6f2":{
      "scriptId":"u17"},
    "2eb45a8082b043abb6c9869dcfcff7e3":{
      "scriptId":"u18"},
    "1cd5d2d7c37b41d583539119263d1b51":{
      "scriptId":"u19"},
    "bc8a61c12282452f970b5b3707c17bf9":{
      "scriptId":"u20"},
    "4580673afbd04a5cb4666971d9e606a7":{
      "scriptId":"u21"},
    "dd80a8d683774540a7ae9a9c03d70e6e":{
      "scriptId":"u22"},
    "d338dcc35945448da3dee8a7dc70c543":{
      "scriptId":"u23"},
    "ba8e9644946a4ff3bf4637e60987660f":{
      "scriptId":"u24"},
    "6c39ca7f4e4849c5937531fe17446ca3":{
      "scriptId":"u25"},
    "98ff04d391f14b849bad1fe3411b3b2f":{
      "scriptId":"u26"},
    "815efbc8ddc04033b8d704232b7bc5a3":{
      "scriptId":"u27"},
    "a3adbeb6285845099b8f93985279ce6b":{
      "scriptId":"u28"},
    "69f6012b398d4b29834d97b1c8a2a941":{
      "scriptId":"u29"},
    "935c692cbfe244baaebf53dac9493d5d":{
      "scriptId":"u30"},
    "f83d107b23424742bcfa4e6e9338860c":{
      "scriptId":"u31"},
    "afd0c01586984e6b8cc51e35ed86f182":{
      "scriptId":"u32"},
    "5483537494524fdbabe43df6d6b2ccee":{
      "scriptId":"u33"},
    "9bba2a11a91641f18241054c7ac39c32":{
      "scriptId":"u34"},
    "d349bfae23c947268f1d0d6e7c707a26":{
      "scriptId":"u35"},
    "8cdfd27ee1ff4f4da6f279c97ff96feb":{
      "scriptId":"u36"},
    "0ede61a3860546a1a7bab2e020d96380":{
      "scriptId":"u37"},
    "a75a210e922843f4873c923462cff98c":{
      "scriptId":"u38"},
    "39d1d4e16a654fb8a153b5f3d4099a2a":{
      "scriptId":"u39"},
    "2be135a8e78f4eeb94f426c1fa82b043":{
      "scriptId":"u40"},
    "905bd9a2e56841a8a61d88a71dc7a4fc":{
      "scriptId":"u41"},
    "18e0417b428d47509ee5abacadd3db96":{
      "scriptId":"u42"},
    "3c64d88aab2544ae8b7d9c59b501024e":{
      "scriptId":"u43"},
    "5593bbf78bd6427c989ffd59abd0bf60":{
      "scriptId":"u44"},
    "ba3c226d126b4f9083ebe00178458e9c":{
      "scriptId":"u45"},
    "3dc7521fed824dddb2f8e3d57bc8d3a4":{
      "scriptId":"u46"},
    "6ceee9d9256e4d3c8df6e78030781114":{
      "scriptId":"u47"},
    "055953ae23f64f48bdc1533366dd0640":{
      "scriptId":"u48"},
    "96d63cea5f654fc1a55d9017a129a39b":{
      "scriptId":"u49"},
    "7717368c94a94ef0990e8e6db94e421a":{
      "scriptId":"u50"},
    "44401955f1854e08a2d807e0c35b0d33":{
      "scriptId":"u51"},
    "4ddb2f818a7641c681cd7f1e99f96483":{
      "scriptId":"u52"},
    "ea5f5a189dbd445e87fdf4ec8d9cd93c":{
      "scriptId":"u53"},
    "b943cca0f73641a88587c1e88b79fde9":{
      "scriptId":"u54"},
    "83aba5266fb34b43972664d4bf297d0d":{
      "scriptId":"u55"},
    "9b656d3ba5ff424fb8974b98bcb6adef":{
      "scriptId":"u56"},
    "edd6086ad42a46079ddf80cbeff12fb3":{
      "scriptId":"u57"},
    "2fe6c4850b2d421cb18985317d88b6a8":{
      "scriptId":"u58"},
    "7e10fbcdb6b54b82a0c254051736e27e":{
      "scriptId":"u59"},
    "7d03df9cbc6f4b65aba34be5ef46eeba":{
      "scriptId":"u60"},
    "2ff99e224641496eb214f4537dd8c164":{
      "scriptId":"u61"},
    "3c6cf6a9d089448f976fe4d226c6e86c":{
      "scriptId":"u62"},
    "154f3b4a8dd742a6a774e5975daf2b9b":{
      "scriptId":"u63"},
    "b8c78d194b424ae288c5f637b535be84":{
      "scriptId":"u64"},
    "a8e0f22e68724a96bd33c438496f5148":{
      "scriptId":"u65"},
    "dc6ff075828b47358af507905c278516":{
      "scriptId":"u66"},
    "060dc04234ff46d7a55088cfda74423b":{
      "scriptId":"u67"},
    "2d7541de5b354592964ad48427565d90":{
      "scriptId":"u68"},
    "50755f87e3c44129a496faa42bd0409e":{
      "scriptId":"u69"}}});