$axure.loadCurrentPage({
  "url":"悦享家.html",
  "generationDate":new Date(1440075583059.52),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b2eaa7d199fb4ece8d84b2eff3a9cc2b",
    "type":"Axure:Page",
    "name":"悦享家",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"59daf82b17a74b76ad26c72fd82e80b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":30},
            "size":{
              "width":1220,
              "height":1800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29740cd3b8d347ccbf8d31f9de94e4f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":30},
                "size":{
                  "width":1220,
                  "height":1800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/悦享家/u0.png"}},
{
          "id":"54483833b51948a1be0cc9fc87ece804",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":110},
            "size":{
              "width":220,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a8887efce194694bcdc457fc1dc11c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":110},
                "size":{
                  "width":220,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u2.png"}},
{
          "id":"e287f683b8c64679ada6a394acda72c3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":1220,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页-已登录/u4_line.png"}},
{
          "id":"edef5fb6e7404d04bdf1efd7cb391235",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":951,
              "y":41},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d045e6acfc14f2eb3db01c0d0ee8704",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":951,
                  "y":41},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cd998f353e54b17ad447a5338aeee28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":1001,
              "y":41},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61934b3aec8a434380ec087b404c6454",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":1001,
                  "y":41},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eeb3368195214d2f95a40b4cb7c3be31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1049,
              "y":110},
            "size":{
              "width":176,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2a105c7b18e4bc583108509d8c0ba1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1049,
                  "y":110},
                "size":{
                  "width":176,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u7.png"}},
{
          "id":"a14ca68b2a8c408585f092288288e451",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE9E9E9},
            "location":{
              "x":59,
              "y":1608},
            "size":{
              "width":1219,
              "height":220},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE9E9E9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73009ca18f4c4966a749d8a414398fe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE9E9E9},
                "location":{
                  "x":59,
                  "y":1608},
                "size":{
                  "width":1219,
                  "height":220},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE9E9E9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u45.png"}},
{
          "id":"4d80e888dd6c4e8d8e13baa68285f6d5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":1634},
            "size":{
              "width":1084,
              "height":156}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cc99b0a8f814e119cc08e6d12653812",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":143,
                  "y":1634},
                "size":{
                  "width":1084,
                  "height":156}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u47.png"}},
{
          "id":"2af71e59485641f9aee52e077a581268",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":1067,
              "y":41},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a01872a5b7e140c39fcb00fde7b3ce3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":1067,
                  "y":41},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"7f64c9e8441e4279b9bd11582b8a0f1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":1140,
              "y":41},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bfbc5c453554fe09f7e0cb4da35af0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":1140,
                  "y":41},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"74efa3731eec4c9c968b87971556759c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1129,
              "y":41},
            "size":{
              "width":11,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b3c5766bad24397a434ddcd32ef20ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1129,
                  "y":41},
                "size":{
                  "width":11,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u18.png"}},
{
          "id":"ec399e90d9bd4ce59a8a0bf3fd9949c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1056,
              "y":41},
            "size":{
              "width":11,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5261bfe555934edab96aea6517c020e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1056,
                  "y":41},
                "size":{
                  "width":11,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u18.png"}},
{
          "id":"198ae88fc1fc4d6b82cc90282f59b6f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1002,
              "y":41},
            "size":{
              "width":11,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d00efd0e5fa946da991907358a23f4c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1002,
                  "y":41},
                "size":{
                  "width":11,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u18.png"}},
{
          "id":"4f12f8cd416b4777aeb37af28fd4bf0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":380,
              "y":113},
            "size":{
              "width":60,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"497c6ded683f49e092b22f8c8b31eb34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":380,
                  "y":113},
                "size":{
                  "width":60,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u5.png"}},
{
          "id":"d5d1d962f2964d25ab79a753a3b64fee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":526,
              "y":131},
            "size":{
              "width":52,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF84C225}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a89a30a0e8dc47a182d83a57eb0dc927",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":526,
                  "y":131},
                "size":{
                  "width":52,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF84C225}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ca3d0f9001f4221819119d7f7f4c4f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1}}},
            "location":{
              "x":606,
              "y":131},
            "size":{
              "width":110,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd73bc210ee245a590848b44218f4a0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF84C225,
                      "opacity":1}}},
                "location":{
                  "x":606,
                  "y":131},
                "size":{
                  "width":110,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"278650ebfbe941f3bc5205c2f0ac5bff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1}}},
            "location":{
              "x":870,
              "y":131},
            "size":{
              "width":110,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"598991df70774962adf5bdc9bace8d89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF84C225,
                      "opacity":1}}},
                "location":{
                  "x":870,
                  "y":131},
                "size":{
                  "width":110,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"cf93301b01b54deb9bb925ed08686e30",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":748.5,
              "y":165},
            "size":{
              "width":97,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF84C225}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/家装分期/u35_line.png"}},
{
          "id":"6b0e1143ce5a4cefab1c52f70c963721",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF84C225,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1}}},
            "location":{
              "x":742,
              "y":131},
            "size":{
              "width":110,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edafceaaea584f74a4117e6a356ff671",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF84C225,
                      "opacity":1}}},
                "location":{
                  "x":742,
                  "y":131},
                "size":{
                  "width":110,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏元件",
                      "objectsToFades":[]}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"9986420d444542cda40bd468ebbbbf26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":217},
            "size":{
              "width":1219,
              "height":531}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c2131a33c9e45e99c5512d3772da716",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":217},
                "size":{
                  "width":1219,
                  "height":531}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/悦享家/u36.png"}},
{
          "id":"f64fd7a38111414c9ab1ca0c4bce7322",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":773},
            "size":{
              "width":1105,
              "height":227}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03656109d39e495abbd90bd535af9e1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":773},
                "size":{
                  "width":1105,
                  "height":227}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/悦享家/u38.png"}},
{
          "id":"f55d148eae284c1c905d8d379531af42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF8B6540},
            "location":{
              "x":360,
              "y":680},
            "size":{
              "width":260,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF764D2B}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e157935e9474ae5bc6494658ba12bd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF8B6540},
                "location":{
                  "x":360,
                  "y":680},
                "size":{
                  "width":260,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF764D2B}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/悦享家/u40.png"}},
{
          "id":"4cccf7e545ca4877ad0550f73b10f95b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4F9326},
            "location":{
              "x":177,
              "y":627},
            "size":{
              "width":160,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4E9225}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12e741ea09ce46a3937acda6aa492f8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4F9326},
                "location":{
                  "x":177,
                  "y":627},
                "size":{
                  "width":160,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4E9225}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/悦享家/u42.png"}},
{
          "id":"726f610c41a744a8a6cd44ebdc1f28c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF4F9326},
            "location":{
              "x":440,
              "y":627},
            "size":{
              "width":160,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4E9225}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"141a97ee881243689b1838f14c1ca3a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4F9326},
                "location":{
                  "x":440,
                  "y":627},
                "size":{
                  "width":160,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4E9225}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/悦享家/u42.png"}},
{
          "id":"7cb02b830f884ed88665e76e6a038eb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFCF9F4},
            "location":{
              "x":180,
              "y":683},
            "size":{
              "width":160,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFDFAF3}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ab4d29cc8f74f2589bd412fc038547e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFCF9F4},
                "location":{
                  "x":180,
                  "y":683},
                "size":{
                  "width":160,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFDFAF3}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/悦享家/u46.png"}},
{
          "id":"1c70f4f5e03544bc959e02d229e74749",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":1010},
            "size":{
              "width":1105,
              "height":589}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98602f537cc24cb3a3fc5cf31cea84e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":1010},
                "size":{
                  "width":1105,
                  "height":589}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/悦享家/u48.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "59daf82b17a74b76ad26c72fd82e80b8":{
      "scriptId":"u0"},
    "29740cd3b8d347ccbf8d31f9de94e4f3":{
      "scriptId":"u1"},
    "54483833b51948a1be0cc9fc87ece804":{
      "scriptId":"u2"},
    "9a8887efce194694bcdc457fc1dc11c4":{
      "scriptId":"u3"},
    "e287f683b8c64679ada6a394acda72c3":{
      "scriptId":"u4"},
    "edef5fb6e7404d04bdf1efd7cb391235":{
      "scriptId":"u5"},
    "7d045e6acfc14f2eb3db01c0d0ee8704":{
      "scriptId":"u6"},
    "9cd998f353e54b17ad447a5338aeee28":{
      "scriptId":"u7"},
    "61934b3aec8a434380ec087b404c6454":{
      "scriptId":"u8"},
    "eeb3368195214d2f95a40b4cb7c3be31":{
      "scriptId":"u9"},
    "e2a105c7b18e4bc583108509d8c0ba1c":{
      "scriptId":"u10"},
    "a14ca68b2a8c408585f092288288e451":{
      "scriptId":"u11"},
    "73009ca18f4c4966a749d8a414398fe1":{
      "scriptId":"u12"},
    "4d80e888dd6c4e8d8e13baa68285f6d5":{
      "scriptId":"u13"},
    "7cc99b0a8f814e119cc08e6d12653812":{
      "scriptId":"u14"},
    "2af71e59485641f9aee52e077a581268":{
      "scriptId":"u15"},
    "a01872a5b7e140c39fcb00fde7b3ce3b":{
      "scriptId":"u16"},
    "7f64c9e8441e4279b9bd11582b8a0f1f":{
      "scriptId":"u17"},
    "2bfbc5c453554fe09f7e0cb4da35af0a":{
      "scriptId":"u18"},
    "74efa3731eec4c9c968b87971556759c":{
      "scriptId":"u19"},
    "0b3c5766bad24397a434ddcd32ef20ad":{
      "scriptId":"u20"},
    "ec399e90d9bd4ce59a8a0bf3fd9949c0":{
      "scriptId":"u21"},
    "5261bfe555934edab96aea6517c020e4":{
      "scriptId":"u22"},
    "198ae88fc1fc4d6b82cc90282f59b6f0":{
      "scriptId":"u23"},
    "d00efd0e5fa946da991907358a23f4c0":{
      "scriptId":"u24"},
    "4f12f8cd416b4777aeb37af28fd4bf0e":{
      "scriptId":"u25"},
    "497c6ded683f49e092b22f8c8b31eb34":{
      "scriptId":"u26"},
    "d5d1d962f2964d25ab79a753a3b64fee":{
      "scriptId":"u27"},
    "a89a30a0e8dc47a182d83a57eb0dc927":{
      "scriptId":"u28"},
    "2ca3d0f9001f4221819119d7f7f4c4f6":{
      "scriptId":"u29"},
    "cd73bc210ee245a590848b44218f4a0a":{
      "scriptId":"u30"},
    "278650ebfbe941f3bc5205c2f0ac5bff":{
      "scriptId":"u31"},
    "598991df70774962adf5bdc9bace8d89":{
      "scriptId":"u32"},
    "cf93301b01b54deb9bb925ed08686e30":{
      "scriptId":"u33"},
    "6b0e1143ce5a4cefab1c52f70c963721":{
      "scriptId":"u34"},
    "edafceaaea584f74a4117e6a356ff671":{
      "scriptId":"u35"},
    "9986420d444542cda40bd468ebbbbf26":{
      "scriptId":"u36"},
    "3c2131a33c9e45e99c5512d3772da716":{
      "scriptId":"u37"},
    "f64fd7a38111414c9ab1ca0c4bce7322":{
      "scriptId":"u38"},
    "03656109d39e495abbd90bd535af9e1c":{
      "scriptId":"u39"},
    "f55d148eae284c1c905d8d379531af42":{
      "scriptId":"u40"},
    "3e157935e9474ae5bc6494658ba12bd4":{
      "scriptId":"u41"},
    "4cccf7e545ca4877ad0550f73b10f95b":{
      "scriptId":"u42"},
    "12e741ea09ce46a3937acda6aa492f8c":{
      "scriptId":"u43"},
    "726f610c41a744a8a6cd44ebdc1f28c4":{
      "scriptId":"u44"},
    "141a97ee881243689b1838f14c1ca3a9":{
      "scriptId":"u45"},
    "7cb02b830f884ed88665e76e6a038eb8":{
      "scriptId":"u46"},
    "8ab4d29cc8f74f2589bd412fc038547e":{
      "scriptId":"u47"},
    "1c70f4f5e03544bc959e02d229e74749":{
      "scriptId":"u48"},
    "98602f537cc24cb3a3fc5cf31cea84e2":{
      "scriptId":"u49"}}});