$axure.loadCurrentPage({
  "url":"角色管理-角色列表-完成.html",
  "generationDate":new Date(1441157429913.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"54b944dd208d4cf98aa17b93714cf185",
    "type":"Axure:Page",
    "name":"角色管理-角色列表-完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b03c8ae62f6c4c99af95a801bbaeb9ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":1180,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dd5436527544a36afa93695b63fed66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":1180,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u0.png"}},
{
          "id":"5c23eafa8329402394dc449859831978",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":140},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b82bf75fd96845b6bc864c57601247f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":140},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"b91db591d98a430ab022dfd32e447cf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":190},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5de3b4b2da5544a5afe4461859d57197",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":190},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"3b099c3f87b34562a651a4db3a4a7679",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":240},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"565ac72388d94959b4aedc5054c2e85d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":240},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"38c1880e5bdf4f679c99dad4e61412cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":290},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1bf7cbe165c48568cf333e5c226353a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":290},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"bc70b035b7ff4c24a8a1e53c8880caec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":55,
              "y":340},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c63b1ec0d794286a1bfede35db991c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":55,
                  "y":340},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u2.png"}},
{
          "id":"7558f516c35c47a48a9d27a15df5f7ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":390},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fafa2294ca44b83ae09e0672dc4b52e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":390},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"bc182007830349f596fa6ba230583aea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":440},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a907680894ab4a2c8a8fdb7cd256ae3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":440},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"d92e06651b464749a2a191e3469eab8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":490},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5373b5b6993e4f25a9aa1634790fcbfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":490},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"883deefc40a345e59e3633de9b75f511",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":76},
            "size":{
              "width":1180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/预约管理-未下载-完成/u18_line.png"}},
{
          "id":"627b1191e1bf4817b1c893115260e5f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":26},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1504b9d0dfba47598ee9936a51e316cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":26},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba078e759f6145c595a8e2f38a0d6f6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1137,
              "y":26},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb0622f2491c44e9900e41034bf9c0cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1137,
                  "y":26},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2518048e0c0c4a32bd5fce776c5b7129",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":18},
            "size":{
              "width":135,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eddf112628e4e5e8f37b2e597e6ba0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":18},
                "size":{
                  "width":135,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u23.png"}},
{
          "id":"b7711dbf07094cfdb036deee107ad1df",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":33},
            "size":{
              "width":270,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a2c6710d11e434bbb4ade64ef2b7e0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":33},
                "size":{
                  "width":270,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"939990842d444a50b1cfa025baa343d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":52},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3324b13387e4edf908558ace27ba941",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":52},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4466eb511eb54d92b7fd3dcaa6398d45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1147,
              "y":52},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdb473778ddf4230a8701aa20f8fdae3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1147,
                  "y":52},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bc17c2e44e1436db84bc031e6d33c81",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":140},
            "size":{
              "width":950,
              "height":400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a84882136d6449a9e5445a37cb3ffce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":140},
                "size":{
                  "width":950,
                  "height":400}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加和编辑页面-完成/u31.png"}},
{
          "id":"67042df843ab498e8499ecb66e620a98",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":152.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b2c693bbf8514d88a1f2e2d91e777685",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":566,
              "y":152.5},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9783d7efabfe4c1d82161a65c222ef4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":566,
                  "y":152.5},
                "size":{
                  "width":50,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u37.png"}},
{
          "id":"0d8f63f15fc841e58fab751d4bf04f04",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":187},
            "size":{
              "width":652,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5292a7fa0f1948619a3fab2198d0ddc8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"72ae4a83a31349af8449b414803c236f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u44.png"}},
{
              "id":"44f15409888842d8b809106167793822",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":150,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"16f07c19cae04ab4907c881d2b3ca108",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":150,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u54.png"}},
{
              "id":"468f4c54a16d4b4cba199f6063b4eb6a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":77},
                "size":{
                  "width":150,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fa28de9b115544168a0f6143b1a8b6ef",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":77},
                    "size":{
                      "width":150,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u64.png"}},
{
              "id":"964f2838b3ec44a4b3c4adf7ba93bfc5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":150,
                  "y":0},
                "size":{
                  "width":166,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f7f520bae024e8b8c4fd364912aadae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":150,
                      "y":0},
                    "size":{
                      "width":166,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u46.png"}},
{
              "id":"79f741202d964cc3bdd516816a9b1458",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":40},
                "size":{
                  "width":166,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12524b7544ec46f88736120ba0fce849",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":40},
                    "size":{
                      "width":166,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u56.png"}},
{
              "id":"4b54d551824649b8bb9f939f174ffcce",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":77},
                "size":{
                  "width":166,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a73cbcad2c1468e82dda69ce5fe8e4a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":77},
                    "size":{
                      "width":166,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u66.png"}},
{
              "id":"68fd193fc1b84940b8825b9dab56ba24",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":316,
                  "y":0},
                "size":{
                  "width":153,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cadf7eb5be8f4a2982056b225c3c6d9c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":316,
                      "y":0},
                    "size":{
                      "width":153,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u41.png"}},
{
              "id":"ba15c3168e5b4056a1b67686bfae0f29",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":316,
                  "y":40},
                "size":{
                  "width":153,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8bd0215a783d4dd4ad137ff679d36c58",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":316,
                      "y":40},
                    "size":{
                      "width":153,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u49.png"}},
{
              "id":"a323e37bb2e04cfe8e488da48549fbb9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":316,
                  "y":77},
                "size":{
                  "width":153,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8fc041c68fe5491c8dc440b7a1801705",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":316,
                      "y":77},
                    "size":{
                      "width":153,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u57.png"}},
{
              "id":"29f8e916d78d47e7928609b7dce583ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":469,
                  "y":0},
                "size":{
                  "width":183,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a08ac8f5138f43f6a5c0bd04a9099d94",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":469,
                      "y":0},
                    "size":{
                      "width":183,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u43.png"}},
{
              "id":"c6d834c415764ad1a795e534f7648ea3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":469,
                  "y":40},
                "size":{
                  "width":183,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7cb415f446574f3fa76afca4216e7cb7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000CC,
                      "opacity":1},
                    "location":{
                      "x":469,
                      "y":40},
                    "size":{
                      "width":183,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u51.png"}},
{
              "id":"fa504afe9db84d6a88f859a047f7217a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":469,
                  "y":77},
                "size":{
                  "width":183,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"20267325d46f4337af61f06c24d49daa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000CC,
                      "opacity":1},
                    "location":{
                      "x":469,
                      "y":77},
                    "size":{
                      "width":183,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u59.png"}}]},
{
          "id":"e0b0fefb903f46fcbf171b4d5ee68693",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":370},
            "size":{
              "width":560,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ef625f4fe154c5fb4c85f1cab32113c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":370},
                "size":{
                  "width":560,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u101.png"}},
{
          "id":"c7766aa5d6cf4e54b8357e84591bf954",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":104},
            "size":{
              "width":225,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5f3dbf6ff05442f9c46afa015d1daa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":104},
                "size":{
                  "width":225,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8617e6e08e845a68e3b2cd5d71aa819",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":156},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8701bca26b14c17a5cc4a9d507ffcb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":156},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1ee8b69a48f4fa69a04397c7197e5e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":626,
              "y":152},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b736a3937361412e8380b46f1b11049a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":626,
                  "y":152},
                "size":{
                  "width":50,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u37.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b03c8ae62f6c4c99af95a801bbaeb9ff":{
      "scriptId":"u0"},
    "1dd5436527544a36afa93695b63fed66":{
      "scriptId":"u1"},
    "5c23eafa8329402394dc449859831978":{
      "scriptId":"u2"},
    "b82bf75fd96845b6bc864c57601247f2":{
      "scriptId":"u3"},
    "b91db591d98a430ab022dfd32e447cf0":{
      "scriptId":"u4"},
    "5de3b4b2da5544a5afe4461859d57197":{
      "scriptId":"u5"},
    "3b099c3f87b34562a651a4db3a4a7679":{
      "scriptId":"u6"},
    "565ac72388d94959b4aedc5054c2e85d":{
      "scriptId":"u7"},
    "38c1880e5bdf4f679c99dad4e61412cf":{
      "scriptId":"u8"},
    "f1bf7cbe165c48568cf333e5c226353a":{
      "scriptId":"u9"},
    "bc70b035b7ff4c24a8a1e53c8880caec":{
      "scriptId":"u10"},
    "0c63b1ec0d794286a1bfede35db991c1":{
      "scriptId":"u11"},
    "7558f516c35c47a48a9d27a15df5f7ed":{
      "scriptId":"u12"},
    "6fafa2294ca44b83ae09e0672dc4b52e":{
      "scriptId":"u13"},
    "bc182007830349f596fa6ba230583aea":{
      "scriptId":"u14"},
    "a907680894ab4a2c8a8fdb7cd256ae3f":{
      "scriptId":"u15"},
    "d92e06651b464749a2a191e3469eab8e":{
      "scriptId":"u16"},
    "5373b5b6993e4f25a9aa1634790fcbfd":{
      "scriptId":"u17"},
    "883deefc40a345e59e3633de9b75f511":{
      "scriptId":"u18"},
    "627b1191e1bf4817b1c893115260e5f5":{
      "scriptId":"u19"},
    "1504b9d0dfba47598ee9936a51e316cc":{
      "scriptId":"u20"},
    "ba078e759f6145c595a8e2f38a0d6f6f":{
      "scriptId":"u21"},
    "bb0622f2491c44e9900e41034bf9c0cd":{
      "scriptId":"u22"},
    "2518048e0c0c4a32bd5fce776c5b7129":{
      "scriptId":"u23"},
    "9eddf112628e4e5e8f37b2e597e6ba0b":{
      "scriptId":"u24"},
    "b7711dbf07094cfdb036deee107ad1df":{
      "scriptId":"u25"},
    "4a2c6710d11e434bbb4ade64ef2b7e0f":{
      "scriptId":"u26"},
    "939990842d444a50b1cfa025baa343d0":{
      "scriptId":"u27"},
    "f3324b13387e4edf908558ace27ba941":{
      "scriptId":"u28"},
    "4466eb511eb54d92b7fd3dcaa6398d45":{
      "scriptId":"u29"},
    "cdb473778ddf4230a8701aa20f8fdae3":{
      "scriptId":"u30"},
    "4bc17c2e44e1436db84bc031e6d33c81":{
      "scriptId":"u31"},
    "0a84882136d6449a9e5445a37cb3ffce":{
      "scriptId":"u32"},
    "67042df843ab498e8499ecb66e620a98":{
      "scriptId":"u33"},
    "b2c693bbf8514d88a1f2e2d91e777685":{
      "scriptId":"u34"},
    "9783d7efabfe4c1d82161a65c222ef4c":{
      "scriptId":"u35"},
    "0d8f63f15fc841e58fab751d4bf04f04":{
      "scriptId":"u36"},
    "5292a7fa0f1948619a3fab2198d0ddc8":{
      "scriptId":"u37"},
    "72ae4a83a31349af8449b414803c236f":{
      "scriptId":"u38"},
    "964f2838b3ec44a4b3c4adf7ba93bfc5":{
      "scriptId":"u39"},
    "7f7f520bae024e8b8c4fd364912aadae":{
      "scriptId":"u40"},
    "68fd193fc1b84940b8825b9dab56ba24":{
      "scriptId":"u41"},
    "cadf7eb5be8f4a2982056b225c3c6d9c":{
      "scriptId":"u42"},
    "29f8e916d78d47e7928609b7dce583ff":{
      "scriptId":"u43"},
    "a08ac8f5138f43f6a5c0bd04a9099d94":{
      "scriptId":"u44"},
    "44f15409888842d8b809106167793822":{
      "scriptId":"u45"},
    "16f07c19cae04ab4907c881d2b3ca108":{
      "scriptId":"u46"},
    "79f741202d964cc3bdd516816a9b1458":{
      "scriptId":"u47"},
    "12524b7544ec46f88736120ba0fce849":{
      "scriptId":"u48"},
    "ba15c3168e5b4056a1b67686bfae0f29":{
      "scriptId":"u49"},
    "8bd0215a783d4dd4ad137ff679d36c58":{
      "scriptId":"u50"},
    "c6d834c415764ad1a795e534f7648ea3":{
      "scriptId":"u51"},
    "7cb415f446574f3fa76afca4216e7cb7":{
      "scriptId":"u52"},
    "468f4c54a16d4b4cba199f6063b4eb6a":{
      "scriptId":"u53"},
    "fa28de9b115544168a0f6143b1a8b6ef":{
      "scriptId":"u54"},
    "4b54d551824649b8bb9f939f174ffcce":{
      "scriptId":"u55"},
    "3a73cbcad2c1468e82dda69ce5fe8e4a":{
      "scriptId":"u56"},
    "a323e37bb2e04cfe8e488da48549fbb9":{
      "scriptId":"u57"},
    "8fc041c68fe5491c8dc440b7a1801705":{
      "scriptId":"u58"},
    "fa504afe9db84d6a88f859a047f7217a":{
      "scriptId":"u59"},
    "20267325d46f4337af61f06c24d49daa":{
      "scriptId":"u60"},
    "e0b0fefb903f46fcbf171b4d5ee68693":{
      "scriptId":"u61"},
    "7ef625f4fe154c5fb4c85f1cab32113c":{
      "scriptId":"u62"},
    "c7766aa5d6cf4e54b8357e84591bf954":{
      "scriptId":"u63"},
    "b5f3dbf6ff05442f9c46afa015d1daa2":{
      "scriptId":"u64"},
    "e8617e6e08e845a68e3b2cd5d71aa819":{
      "scriptId":"u65"},
    "d8701bca26b14c17a5cc4a9d507ffcb4":{
      "scriptId":"u66"},
    "d1ee8b69a48f4fa69a04397c7197e5e3":{
      "scriptId":"u67"},
    "b736a3937361412e8380b46f1b11049a":{
      "scriptId":"u68"}}});