$axure.loadCurrentPage({
  "url":"换绑手机-第三步修改成功.html",
  "generationDate":new Date(1440075590270.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d882d0c22e34400585a0db8437c8d197",
    "type":"Axure:Page",
    "name":"换绑手机-第三步修改成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"16efe71f694542b28cb5d9e367d0763a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":43},
            "size":{
              "width":110,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1cc588e823344eaa9099ff60eab008d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":43},
                "size":{
                  "width":110,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u24.png"}},
{
          "id":"407798fcea3e4d7e86a6c469951c860a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":315,
              "y":51},
            "size":{
              "width":88,
              "height":43},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08034218dd194f17813a1464b957076a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":315,
                  "y":51},
                "size":{
                  "width":88,
                  "height":43},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u26.png"}},
{
          "id":"d63c9fabf5304de19a4e5c1d381cd133",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1373,
              "y":23},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1D82DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7519b74ee54249a6b759874322312b8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1373,
                  "y":23},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1D82DE}},
              "adaptiveStyles":{
}}]},
{
          "id":"7f2b54e2d8504d4e965624977a93b7e9",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1373,
              "y":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF1D82DE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac45a896450f48e4858de27a957ccbcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1373,
                  "y":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF1D82DE}},
              "adaptiveStyles":{
}}]},
{
          "id":"0a07b2394b1147b38111362319e899fa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":155},
            "size":{
              "width":971,
              "height":286}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94bfe3d4554a426ea87cd050b69e9d78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":155},
                "size":{
                  "width":971,
                  "height":286}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一步-验证手机/u8.png"}},
{
          "id":"37310b19f1ff43feb0cec578d92c376d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":266},
            "size":{
              "width":944,
              "height":175},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06dc58f91e7649dd89ae6f3a5b4ef2f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":266},
                "size":{
                  "width":944,
                  "height":175},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一步-验证手机/u14.png"}},
{
          "id":"fa5e06f1e77948839eef950b2cef6b1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":290},
            "size":{
              "width":932,
              "height":426},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a48fecafb56c470eb18f4b4253445eaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":290},
                "size":{
                  "width":932,
                  "height":426},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第二步-修改密码/u16.png"}},
{
          "id":"ea425168d4ed4721b9999f51afb4cde4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":572,
              "y":330},
            "size":{
              "width":547,
              "height":293}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d0733df4b964e2a88ae2c95cb78b418",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":572,
                  "y":330},
                "size":{
                  "width":547,
                  "height":293}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一步-验证手机/u20.png"}},
{
          "id":"8efd98a4a98646e7b29a4a51cb7b3e46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":808,
              "y":451},
            "size":{
              "width":124,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f45aece0bd54bc991fed217a31d6dd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":808,
                  "y":451},
                "size":{
                  "width":124,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一步-验证手机/u22.png"}},
{
          "id":"688ab95fde3c4147bd9e4561cff938f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":208},
            "size":{
              "width":949,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a34d2844f114501af21e29b65839616",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":312,
                  "y":208},
                "size":{
                  "width":949,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第二步-修改密码/u22.png"}},
{
          "id":"e78588404d74448dbc7a7ecd906f9100",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF8900},
            "location":{
              "x":688,
              "y":218},
            "size":{
              "width":174,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF8900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"455b7400925f4bf18a666ddd781401f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF8900},
                "location":{
                  "x":688,
                  "y":218},
                "size":{
                  "width":174,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF8900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三步-修改成功/u22.png"}},
{
          "id":"6aee509859fc49acaee35522aa35f23d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFDEDEDE},
            "location":{
              "x":364,
              "y":217},
            "size":{
              "width":174,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDEDEDE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b42a6dc3344f462b8ca340151b181a37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDEDEDE},
                "location":{
                  "x":364,
                  "y":217},
                "size":{
                  "width":174,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDEDEDE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一步-验证手机/u12.png"}},
{
          "id":"e88183c9e4044ae099c0a01dc6c1238c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":313},
            "size":{
              "width":659,
              "height":336}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf4513f3cb874092b3d0da8c980daad6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":313},
                "size":{
                  "width":659,
                  "height":336}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第二步-修改密码/u28.png"}},
{
          "id":"65cdf1541b344abd8eb0e126ee970bac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":732,
              "y":475},
            "size":{
              "width":120,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc15c4bec08743658cc1633b4674b489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":732,
                  "y":475},
                "size":{
                  "width":120,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第二步-修改密码/u32.png"}},
{
          "id":"e60b46d0fc964291817a9b81517575b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF333333},
            "location":{
              "x":932,
              "y":216},
            "size":{
              "width":322,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"205292b49ff0404281777b647e1bb8a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":932,
                  "y":216},
                "size":{
                  "width":322,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三步-修改成功/u32.png"}},
{
          "id":"a35032688ed1404a9455a4589aa041fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDEDEDE},
            "location":{
              "x":632,
              "y":216},
            "size":{
              "width":322,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bd8062b19ba4db893d4ce631461a10d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDEDEDE},
                "location":{
                  "x":632,
                  "y":216},
                "size":{
                  "width":322,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三步-修改成功/u34.png"}},
{
          "id":"553d6ba4e8da472cbb4b163eba219443",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDEDEDE},
            "location":{
              "x":320,
              "y":216},
            "size":{
              "width":322,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84dd27518aae41c6b9fa797eb90a7fd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDEDEDE},
                "location":{
                  "x":320,
                  "y":216},
                "size":{
                  "width":322,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三步-修改成功/u34.png"}},
{
          "id":"1ce1cc8926a24d9d94b53fa41a3d2a59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":548,
              "y":426},
            "size":{
              "width":484,
              "height":230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce384dda63d0425b9663a62009efbcdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":548,
                  "y":426},
                "size":{
                  "width":484,
                  "height":230},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第三步-修改成功/u38.png"}},
{
          "id":"1b0e1c3c1e254c69890f788f9dfccb84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文楷体 Bold', '华文楷体'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":310,
              "y":150},
            "size":{
              "width":159,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b99d9992b9d4386a2955ad2f26209f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文楷体 Bold', '华文楷体'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":310,
                  "y":150},
                "size":{
                  "width":159,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一步-验证手机/u26.png"}},
{
          "id":"9e304d82f93b44438e5edead1b22c278",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":317.5,
              "y":156},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"c281df4da8cf4c66aa3250718b006162",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"be47ef09a4864754acd322a0c9c8edcc",
                  "label":"",
                  "parentDynamicPanel":"9e304d82f93b44438e5edead1b22c278",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'楷体 Bold', '楷体'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "horizontalAlignment":"left",
                    "location":{
                      "x":0,
                      "y":2},
                    "size":{
                      "width":170,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2af396a58b35450aa09d23bca1b24705",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9e304d82f93b44438e5edead1b22c278",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'楷体 Bold', '楷体'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "horizontalAlignment":"left",
                        "location":{
                          "x":0,
                          "y":2},
                        "size":{
                          "width":170,
                          "height":36},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/第三步-修改成功/u43.png"}},
{
                  "id":"e438e7a16ebc471cb2a39e204097cb12",
                  "label":"",
                  "parentDynamicPanel":"9e304d82f93b44438e5edead1b22c278",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":2,
                      "y":37},
                    "size":{
                      "width":158,
                      "height":10},
                    "borderWidth":"3",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF333333}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/第一步-验证手机/u32_line.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"b77660216ed4454e831c6bd3fb83e0e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":556,
              "y":335},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2575b814170a4ba2acc68d443fe5bd99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":556,
                  "y":335},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册成功/u20.png"}},
{
          "id":"6d6397badd0d48c29e66e77d9146791e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":468,
              "y":740},
            "size":{
              "width":665,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8123eaa60c040be977312da8be865fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":468,
                  "y":740},
                "size":{
                  "width":665,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u82.png"}},
{
          "id":"2c27e4ee5a2b48efbd3b8087c9ee8953",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":722,
              "y":750},
            "size":{
              "width":60,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28c29d3bc98843ddbf1ea9e89c61e1ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":722,
                  "y":750},
                "size":{
                  "width":60,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册成功/u28.png"}},
{
          "id":"2adcb65dffa8437391978dfcab38f106",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":508,
              "y":780},
            "size":{
              "width":580,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dcec41181624ede9ad3cebee2942be9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":508,
                  "y":780},
                "size":{
                  "width":580,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u96.png"}},
{
          "id":"1f8b7c0e9dbb49b48ed3fa36c0549025",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":292,
              "y":740},
            "size":{
              "width":190,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87ecdf468b034803b22b7fb692aa0fe6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":292,
                  "y":740},
                "size":{
                  "width":190,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u84.png"}},
{
          "id":"0cc7e77cc6de4060932f96bc7eea6cb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":1102,
              "y":740},
            "size":{
              "width":190,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec229d23beaa4c33ae7882e1220f804c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":1102,
                  "y":740},
                "size":{
                  "width":190,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u84.png"}},
{
          "id":"2d4c77901ff144d79fd0f90f3092361c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0EEEF},
            "location":{
              "x":292,
              "y":810},
            "size":{
              "width":1000,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF0EEEF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13f8e05b236f4a9a82befa10ea7d31b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF},
                "location":{
                  "x":292,
                  "y":810},
                "size":{
                  "width":1000,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF0EEEF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u88.png"}},
{
          "id":"88becb3417ac4b27838bfe9ebfa04a2f",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":471,
              "y":747},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"6f83848e8a4f42f7a6a91c74c734ea66",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"79252bde6db949809c8c469963635cef",
                  "label":"",
                  "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF0EEEF},
                    "location":{
                      "x":25,
                      "y":31},
                    "size":{
                      "width":580,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF0EEEF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25aa5a0c2f434086bfcab03411f32ef9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF0EEEF},
                        "location":{
                          "x":25,
                          "y":31},
                        "size":{
                          "width":580,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF0EEEF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/注册/u96.png"}},
{
                  "id":"719583ed781c419193614cab13673ddf",
                  "label":"",
                  "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF0EEEF},
                    "size":{
                      "width":630,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF0EEEF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1600380967c04e1f815ee60fc3f9f0b1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF0EEEF},
                        "size":{
                          "width":630,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF0EEEF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/注册/u98.png"}},
{
                  "id":"1b1f06bd52d242618e6ec07be7465d65",
                  "label":"",
                  "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":80,
                      "y":5},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b8fb861b92bb4179b2489dff76eaa3c4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":80,
                          "y":5},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cf0890ec1afd4a9cb1b264516fd51efc",
                  "label":"",
                  "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                  "panelIndex":0,
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":5},
                    "size":{
                      "width":10,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/注册/u102_line.png"}},
{
                  "id":"b67823af9051406391f3679d7d35ff76",
                  "label":"",
                  "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":172,
                      "y":5},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d22538975e984362aac00d107f591d0e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":172,
                          "y":5},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2c10902095ab4ef69df946a94636963e",
                  "label":"",
                  "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                  "panelIndex":0,
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":253,
                      "y":5},
                    "size":{
                      "width":10,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/注册/u102_line.png"}},
{
                  "id":"a3cbcc1898374b8ba1c703b07b34a793",
                  "label":"",
                  "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":263,
                      "y":5},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a206aadda76e41b88ff6bc756f4a1643",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":263,
                          "y":5},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"57e82121ed4d4b74a0dfe5a7a51e193e",
                  "label":"",
                  "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                  "panelIndex":0,
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":342,
                      "y":5},
                    "size":{
                      "width":10,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/注册/u102_line.png"}},
{
                  "id":"68014f5c35be40fab77e60791f3cbbc4",
                  "label":"",
                  "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":353,
                      "y":5},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"21e88153d74e4b9ab313253ccfeaf763",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":353,
                          "y":5},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d676eb6de4f04c0a80a6bcb073b1d813",
                  "label":"",
                  "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                  "panelIndex":0,
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":432,
                      "y":5},
                    "size":{
                      "width":10,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF666666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/注册/u102_line.png"}},
{
                  "id":"06581331db2741ceb995fcc1abeadcc7",
                  "label":"",
                  "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "location":{
                      "x":442,
                      "y":5},
                    "size":{
                      "width":80,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"69ecdd4902bc4272bc24136895fa6eb3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88becb3417ac4b27838bfe9ebfa04a2f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "location":{
                          "x":442,
                          "y":5},
                        "size":{
                          "width":80,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"cf40fe5983be4e7b8e9cddfea86fe437",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":320,
              "y":259},
            "size":{
              "width":332,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc6ae7dccca9450ea1dbecde9c3cd5b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":320,
                  "y":259},
                "size":{
                  "width":332,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c552362686444abc9d59c150bb989ae0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":636,
              "y":339},
            "size":{
              "width":420,
              "height":57},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"108bef18b62d4bd694b292364a9d511c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":636,
                  "y":339},
                "size":{
                  "width":420,
                  "height":57},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第二步-修改密码/u30.png"}},
{
          "id":"54d1dd9f8d0e44f8ad0d82d605954c0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":1052,
              "y":62},
            "size":{
              "width":72,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f62eacfec8c44da9aa191cab20d7786d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":1052,
                  "y":62},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"9141f202783a492d81d91b0b4517ecea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":961,
              "y":62},
            "size":{
              "width":73,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78f7662fca8e419b9f7a6fb91c2890d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":961,
                  "y":62},
                "size":{
                  "width":73,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"f61b75fce2d54518933f7885ab9af13f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":907,
              "y":62},
            "size":{
              "width":54,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c12203890dee4814ae4368d3a35117aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":907,
                  "y":62},
                "size":{
                  "width":54,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"1bbd2d952d794127a3a594e360d177dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":1142,
              "y":62},
            "size":{
              "width":72,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ec7217ef8f2492a8cb386d3ca0ae775",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":1142,
                  "y":62},
                "size":{
                  "width":72,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "16efe71f694542b28cb5d9e367d0763a":{
      "scriptId":"u0"},
    "e1cc588e823344eaa9099ff60eab008d":{
      "scriptId":"u1"},
    "407798fcea3e4d7e86a6c469951c860a":{
      "scriptId":"u2"},
    "08034218dd194f17813a1464b957076a":{
      "scriptId":"u3"},
    "d63c9fabf5304de19a4e5c1d381cd133":{
      "scriptId":"u4"},
    "7519b74ee54249a6b759874322312b8f":{
      "scriptId":"u5"},
    "7f2b54e2d8504d4e965624977a93b7e9":{
      "scriptId":"u6"},
    "ac45a896450f48e4858de27a957ccbcd":{
      "scriptId":"u7"},
    "0a07b2394b1147b38111362319e899fa":{
      "scriptId":"u8"},
    "94bfe3d4554a426ea87cd050b69e9d78":{
      "scriptId":"u9"},
    "37310b19f1ff43feb0cec578d92c376d":{
      "scriptId":"u10"},
    "06dc58f91e7649dd89ae6f3a5b4ef2f1":{
      "scriptId":"u11"},
    "fa5e06f1e77948839eef950b2cef6b1a":{
      "scriptId":"u12"},
    "a48fecafb56c470eb18f4b4253445eaa":{
      "scriptId":"u13"},
    "ea425168d4ed4721b9999f51afb4cde4":{
      "scriptId":"u14"},
    "7d0733df4b964e2a88ae2c95cb78b418":{
      "scriptId":"u15"},
    "8efd98a4a98646e7b29a4a51cb7b3e46":{
      "scriptId":"u16"},
    "5f45aece0bd54bc991fed217a31d6dd3":{
      "scriptId":"u17"},
    "688ab95fde3c4147bd9e4561cff938f9":{
      "scriptId":"u18"},
    "8a34d2844f114501af21e29b65839616":{
      "scriptId":"u19"},
    "e78588404d74448dbc7a7ecd906f9100":{
      "scriptId":"u20"},
    "455b7400925f4bf18a666ddd781401f8":{
      "scriptId":"u21"},
    "6aee509859fc49acaee35522aa35f23d":{
      "scriptId":"u22"},
    "b42a6dc3344f462b8ca340151b181a37":{
      "scriptId":"u23"},
    "e88183c9e4044ae099c0a01dc6c1238c":{
      "scriptId":"u24"},
    "bf4513f3cb874092b3d0da8c980daad6":{
      "scriptId":"u25"},
    "65cdf1541b344abd8eb0e126ee970bac":{
      "scriptId":"u26"},
    "cc15c4bec08743658cc1633b4674b489":{
      "scriptId":"u27"},
    "e60b46d0fc964291817a9b81517575b6":{
      "scriptId":"u28"},
    "205292b49ff0404281777b647e1bb8a8":{
      "scriptId":"u29"},
    "a35032688ed1404a9455a4589aa041fe":{
      "scriptId":"u30"},
    "6bd8062b19ba4db893d4ce631461a10d":{
      "scriptId":"u31"},
    "553d6ba4e8da472cbb4b163eba219443":{
      "scriptId":"u32"},
    "84dd27518aae41c6b9fa797eb90a7fd2":{
      "scriptId":"u33"},
    "1ce1cc8926a24d9d94b53fa41a3d2a59":{
      "scriptId":"u34"},
    "ce384dda63d0425b9663a62009efbcdb":{
      "scriptId":"u35"},
    "1b0e1c3c1e254c69890f788f9dfccb84":{
      "scriptId":"u36"},
    "7b99d9992b9d4386a2955ad2f26209f1":{
      "scriptId":"u37"},
    "9e304d82f93b44438e5edead1b22c278":{
      "scriptId":"u38"},
    "be47ef09a4864754acd322a0c9c8edcc":{
      "scriptId":"u39"},
    "2af396a58b35450aa09d23bca1b24705":{
      "scriptId":"u40"},
    "e438e7a16ebc471cb2a39e204097cb12":{
      "scriptId":"u41"},
    "b77660216ed4454e831c6bd3fb83e0e3":{
      "scriptId":"u42"},
    "2575b814170a4ba2acc68d443fe5bd99":{
      "scriptId":"u43"},
    "6d6397badd0d48c29e66e77d9146791e":{
      "scriptId":"u44"},
    "e8123eaa60c040be977312da8be865fb":{
      "scriptId":"u45"},
    "2c27e4ee5a2b48efbd3b8087c9ee8953":{
      "scriptId":"u46"},
    "28c29d3bc98843ddbf1ea9e89c61e1ec":{
      "scriptId":"u47"},
    "2adcb65dffa8437391978dfcab38f106":{
      "scriptId":"u48"},
    "9dcec41181624ede9ad3cebee2942be9":{
      "scriptId":"u49"},
    "1f8b7c0e9dbb49b48ed3fa36c0549025":{
      "scriptId":"u50"},
    "87ecdf468b034803b22b7fb692aa0fe6":{
      "scriptId":"u51"},
    "0cc7e77cc6de4060932f96bc7eea6cb6":{
      "scriptId":"u52"},
    "ec229d23beaa4c33ae7882e1220f804c":{
      "scriptId":"u53"},
    "2d4c77901ff144d79fd0f90f3092361c":{
      "scriptId":"u54"},
    "13f8e05b236f4a9a82befa10ea7d31b8":{
      "scriptId":"u55"},
    "88becb3417ac4b27838bfe9ebfa04a2f":{
      "scriptId":"u56"},
    "79252bde6db949809c8c469963635cef":{
      "scriptId":"u57"},
    "25aa5a0c2f434086bfcab03411f32ef9":{
      "scriptId":"u58"},
    "719583ed781c419193614cab13673ddf":{
      "scriptId":"u59"},
    "1600380967c04e1f815ee60fc3f9f0b1":{
      "scriptId":"u60"},
    "1b1f06bd52d242618e6ec07be7465d65":{
      "scriptId":"u61"},
    "b8fb861b92bb4179b2489dff76eaa3c4":{
      "scriptId":"u62"},
    "cf0890ec1afd4a9cb1b264516fd51efc":{
      "scriptId":"u63"},
    "b67823af9051406391f3679d7d35ff76":{
      "scriptId":"u64"},
    "d22538975e984362aac00d107f591d0e":{
      "scriptId":"u65"},
    "2c10902095ab4ef69df946a94636963e":{
      "scriptId":"u66"},
    "a3cbcc1898374b8ba1c703b07b34a793":{
      "scriptId":"u67"},
    "a206aadda76e41b88ff6bc756f4a1643":{
      "scriptId":"u68"},
    "57e82121ed4d4b74a0dfe5a7a51e193e":{
      "scriptId":"u69"},
    "68014f5c35be40fab77e60791f3cbbc4":{
      "scriptId":"u70"},
    "21e88153d74e4b9ab313253ccfeaf763":{
      "scriptId":"u71"},
    "d676eb6de4f04c0a80a6bcb073b1d813":{
      "scriptId":"u72"},
    "06581331db2741ceb995fcc1abeadcc7":{
      "scriptId":"u73"},
    "69ecdd4902bc4272bc24136895fa6eb3":{
      "scriptId":"u74"},
    "cf40fe5983be4e7b8e9cddfea86fe437":{
      "scriptId":"u75"},
    "dc6ae7dccca9450ea1dbecde9c3cd5b1":{
      "scriptId":"u76"},
    "c552362686444abc9d59c150bb989ae0":{
      "scriptId":"u77"},
    "108bef18b62d4bd694b292364a9d511c":{
      "scriptId":"u78"},
    "54d1dd9f8d0e44f8ad0d82d605954c0e":{
      "scriptId":"u79"},
    "f62eacfec8c44da9aa191cab20d7786d":{
      "scriptId":"u80"},
    "9141f202783a492d81d91b0b4517ecea":{
      "scriptId":"u81"},
    "78f7662fca8e419b9f7a6fb91c2890d4":{
      "scriptId":"u82"},
    "f61b75fce2d54518933f7885ab9af13f":{
      "scriptId":"u83"},
    "c12203890dee4814ae4368d3a35117aa":{
      "scriptId":"u84"},
    "1bbd2d952d794127a3a594e360d177dc":{
      "scriptId":"u85"},
    "2ec7217ef8f2492a8cb386d3ca0ae775":{
      "scriptId":"u86"}}});