$axure.loadCurrentPage({
  "url":"账号管理-账号列表-完成.html",
  "generationDate":new Date(1441157430170.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d1a2db900dfe4aebaa720b27ceb9a3f6",
    "type":"Axure:Page",
    "name":"账号管理-账号列表-完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6a517efe55fa494c87b6f9b65f3f953e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":1180,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f415491fc656485f89b888d1c10e47d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":1180,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u0.png"}},
{
          "id":"06d02ef3d8ed4b1f829b6f954462d993",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":140},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be7a4d93f3ee4cc28ced52f831c58f1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":140},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"24e9e7c42fa744ce954d148656d30d98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":190},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fa6f6e5a9934e4090fc3cf70e116a98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":190},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"ed837e749e64496da8608bf7c72e4c8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":240},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"229a60c7056340acb0cc48e0b0d0bf70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":240},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"b11533f198d0476c9eb00b8ee12e173e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":290},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de37ef4069c14743b9e6ae24742448aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":290},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"0e7e1a0bddba409cbf7d33f9f998adf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":340},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8a03e6112dd40bb8ff0c3d3343b6781",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":340},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"112326507983476e87a4e698efdbbd42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":55,
              "y":390},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"342782384ca2470e9abc1332d10f5f25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":55,
                  "y":390},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账号管理-账号列表-完成/u12.png"}},
{
          "id":"99e39f50add742c6bf866dde9dd3a8c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":440},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81959409dc3947699fb51634695de96e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":440},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"5ca7c0c8aacc46538063ddf9aa3d015d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":490},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cabde4e9ce74fe4b476cc013df5e491",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":490},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"d7db9ba6654944f1b575aa284d763470",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":76},
            "size":{
              "width":1180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/预约管理-未下载-完成/u18_line.png"}},
{
          "id":"978e8e88043e416184f99636a3f887a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":26},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b06efa9b760841ad9b592f3b5094aabc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":26},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"476b38f7aea84badab3e4cbeabd28a59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1137,
              "y":26},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ed7d311e41d469dbefd9ed71edd707d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1137,
                  "y":26},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52a92c85fc0f4a7a8bebd85141e91ec1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":18},
            "size":{
              "width":135,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f4e1774dcf0442d9ef1efd9f42983cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":18},
                "size":{
                  "width":135,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u23.png"}},
{
          "id":"966b392366f148c8812a5eecec3c18c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":33},
            "size":{
              "width":270,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8834a23561644bab5d3183436b16c8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":33},
                "size":{
                  "width":270,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08f35d4352af4ab2a8d4d5ef9afe7d31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":52},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f52fd03473eb4c90af29ba138926da7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":52},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57b07c82b0674f9cbd602f8b0719b4e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1147,
              "y":52},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd1cb2f736f24bdd8cd97147d34f07a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1147,
                  "y":52},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6a2466133ef4c6d99d175f090114ea6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":140},
            "size":{
              "width":950,
              "height":400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10f6903cd56642d782ceec5cceae592c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":140},
                "size":{
                  "width":950,
                  "height":400}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加和编辑页面-完成/u31.png"}},
{
          "id":"94720dac4cff4376887b3a0101207e6b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":152.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d6cec70586cc4cb895306d66fc439f05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":566,
              "y":152},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b77db11ea8744456b6ea06ff7a53ed19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":566,
                  "y":152},
                "size":{
                  "width":50,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u37.png"}},
{
          "id":"f468385f973d49c6a86b640878778380",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":187},
            "size":{
              "width":815,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e56fdaf9f634461ab19e6925e1f87ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"49205231f129443692655cf49c4769f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u44.png"}},
{
              "id":"58a05a6e127c442c94f9647d4367e110",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":150,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"836990b138f642f0a7a6cb567215d065",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":150,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u54.png"}},
{
              "id":"d9810e29b35641ccbde113e0d91e18f2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":77},
                "size":{
                  "width":150,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a8e612214daf4c51a706a56e1cb60566",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":77},
                    "size":{
                      "width":150,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u64.png"}},
{
              "id":"ae425b96d057479cbfbac41c52b94d47",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":313,
                  "y":0},
                "size":{
                  "width":166,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb59ffbe6dfe4c36bf0d85a7e5fb5d6d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":313,
                      "y":0},
                    "size":{
                      "width":166,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u46.png"}},
{
              "id":"542711ef29f246ba8ecefbd34f73fe40",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":313,
                  "y":40},
                "size":{
                  "width":166,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aa3d238661104f94a817246982994ac7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":313,
                      "y":40},
                    "size":{
                      "width":166,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u56.png"}},
{
              "id":"c48dc10ca3d34368afd4af504c834501",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":313,
                  "y":77},
                "size":{
                  "width":166,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6d0a6deaf51b4e7a99acf4e2909c5aa5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":313,
                      "y":77},
                    "size":{
                      "width":166,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u66.png"}},
{
              "id":"981ac9645d99418ba982e11e0bdb7445",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":479,
                  "y":0},
                "size":{
                  "width":153,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83df82a567694317868e63c631d658da",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":479,
                      "y":0},
                    "size":{
                      "width":153,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u41.png"}},
{
              "id":"899d00b735ad46a1a81dacaadd855807",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":479,
                  "y":40},
                "size":{
                  "width":153,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1197da9d4004bd5b077cef1c9d4fd04",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":479,
                      "y":40},
                    "size":{
                      "width":153,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u49.png"}},
{
              "id":"f73ef1333a784938befcb2698c40efe6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":479,
                  "y":77},
                "size":{
                  "width":153,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bf6f21e72b1547a18ecfde5b56de9567",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":479,
                      "y":77},
                    "size":{
                      "width":153,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u57.png"}},
{
              "id":"0adbd7db6fca49588a669fe3ba4e80a7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":632,
                  "y":0},
                "size":{
                  "width":183,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4f2e5a6e6d114f05967d7aabd744f425",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":632,
                      "y":0},
                    "size":{
                      "width":183,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u43.png"}},
{
              "id":"5a7cf60617bd476b9badc837b1c4b75e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":632,
                  "y":40},
                "size":{
                  "width":183,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"08b65cfef2ca49c0b8d1d63a1442ace1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000CC,
                      "opacity":1},
                    "location":{
                      "x":632,
                      "y":40},
                    "size":{
                      "width":183,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u51.png"}},
{
              "id":"2aacffd829504422a4a7dafbe7a3eb5b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":632,
                  "y":77},
                "size":{
                  "width":183,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b508b6f65c2e468d8acf4fb1f0b9ac9e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000CC,
                      "opacity":1},
                    "location":{
                      "x":632,
                      "y":77},
                    "size":{
                      "width":183,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/角色管理-角色列表-完成/u59.png"}},
{
              "id":"b705f124b2b741aeb601759b41be425e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":150,
                  "y":0},
                "size":{
                  "width":163,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"479d21b85eb64ebea93997b62718c13e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":150,
                      "y":0},
                    "size":{
                      "width":163,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/账号管理-账号列表-完成/u39.png"}},
{
              "id":"c883015bb9e14f4ba6054451eeec204c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":40},
                "size":{
                  "width":163,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f99a3a2d42b949d393e9794dd1339f34",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":40},
                    "size":{
                      "width":163,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/账号管理-账号列表-完成/u49.png"}},
{
              "id":"c92ac5eadb8e482ebdc2db66a713a2a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":77},
                "size":{
                  "width":163,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a6e283edff734314beb135f33d824813",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":77},
                    "size":{
                      "width":163,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/账号管理-账号列表-完成/u59.png"}}]},
{
          "id":"0bc0cc83daa44537ba8932e51d2d26d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":370},
            "size":{
              "width":560,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b62ed862edb546dd99e6ebf6516255ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":370},
                "size":{
                  "width":560,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u101.png"}},
{
          "id":"b48fc4ecbc104fb0aba0c80fe609eb24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":104},
            "size":{
              "width":225,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a7ddb4c5c094d269623f958e6651dd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":104},
                "size":{
                  "width":225,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"284f766ffcb84107a1a5496788af4579",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":156},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6929f32ea6ea4a2a84dc3c956091e2b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":156},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2847a810bc8f40efba0fa8fa4eb84300",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":626,
              "y":152},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c1d3ce0da6f40bab9a6d878ea5a199f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":626,
                  "y":152},
                "size":{
                  "width":50,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u37.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6a517efe55fa494c87b6f9b65f3f953e":{
      "scriptId":"u0"},
    "f415491fc656485f89b888d1c10e47d6":{
      "scriptId":"u1"},
    "06d02ef3d8ed4b1f829b6f954462d993":{
      "scriptId":"u2"},
    "be7a4d93f3ee4cc28ced52f831c58f1a":{
      "scriptId":"u3"},
    "24e9e7c42fa744ce954d148656d30d98":{
      "scriptId":"u4"},
    "8fa6f6e5a9934e4090fc3cf70e116a98":{
      "scriptId":"u5"},
    "ed837e749e64496da8608bf7c72e4c8b":{
      "scriptId":"u6"},
    "229a60c7056340acb0cc48e0b0d0bf70":{
      "scriptId":"u7"},
    "b11533f198d0476c9eb00b8ee12e173e":{
      "scriptId":"u8"},
    "de37ef4069c14743b9e6ae24742448aa":{
      "scriptId":"u9"},
    "0e7e1a0bddba409cbf7d33f9f998adf9":{
      "scriptId":"u10"},
    "c8a03e6112dd40bb8ff0c3d3343b6781":{
      "scriptId":"u11"},
    "112326507983476e87a4e698efdbbd42":{
      "scriptId":"u12"},
    "342782384ca2470e9abc1332d10f5f25":{
      "scriptId":"u13"},
    "99e39f50add742c6bf866dde9dd3a8c3":{
      "scriptId":"u14"},
    "81959409dc3947699fb51634695de96e":{
      "scriptId":"u15"},
    "5ca7c0c8aacc46538063ddf9aa3d015d":{
      "scriptId":"u16"},
    "1cabde4e9ce74fe4b476cc013df5e491":{
      "scriptId":"u17"},
    "d7db9ba6654944f1b575aa284d763470":{
      "scriptId":"u18"},
    "978e8e88043e416184f99636a3f887a7":{
      "scriptId":"u19"},
    "b06efa9b760841ad9b592f3b5094aabc":{
      "scriptId":"u20"},
    "476b38f7aea84badab3e4cbeabd28a59":{
      "scriptId":"u21"},
    "5ed7d311e41d469dbefd9ed71edd707d":{
      "scriptId":"u22"},
    "52a92c85fc0f4a7a8bebd85141e91ec1":{
      "scriptId":"u23"},
    "5f4e1774dcf0442d9ef1efd9f42983cb":{
      "scriptId":"u24"},
    "966b392366f148c8812a5eecec3c18c8":{
      "scriptId":"u25"},
    "f8834a23561644bab5d3183436b16c8c":{
      "scriptId":"u26"},
    "08f35d4352af4ab2a8d4d5ef9afe7d31":{
      "scriptId":"u27"},
    "f52fd03473eb4c90af29ba138926da7c":{
      "scriptId":"u28"},
    "57b07c82b0674f9cbd602f8b0719b4e1":{
      "scriptId":"u29"},
    "cd1cb2f736f24bdd8cd97147d34f07a5":{
      "scriptId":"u30"},
    "e6a2466133ef4c6d99d175f090114ea6":{
      "scriptId":"u31"},
    "10f6903cd56642d782ceec5cceae592c":{
      "scriptId":"u32"},
    "94720dac4cff4376887b3a0101207e6b":{
      "scriptId":"u33"},
    "d6cec70586cc4cb895306d66fc439f05":{
      "scriptId":"u34"},
    "b77db11ea8744456b6ea06ff7a53ed19":{
      "scriptId":"u35"},
    "f468385f973d49c6a86b640878778380":{
      "scriptId":"u36"},
    "4e56fdaf9f634461ab19e6925e1f87ff":{
      "scriptId":"u37"},
    "49205231f129443692655cf49c4769f7":{
      "scriptId":"u38"},
    "b705f124b2b741aeb601759b41be425e":{
      "scriptId":"u39"},
    "479d21b85eb64ebea93997b62718c13e":{
      "scriptId":"u40"},
    "ae425b96d057479cbfbac41c52b94d47":{
      "scriptId":"u41"},
    "fb59ffbe6dfe4c36bf0d85a7e5fb5d6d":{
      "scriptId":"u42"},
    "981ac9645d99418ba982e11e0bdb7445":{
      "scriptId":"u43"},
    "83df82a567694317868e63c631d658da":{
      "scriptId":"u44"},
    "0adbd7db6fca49588a669fe3ba4e80a7":{
      "scriptId":"u45"},
    "4f2e5a6e6d114f05967d7aabd744f425":{
      "scriptId":"u46"},
    "58a05a6e127c442c94f9647d4367e110":{
      "scriptId":"u47"},
    "836990b138f642f0a7a6cb567215d065":{
      "scriptId":"u48"},
    "c883015bb9e14f4ba6054451eeec204c":{
      "scriptId":"u49"},
    "f99a3a2d42b949d393e9794dd1339f34":{
      "scriptId":"u50"},
    "542711ef29f246ba8ecefbd34f73fe40":{
      "scriptId":"u51"},
    "aa3d238661104f94a817246982994ac7":{
      "scriptId":"u52"},
    "899d00b735ad46a1a81dacaadd855807":{
      "scriptId":"u53"},
    "e1197da9d4004bd5b077cef1c9d4fd04":{
      "scriptId":"u54"},
    "5a7cf60617bd476b9badc837b1c4b75e":{
      "scriptId":"u55"},
    "08b65cfef2ca49c0b8d1d63a1442ace1":{
      "scriptId":"u56"},
    "d9810e29b35641ccbde113e0d91e18f2":{
      "scriptId":"u57"},
    "a8e612214daf4c51a706a56e1cb60566":{
      "scriptId":"u58"},
    "c92ac5eadb8e482ebdc2db66a713a2a9":{
      "scriptId":"u59"},
    "a6e283edff734314beb135f33d824813":{
      "scriptId":"u60"},
    "c48dc10ca3d34368afd4af504c834501":{
      "scriptId":"u61"},
    "6d0a6deaf51b4e7a99acf4e2909c5aa5":{
      "scriptId":"u62"},
    "f73ef1333a784938befcb2698c40efe6":{
      "scriptId":"u63"},
    "bf6f21e72b1547a18ecfde5b56de9567":{
      "scriptId":"u64"},
    "2aacffd829504422a4a7dafbe7a3eb5b":{
      "scriptId":"u65"},
    "b508b6f65c2e468d8acf4fb1f0b9ac9e":{
      "scriptId":"u66"},
    "0bc0cc83daa44537ba8932e51d2d26d2":{
      "scriptId":"u67"},
    "b62ed862edb546dd99e6ebf6516255ad":{
      "scriptId":"u68"},
    "b48fc4ecbc104fb0aba0c80fe609eb24":{
      "scriptId":"u69"},
    "9a7ddb4c5c094d269623f958e6651dd5":{
      "scriptId":"u70"},
    "284f766ffcb84107a1a5496788af4579":{
      "scriptId":"u71"},
    "6929f32ea6ea4a2a84dc3c956091e2b6":{
      "scriptId":"u72"},
    "2847a810bc8f40efba0fa8fa4eb84300":{
      "scriptId":"u73"},
    "5c1d3ce0da6f40bab9a6d878ea5a199f":{
      "scriptId":"u74"}}});