$axure.loadCurrentPage({
  "url":"用户管理-商户列表-完成.html",
  "generationDate":new Date(1441157429688.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"14e615608c3140a28c007b637d8e53ea",
    "type":"Axure:Page",
    "name":"用户管理-商户列表-完成",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"18a0f17368d24d13bf6c8ecedee28e08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":10},
            "size":{
              "width":1180,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5149cd6c76ef4de4aef8e2deba306063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":10},
                "size":{
                  "width":1180,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u0.png"}},
{
          "id":"666ac07762bc4a25bc993d19f6984386",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":140},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4f1c57c7d804237bd7ac3edc52c48ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":140},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"2690311696154f0b9ebbb5b9eea38e53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":55,
              "y":190},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2aa43eaf5b3434ba9958aa550504bfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":55,
                  "y":190},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u2.png"}},
{
          "id":"233453d39eed4b75b8d4bff1cd6bdaf5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":240},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62c9c966cf62440da86e01227e413ea7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":240},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"cc09bca23c134d52b76a371761452871",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":290},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5c30f73f2994412a969465f8139bd3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":290},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"644cb39c47634db586fbba77c34882ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":340},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90243337d32549e0a273e194e5908d23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":340},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"eaffca56be6946b8b2d9339d0efcba3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":390},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5697e894303446a2aaaaa5dddb309b6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":390},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"090049fb485c4b0ebf69a3f4332418a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":440},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eef065b946944709ce0480dac652d7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":440},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"3a8e08246374499c83c637e3095c6e82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":490},
            "size":{
              "width":165,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c13871483f94434598f4275939c87587",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":490},
                "size":{
                  "width":165,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u4.png"}},
{
          "id":"a37babd51ab049b78e86c877f6f032b2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":76},
            "size":{
              "width":1180,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/预约管理-未下载-完成/u18_line.png"}},
{
          "id":"16fdc53ef2634e66a58528fe5a5c4313",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":26},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b993b19884d9469eac60756045086106",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":26},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f284bf704d04c38b0ff97f9a17e16d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1137,
              "y":26},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45a225bafb20491381ad8de902124ade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1137,
                  "y":26},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5d874503aa84295bbb9f8a3b9f646f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":18},
            "size":{
              "width":135,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b04aacdc2fe4a54a50ef5c846ab9e14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":18},
                "size":{
                  "width":135,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u23.png"}},
{
          "id":"fca7e9a51d6b4c9a8e395362ade2032a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":33},
            "size":{
              "width":270,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff3a95459007463094df8fff23bec740",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":33},
                "size":{
                  "width":270,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59f317eef4f14bd3b206218e317aa39a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1016,
              "y":52},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15c4c9ed7a7740d88b3f7b2446634c9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1016,
                  "y":52},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cadc05c4f384ac3aaac929c470a10a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1147,
              "y":52},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93dd44424f3b499cb0dc0ee171405fbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1147,
                  "y":52},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b38d25b051c4a10b8feca748652b123",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":190},
            "size":{
              "width":950,
              "height":350}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"383eaad47d0f426eba079d5ec50fe438",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":190},
                "size":{
                  "width":950,
                  "height":350}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户管理-个人用户列表-完成/u31.png"}},
{
          "id":"e8f5406358844734a8b99590f2e0f68b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":623,
              "y":200},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"872f77a5d5454437ae56c2a2172e81b7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":200},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0745a1f9894d4110b9971c95c5f894d3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":419,
              "y":208},
            "size":{
              "width":15,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/预约管理-未下载-完成/u35_line.png"}},
{
          "id":"6c9272f7f9cc4950bea447b5d78161ca",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":444,
              "y":200},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"30f0fe5ead4e4f2f81304ea29081c256",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":853,
              "y":200},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf09cf290dea48a995a2fac839929c97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":853,
                  "y":200},
                "size":{
                  "width":50,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u37.png"}},
{
          "id":"659507317b804f2a87c504c634f2eab2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":150},
            "size":{
              "width":119,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9537f44e88242a99efe8d6334581479",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":150},
                "size":{
                  "width":119,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户管理-商户列表-完成/u39.png"}},
{
          "id":"cc61f4bf63824f9bb88c733b358f202c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":369,
              "y":150},
            "size":{
              "width":119,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c6040d525274dc49f710826ba856d5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":369,
                  "y":150},
                "size":{
                  "width":119,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u39.png"}},
{
          "id":"656956c0b47445e29aafb58306c5b2c3",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":244},
            "size":{
              "width":699,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32de575572a849f099fa5bc0d68625f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":135,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e8e6a758c3b84efa90e3f906c440b706",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":135,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-商户列表-完成/u44.png"}},
{
              "id":"072d84ed7f344f07a766f8380b19659d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":135,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"72c4af502c974985baaf52ebc1764608",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":135,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-商户列表-完成/u54.png"}},
{
              "id":"bcfd2290384e42d387090d0b7876dad4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":77},
                "size":{
                  "width":135,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"15f1ee3f5fb04f488307e2a9c3efdabc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":77},
                    "size":{
                      "width":135,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-商户列表-完成/u64.png"}},
{
              "id":"fdcaebfa7b5e456190b84b4769d49b57",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":135,
                  "y":0},
                "size":{
                  "width":135,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e53b9a74b94a4ae5a347e9de2c30c0d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":135,
                      "y":0},
                    "size":{
                      "width":135,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-商户列表-完成/u44.png"}},
{
              "id":"1eef1745a0dc44f4837cf0558a7f30fd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":40},
                "size":{
                  "width":135,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e88b1d8d1fc4e0f8520549abb1cdc75",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":40},
                    "size":{
                      "width":135,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-商户列表-完成/u54.png"}},
{
              "id":"cdcccbaa4a9841ffa8dcac2831dab7f5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":77},
                "size":{
                  "width":135,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4f1deaa644bd42499887d1a055f0ce5a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":77},
                    "size":{
                      "width":135,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-商户列表-完成/u64.png"}},
{
              "id":"963a734207ea4744a8b0d0ef6fd2c6c6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":270,
                  "y":0},
                "size":{
                  "width":135,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"deec1bc06f7c41a5bf9286c21167a7dd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":270,
                      "y":0},
                    "size":{
                      "width":135,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-商户列表-完成/u44.png"}},
{
              "id":"121305f2bacc4560aa1d823e75d29655",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":270,
                  "y":40},
                "size":{
                  "width":135,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6daa102db6a44dd4b8292677297717ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":270,
                      "y":40},
                    "size":{
                      "width":135,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-商户列表-完成/u54.png"}},
{
              "id":"b8efba5d2c744b8fac20153a5096e483",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":270,
                  "y":77},
                "size":{
                  "width":135,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5703c547e96d44c4ba2315811408b521",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":270,
                      "y":77},
                    "size":{
                      "width":135,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-商户列表-完成/u64.png"}},
{
              "id":"6b22870e407849d09a8f01fa0e14de56",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":405,
                  "y":0},
                "size":{
                  "width":152,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f1c6b7a8180f42ba985749aa69c4cac3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":405,
                      "y":0},
                    "size":{
                      "width":152,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u50.png"}},
{
              "id":"62e85b0d2171488598a263c2c28484b1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":405,
                  "y":40},
                "size":{
                  "width":152,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a19d6729e934686843f58a6c01a7951",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":405,
                      "y":40},
                    "size":{
                      "width":152,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u60.png"}},
{
              "id":"af3e7b83a0774ab78e1e422c6f905649",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":405,
                  "y":77},
                "size":{
                  "width":152,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"84317a61c55a4663be606998d56c8e8d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":405,
                      "y":77},
                    "size":{
                      "width":152,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-个人用户列表-完成/u70.png"}},
{
              "id":"7535e01de0924cba96f3ef0ffa27c834",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":557,
                  "y":0},
                "size":{
                  "width":142,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2e64f870e6db4872af062cd83c8c4cb3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":557,
                      "y":0},
                    "size":{
                      "width":142,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-商户列表-完成/u52.png"}},
{
              "id":"417ccf7d0b1e4679be6264a4ee1d7d32",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":557,
                  "y":40},
                "size":{
                  "width":142,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8f9b38e6cfb14f07a7e10d77b765a60a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000CC,
                      "opacity":1},
                    "location":{
                      "x":557,
                      "y":40},
                    "size":{
                      "width":142,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-商户列表-完成/u62.png"}},
{
              "id":"7a8a2bebd7f446f4ba4163fc9732a10b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":557,
                  "y":77},
                "size":{
                  "width":142,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a82cc42606d44fa8e9df83dc96f9e97",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000CC,
                      "opacity":1},
                    "location":{
                      "x":557,
                      "y":77},
                    "size":{
                      "width":142,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/用户管理-商户列表-完成/u72.png"}}]},
{
          "id":"56a4d6f8e90245b5a8a022402c128a1c",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":533,
              "y":202},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"807b9623925e466bbea409fdd872dd47",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":452},
            "size":{
              "width":560,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"befc1dc99d1941e2a9b2ea3d45763dfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":452},
                "size":{
                  "width":560,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u101.png"}},
{
          "id":"f068140780d041b286d87c2c2f466efb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":104},
            "size":{
              "width":225,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1979d5c8df3413f84825c488b84e9a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":104},
                "size":{
                  "width":225,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4f9049d79dd424698ed933079e5b326",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":204},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21a778dae34645ffad99e48a5eef87fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":266,
                  "y":204},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54c8c2b3375a4487affefb691fd3d84d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":913,
              "y":200},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24728cfd00164013a333c21146394431",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":913,
                  "y":200},
                "size":{
                  "width":50,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/预约管理-未下载-完成/u37.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "18a0f17368d24d13bf6c8ecedee28e08":{
      "scriptId":"u0"},
    "5149cd6c76ef4de4aef8e2deba306063":{
      "scriptId":"u1"},
    "666ac07762bc4a25bc993d19f6984386":{
      "scriptId":"u2"},
    "e4f1c57c7d804237bd7ac3edc52c48ce":{
      "scriptId":"u3"},
    "2690311696154f0b9ebbb5b9eea38e53":{
      "scriptId":"u4"},
    "a2aa43eaf5b3434ba9958aa550504bfd":{
      "scriptId":"u5"},
    "233453d39eed4b75b8d4bff1cd6bdaf5":{
      "scriptId":"u6"},
    "62c9c966cf62440da86e01227e413ea7":{
      "scriptId":"u7"},
    "cc09bca23c134d52b76a371761452871":{
      "scriptId":"u8"},
    "f5c30f73f2994412a969465f8139bd3c":{
      "scriptId":"u9"},
    "644cb39c47634db586fbba77c34882ea":{
      "scriptId":"u10"},
    "90243337d32549e0a273e194e5908d23":{
      "scriptId":"u11"},
    "eaffca56be6946b8b2d9339d0efcba3c":{
      "scriptId":"u12"},
    "5697e894303446a2aaaaa5dddb309b6e":{
      "scriptId":"u13"},
    "090049fb485c4b0ebf69a3f4332418a2":{
      "scriptId":"u14"},
    "2eef065b946944709ce0480dac652d7e":{
      "scriptId":"u15"},
    "3a8e08246374499c83c637e3095c6e82":{
      "scriptId":"u16"},
    "c13871483f94434598f4275939c87587":{
      "scriptId":"u17"},
    "a37babd51ab049b78e86c877f6f032b2":{
      "scriptId":"u18"},
    "16fdc53ef2634e66a58528fe5a5c4313":{
      "scriptId":"u19"},
    "b993b19884d9469eac60756045086106":{
      "scriptId":"u20"},
    "4f284bf704d04c38b0ff97f9a17e16d3":{
      "scriptId":"u21"},
    "45a225bafb20491381ad8de902124ade":{
      "scriptId":"u22"},
    "a5d874503aa84295bbb9f8a3b9f646f3":{
      "scriptId":"u23"},
    "5b04aacdc2fe4a54a50ef5c846ab9e14":{
      "scriptId":"u24"},
    "fca7e9a51d6b4c9a8e395362ade2032a":{
      "scriptId":"u25"},
    "ff3a95459007463094df8fff23bec740":{
      "scriptId":"u26"},
    "59f317eef4f14bd3b206218e317aa39a":{
      "scriptId":"u27"},
    "15c4c9ed7a7740d88b3f7b2446634c9a":{
      "scriptId":"u28"},
    "7cadc05c4f384ac3aaac929c470a10a9":{
      "scriptId":"u29"},
    "93dd44424f3b499cb0dc0ee171405fbe":{
      "scriptId":"u30"},
    "7b38d25b051c4a10b8feca748652b123":{
      "scriptId":"u31"},
    "383eaad47d0f426eba079d5ec50fe438":{
      "scriptId":"u32"},
    "e8f5406358844734a8b99590f2e0f68b":{
      "scriptId":"u33"},
    "872f77a5d5454437ae56c2a2172e81b7":{
      "scriptId":"u34"},
    "0745a1f9894d4110b9971c95c5f894d3":{
      "scriptId":"u35"},
    "6c9272f7f9cc4950bea447b5d78161ca":{
      "scriptId":"u36"},
    "30f0fe5ead4e4f2f81304ea29081c256":{
      "scriptId":"u37"},
    "bf09cf290dea48a995a2fac839929c97":{
      "scriptId":"u38"},
    "659507317b804f2a87c504c634f2eab2":{
      "scriptId":"u39"},
    "d9537f44e88242a99efe8d6334581479":{
      "scriptId":"u40"},
    "cc61f4bf63824f9bb88c733b358f202c":{
      "scriptId":"u41"},
    "6c6040d525274dc49f710826ba856d5d":{
      "scriptId":"u42"},
    "656956c0b47445e29aafb58306c5b2c3":{
      "scriptId":"u43"},
    "32de575572a849f099fa5bc0d68625f4":{
      "scriptId":"u44"},
    "e8e6a758c3b84efa90e3f906c440b706":{
      "scriptId":"u45"},
    "fdcaebfa7b5e456190b84b4769d49b57":{
      "scriptId":"u46"},
    "e53b9a74b94a4ae5a347e9de2c30c0d2":{
      "scriptId":"u47"},
    "963a734207ea4744a8b0d0ef6fd2c6c6":{
      "scriptId":"u48"},
    "deec1bc06f7c41a5bf9286c21167a7dd":{
      "scriptId":"u49"},
    "6b22870e407849d09a8f01fa0e14de56":{
      "scriptId":"u50"},
    "f1c6b7a8180f42ba985749aa69c4cac3":{
      "scriptId":"u51"},
    "7535e01de0924cba96f3ef0ffa27c834":{
      "scriptId":"u52"},
    "2e64f870e6db4872af062cd83c8c4cb3":{
      "scriptId":"u53"},
    "072d84ed7f344f07a766f8380b19659d":{
      "scriptId":"u54"},
    "72c4af502c974985baaf52ebc1764608":{
      "scriptId":"u55"},
    "1eef1745a0dc44f4837cf0558a7f30fd":{
      "scriptId":"u56"},
    "4e88b1d8d1fc4e0f8520549abb1cdc75":{
      "scriptId":"u57"},
    "121305f2bacc4560aa1d823e75d29655":{
      "scriptId":"u58"},
    "6daa102db6a44dd4b8292677297717ad":{
      "scriptId":"u59"},
    "62e85b0d2171488598a263c2c28484b1":{
      "scriptId":"u60"},
    "3a19d6729e934686843f58a6c01a7951":{
      "scriptId":"u61"},
    "417ccf7d0b1e4679be6264a4ee1d7d32":{
      "scriptId":"u62"},
    "8f9b38e6cfb14f07a7e10d77b765a60a":{
      "scriptId":"u63"},
    "bcfd2290384e42d387090d0b7876dad4":{
      "scriptId":"u64"},
    "15f1ee3f5fb04f488307e2a9c3efdabc":{
      "scriptId":"u65"},
    "cdcccbaa4a9841ffa8dcac2831dab7f5":{
      "scriptId":"u66"},
    "4f1deaa644bd42499887d1a055f0ce5a":{
      "scriptId":"u67"},
    "b8efba5d2c744b8fac20153a5096e483":{
      "scriptId":"u68"},
    "5703c547e96d44c4ba2315811408b521":{
      "scriptId":"u69"},
    "af3e7b83a0774ab78e1e422c6f905649":{
      "scriptId":"u70"},
    "84317a61c55a4663be606998d56c8e8d":{
      "scriptId":"u71"},
    "7a8a2bebd7f446f4ba4163fc9732a10b":{
      "scriptId":"u72"},
    "5a82cc42606d44fa8e9df83dc96f9e97":{
      "scriptId":"u73"},
    "56a4d6f8e90245b5a8a022402c128a1c":{
      "scriptId":"u74"},
    "807b9623925e466bbea409fdd872dd47":{
      "scriptId":"u75"},
    "befc1dc99d1941e2a9b2ea3d45763dfd":{
      "scriptId":"u76"},
    "f068140780d041b286d87c2c2f466efb":{
      "scriptId":"u77"},
    "b1979d5c8df3413f84825c488b84e9a7":{
      "scriptId":"u78"},
    "c4f9049d79dd424698ed933079e5b326":{
      "scriptId":"u79"},
    "21a778dae34645ffad99e48a5eef87fd":{
      "scriptId":"u80"},
    "54c8c2b3375a4487affefb691fd3d84d":{
      "scriptId":"u81"},
    "24728cfd00164013a333c21146394431":{
      "scriptId":"u82"}}});