$axure.loadCurrentPage({
  "url":"尊享家.html",
  "generationDate":new Date(1440075583271.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3fcb674ccc8c42869b5875dadf887db3",
    "type":"Axure:Page",
    "name":"尊享家",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ecdec89727c94dcaacb1755d583a519d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":30},
            "size":{
              "width":1220,
              "height":1890}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c08a190e105448bb8ca9ecd05711458",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":30},
                "size":{
                  "width":1220,
                  "height":1890}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/尊享家/u0.png"}},
{
          "id":"d060799fcf8f4dffb440eceda8143483",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":110},
            "size":{
              "width":220,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baed716d9108488da1d59c46a9ffdf71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":110},
                "size":{
                  "width":220,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u2.png"}},
{
          "id":"8ccd8ac271db438d9d0e3bf0d956001d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":1220,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页-已登录/u4_line.png"}},
{
          "id":"69cbd6a9e9874bf99f5a6a16dcb3422e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":951,
              "y":41},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dea175286dab43d2b38ab716976a27f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":951,
                  "y":41},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b7ec0f73e8e42e4bb6d1185bede57b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":1001,
              "y":41},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"996902be4cba4f999398f62e6a0f4147",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":1001,
                  "y":41},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a547a56a8334eb5b79fd08976b15240",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1049,
              "y":110},
            "size":{
              "width":176,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"473b1d39705245cc85f25f65afb3c4ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1049,
                  "y":110},
                "size":{
                  "width":176,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u7.png"}},
{
          "id":"62bbd0196af74cb7af56a0751e78ab47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE9E9E9},
            "location":{
              "x":60,
              "y":1690},
            "size":{
              "width":1219,
              "height":220},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE9E9E9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"091463c9ccd44b2ab3b2e8d1207dfae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE9E9E9},
                "location":{
                  "x":60,
                  "y":1690},
                "size":{
                  "width":1219,
                  "height":220},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE9E9E9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u45.png"}},
{
          "id":"5fe8e94f55cb4bff9243bb4450c9f09c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":1716},
            "size":{
              "width":1084,
              "height":156}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9dc181a2eab4c75be1a252e52152865",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":1716},
                "size":{
                  "width":1084,
                  "height":156}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u47.png"}},
{
          "id":"0847fb5dccf2401e92c9d977b98fbdd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":1067,
              "y":41},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8ce5831a4d44713a82c9c088e3fc6bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":1067,
                  "y":41},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"db4384de27dc4e00aeec11608e30b42e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1}}},
            "location":{
              "x":1140,
              "y":41},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bc97a8249584aeb9433b763bcbb212f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1}}},
                "location":{
                  "x":1140,
                  "y":41},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"9d20bcae5bac4d1fb899ff25be758ced",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1129,
              "y":41},
            "size":{
              "width":11,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e680a4af2ab7437fb917451ed64657ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1129,
                  "y":41},
                "size":{
                  "width":11,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u18.png"}},
{
          "id":"54724ca1a5f44447aab1bf3cbf28b824",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1056,
              "y":41},
            "size":{
              "width":11,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8462c954e72043069db10850d99cf7fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1056,
                  "y":41},
                "size":{
                  "width":11,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u18.png"}},
{
          "id":"bf9cd7aeb97549c49d8f9cd90b69e109",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1002,
              "y":41},
            "size":{
              "width":11,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a43f4ec8afd34c218443bdb2d4c27e4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1002,
                  "y":41},
                "size":{
                  "width":11,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u18.png"}},
{
          "id":"6857fda9f25d432495601b0527e34db3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":380,
              "y":113},
            "size":{
              "width":60,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e58ee7d19d314b9196b5934523648533",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":380,
                  "y":113},
                "size":{
                  "width":60,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-已登录/u5.png"}},
{
          "id":"765dbc354126491b8d7f8fcfd322a5ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":526,
              "y":131},
            "size":{
              "width":52,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF84C225}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5400e94565634370b11c9a8f4eaa1553",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":526,
                  "y":131},
                "size":{
                  "width":52,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF84C225}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d000e244803e44b4867bbafe64f3b569",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1}}},
            "location":{
              "x":606,
              "y":131},
            "size":{
              "width":110,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10c973b5d14048e6900cd04d2e0261f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF84C225,
                      "opacity":1}}},
                "location":{
                  "x":606,
                  "y":131},
                "size":{
                  "width":110,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"eaca63cde1e245fea934aac5e033a480",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1}}},
            "location":{
              "x":870,
              "y":131},
            "size":{
              "width":110,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8fe25bca5984a538abdebe874d155ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF84C225,
                      "opacity":1}}},
                "location":{
                  "x":870,
                  "y":131},
                "size":{
                  "width":110,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"80cdb05d7e384eb9a0fd9a2965e53422",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":748.5,
              "y":165},
            "size":{
              "width":97,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF84C225}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/家装分期/u35_line.png"}},
{
          "id":"ccfb062d8f5340689618e078d7bfc63a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF84C225,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1}}},
            "location":{
              "x":742,
              "y":131},
            "size":{
              "width":110,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61dec98361514765936c76503d3d599b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF84C225,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF84C225,
                      "opacity":1}}},
                "location":{
                  "x":742,
                  "y":131},
                "size":{
                  "width":110,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏元件",
                      "objectsToFades":[]}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"f0498cd513fe43229b0042634fa3f52a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":773},
            "size":{
              "width":1105,
              "height":227}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d58947047e2949c79f9a88ce419382bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":773},
                "size":{
                  "width":1105,
                  "height":227}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/悦享家/u38.png"}},
{
          "id":"05a64ef58b06406e8acee6e43f88dce0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":217},
            "size":{
              "width":1219,
              "height":541}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f16d4a973394b8abb5b901746ee5e99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":217},
                "size":{
                  "width":1219,
                  "height":541}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/尊享家/u38.png"}},
{
          "id":"055596fd45ff4c27a37b58659cf1e9b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF87715A},
            "location":{
              "x":360,
              "y":680},
            "size":{
              "width":260,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF9B806B}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59ec4c8c0d854185862f2c919499d4a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF87715A},
                "location":{
                  "x":360,
                  "y":680},
                "size":{
                  "width":260,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF9B806B}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/尊享家/u40.png"}},
{
          "id":"777e83390274483baebde962a81e38a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD38C38},
            "location":{
              "x":177,
              "y":627},
            "size":{
              "width":160,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCA8332}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2387f091e6874fa485abf000768798a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD38C38},
                "location":{
                  "x":177,
                  "y":627},
                "size":{
                  "width":160,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCA8332}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/尊享家/u42.png"}},
{
          "id":"d1615e801a0c4980af8902f97c9072dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD38C38},
            "location":{
              "x":440,
              "y":627},
            "size":{
              "width":160,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCA8332}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28c67e07a3014f3cacad093a79bde895",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD38C38},
                "location":{
                  "x":440,
                  "y":627},
                "size":{
                  "width":160,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCA8332}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/尊享家/u42.png"}},
{
          "id":"86dfd85aaee947bb9e060dddd7b88d55",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFCF9F4},
            "location":{
              "x":180,
              "y":683},
            "size":{
              "width":160,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFDFAF3}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fc15347158546d9924ffafe9995889c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFCF9F4},
                "location":{
                  "x":180,
                  "y":683},
                "size":{
                  "width":160,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFDFAF3}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/悦享家/u46.png"}},
{
          "id":"cd255040b8d747daaf8147a651afaa7b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":1000},
            "size":{
              "width":1105,
              "height":166}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b1384baf41f45daad35555b1939806b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":1000},
                "size":{
                  "width":1105,
                  "height":166}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/尊享家/u48.png"}},
{
          "id":"25a697056a79466b97c61c1bf16a0fe5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":1166},
            "size":{
              "width":1105,
              "height":494}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d83b3cc0a3a480ca6826d3d44c14f65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":1166},
                "size":{
                  "width":1105,
                  "height":494}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/尊享家/u50.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ecdec89727c94dcaacb1755d583a519d":{
      "scriptId":"u0"},
    "6c08a190e105448bb8ca9ecd05711458":{
      "scriptId":"u1"},
    "d060799fcf8f4dffb440eceda8143483":{
      "scriptId":"u2"},
    "baed716d9108488da1d59c46a9ffdf71":{
      "scriptId":"u3"},
    "8ccd8ac271db438d9d0e3bf0d956001d":{
      "scriptId":"u4"},
    "69cbd6a9e9874bf99f5a6a16dcb3422e":{
      "scriptId":"u5"},
    "dea175286dab43d2b38ab716976a27f0":{
      "scriptId":"u6"},
    "3b7ec0f73e8e42e4bb6d1185bede57b9":{
      "scriptId":"u7"},
    "996902be4cba4f999398f62e6a0f4147":{
      "scriptId":"u8"},
    "9a547a56a8334eb5b79fd08976b15240":{
      "scriptId":"u9"},
    "473b1d39705245cc85f25f65afb3c4ee":{
      "scriptId":"u10"},
    "62bbd0196af74cb7af56a0751e78ab47":{
      "scriptId":"u11"},
    "091463c9ccd44b2ab3b2e8d1207dfae1":{
      "scriptId":"u12"},
    "5fe8e94f55cb4bff9243bb4450c9f09c":{
      "scriptId":"u13"},
    "c9dc181a2eab4c75be1a252e52152865":{
      "scriptId":"u14"},
    "0847fb5dccf2401e92c9d977b98fbdd7":{
      "scriptId":"u15"},
    "d8ce5831a4d44713a82c9c088e3fc6bc":{
      "scriptId":"u16"},
    "db4384de27dc4e00aeec11608e30b42e":{
      "scriptId":"u17"},
    "9bc97a8249584aeb9433b763bcbb212f":{
      "scriptId":"u18"},
    "9d20bcae5bac4d1fb899ff25be758ced":{
      "scriptId":"u19"},
    "e680a4af2ab7437fb917451ed64657ae":{
      "scriptId":"u20"},
    "54724ca1a5f44447aab1bf3cbf28b824":{
      "scriptId":"u21"},
    "8462c954e72043069db10850d99cf7fa":{
      "scriptId":"u22"},
    "bf9cd7aeb97549c49d8f9cd90b69e109":{
      "scriptId":"u23"},
    "a43f4ec8afd34c218443bdb2d4c27e4d":{
      "scriptId":"u24"},
    "6857fda9f25d432495601b0527e34db3":{
      "scriptId":"u25"},
    "e58ee7d19d314b9196b5934523648533":{
      "scriptId":"u26"},
    "765dbc354126491b8d7f8fcfd322a5ac":{
      "scriptId":"u27"},
    "5400e94565634370b11c9a8f4eaa1553":{
      "scriptId":"u28"},
    "d000e244803e44b4867bbafe64f3b569":{
      "scriptId":"u29"},
    "10c973b5d14048e6900cd04d2e0261f9":{
      "scriptId":"u30"},
    "eaca63cde1e245fea934aac5e033a480":{
      "scriptId":"u31"},
    "a8fe25bca5984a538abdebe874d155ab":{
      "scriptId":"u32"},
    "80cdb05d7e384eb9a0fd9a2965e53422":{
      "scriptId":"u33"},
    "ccfb062d8f5340689618e078d7bfc63a":{
      "scriptId":"u34"},
    "61dec98361514765936c76503d3d599b":{
      "scriptId":"u35"},
    "f0498cd513fe43229b0042634fa3f52a":{
      "scriptId":"u36"},
    "d58947047e2949c79f9a88ce419382bc":{
      "scriptId":"u37"},
    "05a64ef58b06406e8acee6e43f88dce0":{
      "scriptId":"u38"},
    "6f16d4a973394b8abb5b901746ee5e99":{
      "scriptId":"u39"},
    "055596fd45ff4c27a37b58659cf1e9b7":{
      "scriptId":"u40"},
    "59ec4c8c0d854185862f2c919499d4a3":{
      "scriptId":"u41"},
    "777e83390274483baebde962a81e38a9":{
      "scriptId":"u42"},
    "2387f091e6874fa485abf000768798a7":{
      "scriptId":"u43"},
    "d1615e801a0c4980af8902f97c9072dd":{
      "scriptId":"u44"},
    "28c67e07a3014f3cacad093a79bde895":{
      "scriptId":"u45"},
    "86dfd85aaee947bb9e060dddd7b88d55":{
      "scriptId":"u46"},
    "7fc15347158546d9924ffafe9995889c":{
      "scriptId":"u47"},
    "cd255040b8d747daaf8147a651afaa7b":{
      "scriptId":"u48"},
    "8b1384baf41f45daad35555b1939806b":{
      "scriptId":"u49"},
    "25a697056a79466b97c61c1bf16a0fe5":{
      "scriptId":"u50"},
    "9d83b3cc0a3a480ca6826d3d44c14f65":{
      "scriptId":"u51"}}});